README.md

`go install` only works if you already have the package checked out:
```
% go install github.com/twpayne/chezmoi
can't load package: package github.com/twpayne/chezmoi: cannot find package "github.com/twpayne/chezmoi" in any of:
/home/michael/sdk/go1.11rc1/src/github.com/twpayne/chezmoi (from $GOROOT)
/home/michael/go/src/github.com/twpayne/chezmoi (from $GOPATH)
```
`go get -u` can be used to install/update.

go install → go get -u

---

cmd/add.go
cmd/cat.go
cmd/cmd.go
cmd/dump.go
cmd/root.go
go.mod
go.sum
lib/chezmoi/chezmoi.go

[`github.com/pkg/errors`](https://github.com/pkg/errors) is great, but `chezmoi` doesn't use it consistently. Use `fmt.Errorf` instead, pending a proper review of errors.

Use fmt.Errorf instead of errors.Errorf

---

cmd/cmd.go
cmd/root.go
cmd/version.go
main.go

[goreleaser](https://goreleaser.com) sets various helpful version number variables. This PR adds a `version` command to print them.

Add version command

---

cmd/add.go
cmd/add_test.go
cmd/cmd.go
cmd/keyring.go
cmd/keyring_get.go
cmd/keyring_set.go

A number of fields of `Config` were exported, meaning that they could be overridden in the config file. This PR makes them private so they cannot be overridden in the config file.

Hide internal config

---

cmd/cat.go
lib/chezmoi/chezmoi.go
lib/chezmoi/chezmoi_test.go

Before this change, files were read and templates were evaluated when reading the source state. This meant that if there was an error in a template, this would raise an error immediately, and prevent the `chezmoi edit` command from allowing you to edit the faulty template.
With this change, file contents and symlink targets are only computed when needed. This allows editing of faulty templates and faster reading of the source state.

Only read files and evaluate templates when required

---

cmd/source_path.go

This PR adds a `source-path` command that prints out a target's source path, for example:
```
$ chezmoi source-path ~/.vimrc
/Users/twp/.chezmoi/dot_vimrc
```
It can be useful for scripts that need to modify files in `~/.chezmoi`.

Add source-path command

---

cmd/cmd.go
cmd/dump.go
go.mod
lib/chezmoi/chezmoi.go

This PR adds `--format` and `--recursive` commands to the `dump` command. Supported formats are JSON and YAML.

Dump in JSON and YAML formats

---

README.md
cmd/root.go
go.mod
go.sum

Existing users using `~/.chezmoi.*` as the config file and `~/.chezmoi` as the source directory will see no change, and these will remain supported for backwards compatibility.

Support XDG Base Directory Specification

---

.goreleaser.yaml
cmd/cmd.go

#65 turns out to be a bit more nuanced that I realized.
- Go's standard library will use the `mygetgrnam_r` library function to lookup groups on Linux, but only if cgo is enabled. Otherwise it falls back to searching `/etc/group`.
- `chezmoi` is built with [`goreleaser`](https://github.com/goreleaser/goreleaser.git), which has limited cgo support but this is currently disabled in `chezmoi`'s `.goreleaser.yml` config.
This PR enables cgo on Linux, and reverts the original fix.

Re-enable checking for LookupGroup errors

---

cmd/bitwarden.go
cmd/lastpass.go
cmd/vault.go

Fix #134 
Only display subcommands that have the necessary binary installed.
Verified using `vault`:
```
~/git/go/src/github.com/twpayne/chezmoi >> feature/supported_cmds $ go build -o cmoi
~/git/go/src/github.com/twpayne/chezmoi >> feature/supported_cmds $ ./cmoi -h
Manage your dotfiles securely across multiple machines
Usage:
chezmoi [command]
Available Commands:
add         Add an existing file, directory, or symlink to the source state
apply       Update the destination directory to match the target state
archive     Write a tar archive of the target state to stdout
cat         Write the target state of a file or symlink to stdout
cd          Launch a shell in the source directory
chattr      Change the attributes of a target in the source state
data        Write the template data to …
```

Hide / display commands based on availability

---

cmd/doctor.go

Redo of #137 because squashing broke the PR

Add doctor command

---

cmd/dump.go

Before this fix, running `chezmoi dump target` would always print `null`.

Fix dump command with targets

---

README.md

Make it clearer that the rpm packages work on OpenSUSE

---

.travis.yml
cmd/config.go
cmd/root.go

Fix #198 - Use os.UserHomeDir() instead of custom function

Fix #198 - Use os.UserHomeDir() instead of custom function

---

.goreleaser.yaml
CONTRIBUTING.md

Updates goreleaser to target ppc64 and ppc64le. I've run the build on my machine using the command below and it generates working binaries.
```bash
TRAVIS_BUILD_NUMBER=1 goreleaser --snapshot --rm-dist --debug --skip-publish
```
Note that I'm using go 1.12.1 on Gentoo to compile.
I also made a minor tweak to the contributing guide as it linked to the issues page for a different repo.
Closes #227

Fix for #227 - Add ppc64 and ppc64le targets

---

cmd/config.go
cmd/init.go
cmd/init_test.go
cmd/root.go

This implements using a config file template to bootstrap config files during `chezmoi init` as discussed via #241 
I did my best to cover this with tests but currently its not really possible to test the entire init command end to end. Instead I chose to test the config creation part that I added in isolation so no big refactoring was required.
Cheers

Implement config file creation from template during init command

---

cmd/config.go
cmd/merge.go
cmd/root.go

Fixes #224.
This PR adds a merge command that invokes `merge.command` to do a three-way merge between the destination state, the source state, and the target state.
`merge.command` defaults to `vimdiff`. You can set a different one in your config file, for example (in TOML):
```toml
[merge]
command = "gvimdiff"
args = ["-f"]
```
cc @markstos

Add merge command

---

cmd/vcsinfos.go

This addresses the Mercurial portion of #179.
- Adds support for `hg pull`, allowing `chezmoi update` to work on a
Mercurial repo.
- Updates the `hg` version regex to allow a 2-component version
My Mercurial install (Fedora package) has only two components to the
version number, which the version regex would not catch:
```
% hg --version
Mercurial Distributed SCM (version 4.9)
```
Verified new `hg pull` support by making and committing a change on
another checkout of the repo, seeing `go run main.go update`
successfully run, and see the updated content in the file changed.

Update mercurial support

---

docs/HOWTO.md

Current instructions result in this
```
eval $(op login <subdomain>.1password.com <email>)
-bash: unexpected EOF while looking for matching `''
-bash: syntax error: unexpected end of file
```
correct instruction below result in user being prompted for Secret Key:
`eval $(op signin <subdomain>.1password.com <email>)`

Fixed typo in 1Password instructions

---

cmd/apply_test.go
cmd/config.go
cmd/edit.go
cmd/root.go
docs/HOWTO.md
docs/REFERENCE.md
go.mod
go.sum
lib/chezmoi/boltpersistentstate.go
lib/chezmoi/boltpersistentstate_test.go
lib/chezmoi/chezmoi.go
lib/chezmoi/dir.go
lib/chezmoi/file.go
lib/chezmoi/script.go
lib/chezmoi/symlink.go
lib/chezmoi/targetstate.go
lib/chezmoi/targetstate_test.go

This PR is inspired by @schrej's work in #206 but takes a somewhat different approach:
* Scripts are stored in the source directory as files with the prefix `run_`, rather than using a separate directory.
* Scripts that should only be executed once are given the prefix `run_once_`, rather than scanning for a regexp in the script.
* Run state is persisted in a database stored next to the configuration file,
* In the code, scripts are treated as `Entry`s, and applied using the same interface, rather than having a separate set of commands and functions to handle them.

Add script support

---

cmd/vcsinfos.go

Support for these is incomplete, and it is unlikely that anyone is actually using them.

Remove CVS and Subversion support skeleton

---

go.mod
go.sum
lib/chezmoi/loggingmutator.go

This should fix building from source (#289) by not relying on `replace` directives in `go.mod` to rewrite import paths.

Go mod workarounds

---

docs/INSTALL.md

Thanks to #306, we don't need #305.

Update snap install instructions with beta channel

---

go.mod
go.sum

Thanks to @zb140, a step on the way to fixing #23.

Use latest go-vfs with Windows support

---

cmd/upgrade.go
go.mod
go.sum

Running `go get` on `chezmoi` is failing now because Google updated `go-github` and only v26 is referenced. This updates chezmoi to use v26.
Tested by running `./chezmoi upgrade --methd replace-executable`, which succeeded.

Update go-github to v26

---

.goreleaser.yaml

Fixes #347. This requires a modification to goreleaser before it can be merged.

Add bash completion in snap package

---

.golangci.yml
cmd/add_test.go
cmd/config.go
cmd/import.go
cmd/root.go
lib/chezmoi/private_posix.go
lib/chezmoi/private_windows.go
lib/chezmoi/targetstate.go

`IsPrivate` as implemented in #381 had a number of problems:
* It swallowed errors, which concealed a problem. `IsPrivate` assumed that the file being added existed, which is not the case when importing an archive directly in to the source directory with the `import` command.
* The result depended on `umask`, which is not correct. A file is private if it has no group or world permissions, independent of `umask`.

Fix IsPrivate

---

.golangci.yml
cmd/add_test.go
lib/chezmoi/private_windows.go

Fix Windows `IsPrivate` to check explicit permissions instead of effective permissions.  Effective permissions include values inherited from parent directories, which had the effect of making lots of things "private" that shouldn't have been.  Neither mode has exactly the same semantics as POSIX-style platforms, but explicit permissions should be a closer match to user intentions (ie, things are not private by default, and a user must take action to make them private).

Fix recursive add

---

cmd/apply_test.go
lib/chezmoi/targetstate.go

Fixes #382.
This is the fix for #382 written by @zb140, slightly tidied-up.
I'm also not familiar enough with the details of `text/template` to understand why this works. My guess that the sorcery used to add the partial templates was somehow changing the default template executed, and specifying an explicit template fixes this.
Thanks again @zb140!

Fix execution with partial templates

---

cmd/docs.go
cmd/docs_embeddocs.go
cmd/docs_noembeddocs.go
docs/CONTRIBUTING.md

@daurnimator this allows you to build chezmoi without embedded documentation, as requested in #427. See the changes to `CONTRIBUTING.md` in this PR for instructions on how to do this.
If this looks OK to you, I'll merge it and tag a new release with it so you can update the Arch Linux package.

Add nodocs and noembeddocs build tags

---

cmd/cd_posix.go
cmd/cd_windows.go
go.mod
go.sum

This PR improves the detection of the user's shell, which should allow the `chezmoi cd` command to work on a wider variety of platforms, including termux.
Refs #445.

Improve detection of the user's shell

---

cmd/config.go
cmd/init.go
docs/REFERENCE.md

cc @duckbrain refs #467.
This PR adds `sourceDir` to the default template variables.

Add sourceDir to default template data

---

go.mod
go.sum

This incorporates https://github.com/twpayne/go-shell/pull/5 which fixes building chezmoi on 32-bit operating systems.
cc @Ikke

Use go-shell with 32-bit support

---

cmd/helps.gen.go
docs/REFERENCE.md

Just a quick fix, `fish` shell completions files must end in `.fish`

Fixed a type in completion example

---

cmd/config.go
cmd/kernelinfo_linux.go
cmd/kernelinfo_linux_test.go
cmd/kernelinfo_notlinux.go
docs/REFERENCE.md

The main purpose of this is to have a way to detect WSL (windows subsystem for linux).
From what I can gather, the best way is currently to look in `/proc/sys/kernel/osrelease` and look for "microsoft" in the kernel name: https://github.com/microsoft/WSL/issues/423

Added kernel information to data

---

cmd/secretkeepassxc.go

Pass --show-protected to keepassxc-cli version 2.5.2 or later

---

.goreleaser.yaml

This reverts commit ed3584c00b85ef96b0314824c74c335f138a459b.
Thanks to https://github.com/goreleaser/goreleaser/pull/1346.

Re-enable bash completion in snaps

---

cmd/config.go
cmd/doctor.go
cmd/edit.go

Fixes #625.
@joeshaw I would be very happy to hear your input on this. This PR in its current form splits `$EDITOR` on whitespace to extract any extra arguments. Another possibility would be to pass `$EDITOR` unchanged to `/bin/sh -c '$EDITOR'`. Is there a more standard way of doing this?

Allow EDITOR and VISUAL to include arguments

---

docs/HOWTO.md

This is suggested fix for #637

Change . to dot_ in symlink template example

---

cmd/init.go
cmd/init_test.go

Windows uses `\r\n` for newlines, so when reading input it needs extra attention to avoid creating data with extra `\r` in the contents

Improve windows support by removing carriage return from prompts

---

cmd/add_test.go
internal/chezmoi/targetstate.go

This fixes a [problem reported](https://github.com/twpayne/chezmoi/issues/550#issuecomment-606699229) by @iopsthecloud in #550.
chezmoi uses empty files to indicate that the file should be removed in the target state, unless the file has the `empty_` attribute. When adding an empty file with `chezmoi add` without the `--empty` option (to add the `empty_` attribute) chezmoi removes the file from the source state. This would cause an error if the file did not already exist in the source state. This PR fixes that.

Fix behavior when adding an empty file without --empty

---

cmd/config.go
cmd/docs.gen.go
docs/REFERENCE.md
internal/chezmoi/gpg.go

There are cases where we want to be able configure the gpg CLI command.
For example I am user of the QubesOS and I use a separate VM for the gpg (split GPG). That's why I need to use the `gpg-client-wrapper` when working with the keys.
Ref.:
- https://github.com/QubesOS/qubes-app-linux-split-gpg

Add possibility to configure GPG cli command in config file

---

cmd/docs.gen.go
docs/FAQ.md
docs/HOWTO.md

@gotgenes encountered this behavior and found the issue on GitHub. I think it's worth surfacing it more clearly in the documentation.
Refs #463.

Document Viper's lowercasing of variable names

---

cmd/config.go
cmd/diff.go
cmd/docs.gen.go
cmd/helps.gen.go
completions/chezmoi-completion.bash
completions/chezmoi.zsh
docs/HOWTO.md
docs/REFERENCE.md

Fixes #673. cc @Gerrit-K.
This is isn't quite ready to merge yet, as it only uses the pager for `chezmoi diff`, not for `chezmoi -v`.
@Gerrit-K is this what you had in mind? Are you able to test this?

Add diff.pager config option

---

README.md
chezmoi.io/content/_index.md
cmd/docs.gen.go
docs/INSTALL.md

As someone who heavily relies on [Chocolatey ](https://chocolatey.org/) instead of Scoop for installing most software, I took the liberty to create a [package](https://chocolatey.org/packages/chezmoi) ([package source](https://github.com/rasmuskriest/Chocolatey-Packages/tree/master/chezmoi)) that updates automatically based on the GitHub releases.
This PR updates all documentation to include the Chocolatey package after/below Scoop.

Add Chocolatey to docs

---

cmd/docs.gen.go
cmd/secretonepassword.go
docs/REFERENCE.md

This fixes the part of #763 targeted at v1 and provides a significant performance boost when fetching items from 1password (if the vault is also specified).  Other perf improvements may come in later versions.

Allow specifying vault when fetching 1password secrets

---

cmd/secretkeepassxc.go
testdata/scripts/secretkeepassxc.txt

* Fix a bug that tried to read KeepassXC passwords from stdout rather than stdin (Fixes #768)
* Allow reading passwords from stdin even when it's not a terminal.
* Add an integration test for KeepassXC features

 Read KeepassXC passwords from stdin rather than stdout

---

cmd/docs.gen.go
cmd/templatefuncs.go
docs/REFERENCE.md

As [suggested by](https://github.com/twpayne/chezmoi/issues/787#issuecomment-646823638) @Legion2.
This adds a template function `include` that includes the contents of a file relative to the source directory.
Notes:
* The literal contents of the file are included, the file is not interpreted as a template.
* If you want to include a template, then you need to put the file in `.chezmoitemplates` and use the `template` function.
@Legion2 I'm not sure whether we should add this there are a number of downsides:
* The `include`d file has to be added to `.chezmoiignore` or start with a `.` to prevent chezmoi from creating a file in the target state of the same name.
* The `include`d file cannot be a template itself.
In short, `include` does not add anything that cannot already be achieved with …

Add include template function

---

cmd/docs.gen.go
cmd/templatefuncs.go
docs/REFERENCE.md

Fixes #774 and #798 by adding `stat` and `lookPath` template functions.
See the changes to `REFERENCE.md` in this PR for details of what these two new template functions do.
@rajaravivarma-r and @ritzmann, do these seem reasonable to you?

Add more template functions

---

go.mod
go.sum

This brings in @iAnomaly's patch from https://github.com/twpayne/go-shell/pull/7.

Prioritize $SHELL on Windows

---

Makefile

${PWD} is empty unless that environmental variable is set. Instead we
run `pwd` in a shell to get our current directory.
`make test` was failing for me due to gofumports missing (due to it
being installed in /bin instead of ./bin). This fixes that.
Error I got before: 
```
[...]
golangci/golangci-lint info installed ./bin/golangci-lint
./bin/golangci-lint run
if [ ! -x bin/gofumports ] ; then \
mkdir -p bin ; \
( cd $(mktemp -d) && go mod init tmp && GOBIN=/bin go get mvdan.cc/gofumpt/gofumports ) ; \
fi
go: creating new go.mod: module tmp
go: downloading mvdan.cc/gofumpt v0.0.0-20200802201014-ab5a8192947d
go: found mvdan.cc/gofumpt/gofumports in mvdan.cc/gofumpt v0.0.0-20200802201014-ab5a8192947d
go: downloading golang.org/x/tools v0.0.0-20200731060945-b5fad4ed8dd6
go: downloading …
```

Fix installation path of gofumports

---

cmd/secretpass.go
testdata/scripts/secretpass.txt

Hi,
This changes the unlock command for pass from `^$` to `$^`. `^$` matches empty lines, causing the unlock step to print some grep matches if empty lines occur in the pass secrets. `$^` on the other hand (end of line followed by beginning of line) should never match anything. 
Note that `$^` was what @m-rey suggested from the beginning in https://github.com/twpayne/chezmoi/issues/784. 
Both `make test` and `make lint` succeed without error. I do not have access to a windows box though so I am not sure if the test on windows is correct. Based on the comment it seems that only leading ^'s are dropped, so that we can match `grep $^`, but I have not been able to verify this (we'll see when the CI runs I guess).

Change pass unlock command

---

cmd/secretpass.go
testdata/scripts/secretpass.txt

Tested for a week on archlinux without any observed side effects.
Here's a gif showing that a password prompt is opened both in a desktop environment and in a terminal without x:
Saves quite a lot of time when `chezmoi apply`ing or `chezmoi diff`ing. 
I have not tested this on mac or windows.

Allow getting pass pw from pinentry instead of 'unlocking' pass

---

cmd/docs.gen.go
docs/HOWTO.md

Updated the documentation for detecting WSL according to https://github.com/Microsoft/WSL/issues/423#issuecomment-611086412. In WSL 2 the string `microsoft` is lowercase and in newer versions there is also `-WSL2` in the string to unambiguously identify it.

added example for detecting WSL 2

---

cmd/docs.gen.go
docs/HOWTO.md

Insignificant change in the documentation that caused me some time and reading the code to find the missing (s), which was in the previous line. Might save someone else the time.

Fixing onepasswordDetailsFields typo in the HOWTO docs

---

.github/workflows/main.yml
.gitignore
.goreleaser.yaml

Statically link Linux binary with musl

---

internal/chezmoi/chezmoi_windows.go

This commit (https://github.com/twpayne/chezmoi/commit/592a363977a83945308018a6b1748647403bed6c) inadvertently made it so that whenever `chezmoi` updates one of my files (on Windows), it's set to "read only".  So if I make some changes to a file, apply it, then make some more changes, the second apply will fail because it can't overwrite the read-only file.
Going back to using `0` for the umask on Windows fixes the issue, but I'm not sure if this change was intentional.  Let me know if you foresee any problems with this and I can look for a different solution.

Fix umask on Windows so new files are not created read-only by default.

---

cmd/docs.gen.go
cmd/secretonepassword.go
docs/REFERENCE.md

The new `--cache` option is provided on all platforms even though no actual caching is done on Windows (🤞 for the future). Also, the option is _not_ automatically added to commands run with `chezmoi secret onepassword` to keep it a pure pass-through.  If people need caching that way, they can simply specify the option themselves.

Opt in to data caching provided by newer versions of 1password-cli

---

docs/HOWTO.md

Should be _Windows Subsystem for Linux_ right? (https://docs.microsoft.com/en-us/windows/wsl/install-win10)
Btw, is small changes like this an okay?

Fix fullname for WSL

---

Makefile

When running `make lint`, it fails locally with the following message:
```
golangci/golangci-lint info checking GitHub for tag 'v1.33'
golangci/golangci-lint crit unable to find 'v1.33' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
```
This PR fixes this issue.

Fix GOLANGCI missing version patch

---

docs/TEMPLATING.md

One letter spelling fix I spotted while reading the docs -- `exectute-template` should be `execute-template`.

docs(TEMPLATING): trivial spelling fix

---

cmd/config.go

This prevents a nil pointer deref when there actually was an error looking up the group (which is nearly always the case on WIndows).  I expect that `group` wasn't actually getting added to `data` on non-Windows platforms either, which this should also fix.  I haven't actually verified this myself though.

Fix typo in error check

---

chezmoi2/cmd/config.go
chezmoi2/cmd/secretcmd.go
chezmoi2/cmd/secretkeyringcmd.go

Refs #987.
As [reported by](https://github.com/twpayne/chezmoi/issues/987#issuecomment-761884922) @zb140.
> Is the `chezmoi secret` subcommand permanently gone?
No :) I just didn't realize that it was actively used. This PR restores it for `secret keyring`. For other password managers, I think that the password manager's CLI should be a better option than using `chezmoi secret` but let's see what users report.
> I've been using it as part of my secret caching scheme to work around the perf issues in 1password. Specifically, I'm caching secrets in keepass and storing the keepass db password in the OS keyring (which gets unlocked when I sign into the computer). Then I use a shell alias to do `chezmoi secret keyring get --service secret_cache_pw --user zb | chezmoi apply` to apply dotfile …

chezmoi2: Restore secret keyring command

---

cmd/docs.gen.go
docs/REFERENCE.md

Docs incorrectly state that the pattern
backups/**
in a `.chezmoiignore` file would ignore `backups` and all its contents recursively; the pattern ignores all the contents of `backups` but not the directory itself. (As a consequence, `chezmoi add` would add `backups` with a `.keep` file in it, but not any of the files or folders in `backups` itself.)
This behavior comes from the `doublestar` library, which has [a test ensuring that `**` patterns work this way](https://github.com/bmatcuk/doublestar/blob/v1.3.4/doublestar_test.go#L87), so this is presumably the intended behavior.

docs(REFERENCE): clarify .chezmoiignore patterns

---

.github/workflows/main.yml

This PR will capture the binaries to artifacts so that every commit has an available downloadable build to test, allowing rapid testing of new features without needing a development environment.
Currently capturing both Chezmoi1 and Chezmoi2
https://github.com/twpayne/chezmoi/pull/1009/checks?check_run_id=1756221264#step:9:15

CI: Add artifact capture "nightlies" to Github Actions

---

assets/scripts/install.ps1
chezmoi2/cmd/docs.gen.go
cmd/docs.gen.go
docs/INSTALL.md

* Fix architecture detection
* Use built-in Expand-Archive to unzip packages.
Document some examples of how to run the install script
Fixes #1006

Fix the install.ps1 script to better support Powershell v5

---

.github/workflows/main.yml

Current snapshot artifacts fail with:
`chezmoi: source state requires version 0.0.0 or later, chezmoi is version 0.0.0-SNAPSHOT-3bc8688`
Removing -snapshot will generate normal versions.

Fix: State Version Check Fails with Artifacts

---

cmd/docs.gen.go
cmd/secretbitwarden.go
docs/REFERENCE.md
testdata/scripts/bitwarden.txt

This "mimics" `onepasswordDocument` for Bitwarden. I found an "issue" with Bitwarden while implementing this feature. Basically Bitwarden's file URL is build upon the `ID` + `itemid`, which makes anyone who exposes both `ids` to expose their files. 
Here is an example of the payload (with dummy values), pay attention to `id` and `id` in `attachments`, then the `url`:
```
[
...
{
"object": "item",
"id": "98ebec3b-3a9f-4220-9ae2-",
"organizationId": null,
"folderId": "C6BE41BF-A86F-455D-B9EB-E36F6E2D37E2",
"type": 2,
"name": ".ssh/id_rsa.pub",
"notes": null,
"favorite": false,
"secureNote": {
"type": 0
},
"collectionIds": [],
"attachments": [
{
"id": "arandom-id",
"fileName": "id_rsa.pub",
"size": "625",
"sizeName": "625 Bytes",
"url": …
```

Add BitwardenAttachment template support

---

cmd/keyringtemplatefuncs.go

- Initialize the keyring cache to prevent errors when using keyring template functions.

Initialize the `keyring` cache

---

cmd/config.go
docs/CHANGES.md

The `.chezmoi.homedir` template variable has been replaced with `chezmoi.homeDir` for consistency, but let's keep the old template variable around for a version to help people transition to v2.

Preserve homedir template variable until v2.1

---

docs/HOWTO.md

Just a simple update to the howto docs to reference main as the branch rather than master since github and git are changing the default. This also aligns with your quickstart

Update howto to use main instead of master

---

assets/scripts/install.ps1

If using the install.ps1 script to update an existing installation it will fail with an error like this:
"An error occurred while installing: Cannot create a file when that file already exists."
Adding -Force to the script makes the script replace the existing chezmoi.exe.

Make PowerShell install script replace previous chezmoi.exe if script is used to update previous installation.

---

internal/chezmoi/realsystem.go
testdata/scripts/scriptsubdir_unix.txt
testdata/scripts/scriptsubdir_windows.txt

This allows putting `before_` scripts in subdirectories, which naturally won't exist during the `before` phase.
Fixes #1097.

Use the first existing parent directory for a script's working directory

---

internal/chezmoi/gpgencryption.go

Current behavior if set encrypt with gpg symmetric (log by --debug flag)
```
2021-04-01T11:41:15+08:00 DBG Stat name=.../.config/chezmoi/chezmoistate.boltdb
2021-04-01T11:41:15+08:00 DBG Mkdir error="mkdir .../.local/share/chezmoi: file exists" name=.../.local/share/chezmoi perm=511
2021-04-01T11:41:15+08:00 DBG Stat name=.../.local/share/chezmoi
2021-04-01T11:41:15+08:00 DBG Lstat name=.../.local/share/chezmoi
2021-04-01T11:41:15+08:00 DBG ReadFile data="..." filename=.../.profile
You did not specify a user ID. (you may use "-r")
Current recipients:
Enter the user ID.  End with an empty line: 
gpg: no valid addressees
gpg: [stdin]: encryption failed: No user ID
2021-04-01T11:41:37+08:00 ERR Output error="exit status 2" args=["gpg","--armor","--encrypt","--symmetric"] exitCode=2 output= …
```

fix: gpg symmetric passing wrong arguments

---

assets/scripts/install.ps1

Fixed checksums.txt filename to match the new naming in sh script.
Current version fails with 404 error when trying to download checksums file as the name changed for release 2.0.7.

Update PowerShell install script to use checksums.txt

---

docs/HOWTO.md

I'm new to Go's templates, but based on [the docs](https://golang.org/pkg/text/template/#hdr-Functions), it looks like there were two erroneous `)` in the example here.

Correct `and` template example in How To guide

---

assets/scripts/install.ps1
docs/INSTALL.md

This PR fixes couple of issues that I've encountered while installing `chezmoi` on Windows 10 with non `en-US` locale.
First, `.OSArchitecture` returns localized value and even changing `CurrentCulture` doesn't help.
```
PS C:\Users\username> (iwr -UseBasicParsing https://git.io/chezmoi.ps1).Content | powershell -c -
WARNING: PowerShell requires an execution policy in [Unrestricted, RemoteSigned, Bypass] to run this install script.
WARNING: For example, to set the execution policy to 'RemoteSigned' please run :
WARNING: 'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'
Unsupported architecture:  (wmi: 64-разрядная)
An error occurred while installing: unsupported architecture
```
```
PS C:\Users\username\Downloads> (Get-WmiObject -Class Win32_OperatingSystem | Select-Object …
```

Improve reliability of Powershell installer

---

.goreleaser.yaml

Looking at the source for zsh[1], it appears that the default directory for
extra functions like completions is `../site-functions` not `../functions`. This
matches the behavior on Fedora.
[1] https://github.com/zsh-users/zsh/blob/c1f932d66896753eb118003b7c1b1139bc6c8725/configure.ac#L308

Update rpm zsh completion directory to match recent Fedora versions.

---

internal/chezmoi/gpgencryption.go

Refs #1074.
@3v1n0 would you be able to test if this PR fixes the problems you reported in #1074?
It changes the way that chezmoi reads and writes data from gpg back to how it was done prior to chezmoi v2, i.e it reverts back to using temporary files rather than gpg's standard input and output.

Use temporary files, instead of stdin/stdout, when calling gpg

---

docs/CONTRIBUTING.md

`golangci-lint` link was broken by an early newline/new list item

Fix a minor typo in CONTRIBUTING.md

---

docs/HOWTO.md

remove any whitespace before and after→
remove and

Fix a minor typo in HOWTO.md

---

docs/REFERENCE.md
go.mod
go.sum
internal/cmd/config.go
internal/cmd/templatefuncs.go
internal/cmd/testdata/scripts/templatefuncs.txt

Add mozillaInstallHash template function

---

internal/chezmoi/entrystate.go
internal/chezmoi/sourcestate.go
internal/chezmoi/targetstateentry.go
internal/cmd/config.go
internal/cmd/testdata/scripts/modify_unix.txt

As [identified by @lcrockett](https://github.com/twpayne/chezmoi/issues/1046#issuecomment-864343405) in #1046.
Before this change, chezmoi would always warn if the target of a modify script had changed since chezmoi last wrote it, but this is counter to the concept of a modify script: we expect the target of modify scripts to have changed since chezmoi last wrote it.
This PR changes the behavior of chezmoi to always overwrite the target of modify scripts, even if `--force` is not specified.
@lcrockett would you be able to test this? No worries if not :)

Make modify scripts always overwrite the target without prompting

---

assets/scripts/install.ps1

Currently, if, ie, the currently running context has called:
```
Set-StrictMode -version latest
```
...then `install.ps1` will error when, ie,
`[Runtime.InteropServices.RuntimeInformation]::OSArchitecture`
in `get_goarch` is fetched from .NET 4.0.
This change won't affect the calling context.

Allow install of chezmoi from a powershell where StrictMode is on

---

docs/COMPARISON.md

- Normalize cell length in Markdown table
- Set the record straight on some bare-git features
- Add VCSH to comparison chart

Fix bare-git and add VCSH to comparison chart

---

docs/COMPARISON.md

Thanks for merging #1314. Unfortunately it seems I made a mistake while revising commits that left two incorrect values that I intended to fix.
I actually fixed this in dde40d0 and included in in the commit message, then I botched some rebase work where I was trying to same formatting cleanup separately from content changes and obliterated the fix.

Fix commit editing snafu in feature chart

---

internal/cmd/editcmd.go
internal/cmd/testdata/scripts/gpgencryption.txt

Strip encrypted suffix when editing transparently decrypted files

---

docs/INSTALL.md

The "ports" method of software installation
on FreeBSD is `make -C /usr/ports/sysutils/chezmoi install`.
It's better to call the method described in the documentation as
"pkg".

Fix the FreeBSD installation method

---

README.md

The previous link (https://gitlab.com/search?search=chezmoi) for some
reason only turns up one result (at least for me).  The new link
(https://gitlab.com/explore/projects?topic=chezmoi) instead searches
for repositories that are tagged "chezmoi", which finds six gitlab
repositories for me.

Change gitlab link for other people's dotfiles

---

docs/HOWTO.md

Paths of files managed by chezmoi can contain spaces, such as configuration files in `~/Library/Application Support` on MacOS. The current Vim integration command would fail as spaces in the path where not escaped. The usage of quotation marks should avoid this problem.

Support paths containing spaces in VIM integration

---

internal/cmd/testdata/scripts/externalguess.txt

chore: Skip test requiring zip if zip is not in installed

---

docs/HOWTO.md

The "different files locations on different systems" guide didn't pass data to the template file, which can result in errors. See https://github.com/twpayne/chezmoi/issues/1108 for an example of this problem.

docs: fix error in HOWTO guide

---

docs/REFERENCE.md
internal/cmd/config.go
internal/cmd/initcmd.go
internal/cmd/inittemplatefuncs.go
internal/cmd/testdata/scripts/update.txt
internal/cmd/updatecmd.go

feat: Add --init option to update command

---

internal/chezmoi/data_test.go
internal/cmd/doctorcmd.go

Specifically, this applies to Arch Linux.

chore: Show OS release name in doctor command even if version is not present

---

internal/cmd/upgradecmd.go

fix: Fix upgrade command on non-amd64 Linux machines

---

docs/FAQ.md
docs/REFERENCE.md
internal/chezmoi/debugsystem.go
internal/chezmoi/dryrunsystem.go
internal/chezmoi/externaldiffsystem.go
internal/chezmoi/gitdiffsystem.go
internal/chezmoi/realsystem.go
internal/chezmoi/system.go
internal/cmd/cmd.go
internal/cmd/config.go
internal/cmd/editcmd.go
internal/cmd/mergecmd.go
internal/cmd/upgradecmd.go

This PR makes `chezmoi edit $TARGET` invoke your editor with an unmangled filename matching `$TARGET` exactly, independent of chezmoi's file name mangling.
For example, say you have a `private_dot_bashrc` in your source state. When you run `chezmoi edit ~/.bashrc` then your editor will be opened with a file with the basename `.bashrc`, so all of your editor's syntax highlighting should work.
Under the hood it creates a hard link from a file in a temporary directory (e.g.`$TMPDIR/.bashrc`) to the actual file in your source directory (e.g. `~/.local/share/chezmoi/private_dot_bashrc`) so your editor thinks it's actually editing `$HOME/.bashrc`.
After you quit your editor the directory with the hard links is cleaned up.
Refs #752 #769
cc @alker0 @m-rey @thernstig
This is an experimental …

feat: Make editors see target filenames

---

.goreleaser.yaml
docs/REFERENCE.md
internal/cmd/config.go
internal/cmd/testdata/scripts/templatevars.txt

Fixes #1532.
`.chezmoi.executable` is the requested `.chezmoi.binPath`.
`.chezmoi.args` combine the requested `.chezmoi.command` and `.chezmoi.options`.
I really don't think that this is a good idea, but here's a PR for you to experiment with :)

feat: Add .chezmoi.args template variable

---

docs/TEMPLATING.md

docs: Fix link to list of template functions

---

internal/cmd/templatefuncs.go
internal/cmd/testdata/scripts/templatefuncs.txt

When it should just return an empty string, specifically when looking for an absolute path.
Fixes #1606

fix: `lookPath` panics when file does not exists

---

internal/cmd/doctorcmd.go
internal/cmd/testdata/scripts/doctor_unix.txt

fix: Warn, don't fail, if age version cannot be parsed in doctor command

---

internal/cmd/doctorcmd.go
internal/cmd/noupgradecmd.go
internal/cmd/upgradecmd.go

Fixes #1609.
Fixes #314.
@felipecrs as discussed yesterday, this is a little tricky to test. You can, however, do:
1. Install chemzoi 2.7.4 with Homebrew on Linux as you described in #1609.
2. Build chezmoi with these changes and replace the `which chezmoi` with the newly-built binary (`/home/linuxbrew/.linuxbrew/bin/chezmoi` on my test system, `/home/felipecrs/.linuxbrew/bin/chezmoi` on yours).
3. Run `chezmoi upgrade --debug --force`, and it should install chezmoi 2.7.5 using `brew update chezmoi`. The `--force` is needed as the new binary will have version `dev` and so won't upgrade itself unless forced.

feat: Add support for Homebrew on Linux to upgrade command

---

.devcontainer/devcontainer.json
docs/REFERENCE.md
internal/cmd/config.go
internal/cmd/testdata/scripts/templatevars.txt

So, it turns out that `.chezmoi.args[0]` is not the path for the chezmoi binary as I thought. It was during my test because I was indeed calling the chezmoi by providing the full path to its executable.
Refs https://github.com/twpayne/chezmoi/pull/1534

feat: Add .chezmoi.executable template variable

---

.goreleaser.yaml

Fixes #1576.
This should only be merged when the next version of goreleaser is released, which will include https://github.com/goreleaser/goreleaser/pull/2620.
cc @torculus this will affect the [OpenIndiana package](https://github.com/OpenIndiana/oi-userland/tree/oi/hipster/components/sysutils/chezmoi) for chezmoi once this merged (2.7.4 and previous versions are not affected). Specifically, instead of the source tarball unpacking the source code into the current directory, the source tarball will unpack into a `chezmoi-$VERSION/` subdirectory.

chore: Use conventional subdirectory for source archives

---

internal/chezmoi/chezmoi.go
internal/chezmoi/sourcestate.go
internal/cmd/testdata/scripts/remove.txt

fix: .chezmoiremove with `*` when destDir is `/`

---

docs/REFERENCE.md
internal/cmd/config.go

I have two use cases for this one:
`run_before_migrate.sh.tmpl`:
```
#!/bin/bash
{{ if hasSuffix .chezmoi.configFile ".toml" -}}
rm -f "{{ .chezmoi.configFile }}"
echo "We need to update the config file format, please run the following command:"
echo "chezmoi init --source '{{ .chezmoi.sourceDir }}'"
{{- end -}}
```
And:
`home/dot_local/bin/executable_rootmoi.tmpl`:
```
#!/bin/bash
readonly config_dir="{{ dir .chezmoi.configFile }}"
readonly config="${config_dir}/root.config.json"
readonly persistent_state="${config_dir}/root.chezmoistate.boltdb"
exec sudo "{{ .chezmoi.executable }}" \
--config="${config}" \
--persistent-state="${persistent_state}" \
"$@"
```

feat: Add .chezmoi.configFile template variable

---

docs/HOWTO.md

The HOWTO document says to use "chezmoi delete-bucket" to clear
the state of the `run_once_` scripts, but when I try that I
get this error:
chezmoi: unknown command "delete-bucket" for "chezmoi"
This commit updates the documentation to use
"chezmoi state delete-bucket" instead,
which I believe is the intended command.

Fix delete-bucket command in HOWTO doc

---

internal/chezmoi/sourcestate.go
internal/cmd/executetemplatecmd.go

This speeds up `chezmoi execute-template` by only reading control data, not the full source state.
Refs #1715.

chore: Don't read full source state in execute-template

---

docs/TEMPLATING.md

Website generation seems to rely on absolute links to git repository.
(As seen line 325 right above the change)
PS: hugo seems to be broken though. Maybe this is the reason the relative link does not work :shrug:
```
❯ ( cd assets/chezmoi.io/ && hugo serve )
Start building sites … 
hugo v0.89.3+extended linux/amd64 BuildDate=unknown
ERROR 2021/12/10 12:25:05 [en] REF_NOT_FOUND: Ref "/docs/install.md": "/home/syphdias/git/private/chezmoi/assets/chezmoi.io/content/docs/menu/index.md:5:13": page not found
ERROR 2021/12/10 12:25:05 [en] REF_NOT_FOUND: Ref "/docs/quick-start.md": "/home/syphdias/git/private/chezmoi/assets/chezmoi.io/content/docs/menu/index.md:6:17": page not found
ERROR 2021/12/10 12:25:05 [en] REF_NOT_FOUND: Ref "/docs/how-to.md": …
```

Fix link on chezmoi.io from templating to reference

---

docs/REFERENCE.md

Running the examples using the short-hand `-i` flag listed in the output of `chezmoi managed --help` results in errors:
```
$ chezmoi managed -i d
chezmoi: invalid argument "d" for "-i, --include" flag: d: unknown entry type
$ chezmoi managed -i d,f
chezmoi: invalid argument "d,f" for "-i, --include" flag: d: unknown entry type
```
If this behaviour is actually a regression and thus a bug I can also look into how to fix it.

Fix managed command example docs

---

.github/ISSUE_TEMPLATE/03_bug_report.md

It just looks better when the extra details are not visible by default:
- https://github.com/twpayne/chezmoi/issues/1780

Add collapsible details to bug report template

---

docs/HOWTO.md
docs/REFERENCE.md
internal/cmd/config.go
internal/cmd/onepasswordtemplatefuncs.go
internal/cmd/testdata/scripts/onepassword.txt

Currently when a user tries to run `chezmoi` against a repo which uses the 1Passoword template functions, it will work correctly with a session token already exported within the environment, but fail if e.g. the session is expired.
With this change, chezmoi will use the `op signin` function to verify the validity of current session and interactively prompt for master password if that fails. This prevents the user from having to repeatedly sign in and export their session manually.
Before:
```
$ chezmoi diff
chezmoi: template: xxx.sh.tmpl:5:30: executing "xxx.sh.tmpl" at <onepassword "xxx">: error calling onepassword: op get item xxx: exit status 1: [ERROR] 2021/12/26 01:28:33 You are not currently signed in. Please run `op signin --help` for instructions
```
After (in an interactive …

onepassword: prompt to sign-in if the current session is missing or expired

---

docs/HOWTO.md

Small improvement in the docs.

docs: personal access token not needed with `--ssh`

---

assets/chezmoi.io/docs/user-guide/manage-machine-to-machine-differences.md

Fix small typo in the docs example under User Guide -> Manage machine-to-machine differences where the code snippet did not match the filename in the example.

docs: Fix small typo in User guide

---

quick-start/index.html

The link to the user manual at the end of the “Quick start” page is broken. This is a fix, making it point to the user guide.

Update gh-pages: fix broken link to user manual

---

.github/workflows/main.yml
.golangci.yml
pkg/cmd/util_unix.go

Draft PR, not ready for merge yet.
Refs https://github.com/breml/errchkjson/issues/5.

chore: Prepare for next release of golangci-lint

---

pkg/cmd/bitwardentemplatefuncs.go
pkg/cmd/errors.go
pkg/cmd/gopasstemplatefuncs.go
pkg/cmd/keepassxctemplatefuncs.go
pkg/cmd/passtemplatefuncs.go
pkg/cmd/secrettemplatefuncs.go
pkg/cmd/templatefuncs.go
pkg/cmd/testdata/scripts/templatefuncs.txt
pkg/cmd/vaulttemplatefuncs.go

This needs to be applied to 1Password too, but #1861 should probably land first.

chore: Factor out common exec errors

---

assets/chezmoi.io/docs/reference/templates/functions/onepassword.md
assets/chezmoi.io/docs/reference/templates/functions/onepasswordDetailsFields.md
assets/chezmoi.io/docs/reference/templates/functions/onepasswordItemFields.md
assets/chezmoi.io/docs/user-guide/password-managers/1password.md
pkg/chezmoi/nullsystem.go
pkg/chezmoi/nullsystem_test.go
pkg/cmd/doctorcmd.go
pkg/cmd/onepasswordtemplatefuncs.go
pkg/cmd/onepasswordtemplatefuncs_test.go
pkg/cmd/testdata/scripts/onepassword2.txt
pkg/cmd/testsystem_test.go

Fixes #1860.
Closes #1828.
cc @cadenkriese
This builds on @kdomanski's work in #1828 (commit is co-authored by @kdomanski) to take into account the refactoring of template functions in #1859 and further refactoring.
At this instant, I believe the code is correct, but there's a bug in the tests that get confused by existing `OP_SESSION_` environment variables, and I'm most of the way through fixing it.
This, [raised by @kdomanski](https://github.com/twpayne/chezmoi/pull/1828#issue-1106185987), still needs to be addressed:
> With the changed API structure IMO I'd reconsider whether having both `onepasswordDetailsFields` and `onepasswordItemFields` with different behavior makes sense. As far as I can tell, all fields are now returned in one array, but some have a Section field and some …

feat: Support 1Password CLI 2.0

---

assets/chezmoi.io/docs/reference/commands/import.md
assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md
go.mod
go.sum
pkg/chezmoi/archive.go
pkg/cmd/testdata/scripts/importxz.txt

This change adds support for `XZ` archives.
Notes:
* adds new dependency `github.com/ulikunitz/xz` (Pure golang package for reading and writing xz-compressed files)
* new archive format comes before `zip` because I sorted list after adding this new one
* only two small documentation changes (could not find any other notable place)
* one new test was added; uses `tar` and requires `xz-utils` (or comparable package); run with `go test -v -run TestScript/importxz ./...`
* the `make test-release` run was done in `golang:1.17.7-bullseye` container
closes #1883

Add support for xz archives

---

assets/scripts/install.sh
internal/cmds/generate-install.sh/install.sh.tmpl

Not set in stone, but was hoping to start the conversation with a little code. I would prefer to maintain my own fork of chezmoi and this would still allow me to use a single-line installer (obviously with my own url).
A couple things I noticed:
1. I was not sure how to accomplish this same edit in the PowerShell variant.
2. Similar to the BINDIR, maybe you want the GITHUB_USER to additionally be set via switch?
Not a life-or-death change, but does abstract the code a bit from your namespace.

Allow overriding GitHub user in shell installer

---

assets/chezmoi.io/docs/reference/commands/secret.md
assets/chezmoi.io/docs/reference/templates/functions/keyring.md
go.mod
go.sum
pkg/cmd/keyringtemplatefuncs.go
pkg/cmd/keyringtemplatefuncs_freebsdnocgo.go
pkg/cmd/secretcmd.go
pkg/cmd/secretkeyringcmd.go
pkg/cmd/secretkeyringcmd_freebsdnocgo.go

Fixes #1918.
@torculus if you [build chezmoi from source](https://www.chezmoi.io/install/#install-from-source) from this PR you should get GNOME Keyring support on FreeBSD. I'll wait for the official tag of zalando/go-keyring before merging this.

feat: Add support for GNOME Keyring on FreeBSD

---

pkg/cmd/config.go

The `hostname` variable was not being cut off at the first `.` character,
as intended. This is because a previous revision of the code accidentally
changed the separator character to `=` instead of `.`
This change returns the behaviour of the `hostname` variable to match
its documentation.
Opening this as a draft while I work out how to add a test for this behaviour
(not a Go developer sorry, so need to find an appropriate existing test
to use as a template). I've checked that the existing tests pass. 
Fixes #1920

Correctly cut hostname off at . character

---

assets/scripts/install.sh
internal/cmds/generate-install.sh/install.sh.tmpl

Fixes #1924 by no longer using the $GITHUB_USER environment variable.
cc @kyounger as the person likely to be affected by this change.

fix: Allow user and repo to set in install script

---

pkg/chezmoi/abspath.go
pkg/chezmoi/path_windows_test.go

Fixes #1964.
@zb140 would you mind reviewing this?
From [your comment](https://github.com/twpayne/chezmoi/issues/1964#issuecomment-1086414230):
> It may also be possible to fix it by also applying the "sometimes add a slash" logic in `TrimDirPrefix` but a) I haven't tried it, and b) I'm not as big a fan of that solution on a philosophical level because I think it's buggy behavior on Go's part to not include the slash in the first place. `H:` by itself is just a volume specifier, not a directory, so I don't think it's really a proper return value for `path.Dir()`. But reasonable minds can differ, and I'm happy to be told I'm wrong about that.
I've actually taken this approach in this PR. I agree with your assessment that it's buggy behavior from Go to not include the slash in the first …

fix: Fix use of drives as home directories on Windows

---

assets/chezmoi.io/docs/reference/templates/variables.md

Hi, 
I'm new to chezmoi and started to look into templates. I've spent quite some time to figure out why I could not get custom variables in the `data` section of the config to work until I realized that I've stumbled upon #463.
I propose to add a hint or disclaimer to the documentation here to make it easier for newcomers to spot this pitfall (and avoid it). The  FAQ added in  #671 contains a reference already, but I only found it by backtracking from the issue.
Maybe adding the hint (also) to [User Guide > Templating](https://www.chezmoi.io/user-guide/templating/) would also help?
Please let me know if I need to change or update anything.

docs: Add clarification about all lowercase custom data fields

---

assets/chezmoi.io/docs/user-guide/password-managers/1password.md

This PR fixes an example in the documentation.
```
chezmoi execute-template "{{ (onepassword \"$UUID\").fields[1].value }}"
```
yields the following error
```
chezmoi: template: stdin:1: bad character U+005B '['
```

Use index function to access an item in the example

---

pkg/chezmoi/lookpath.go

The contents of the directories in `$PATH` might change between calls to `LookPath`, see https://github.com/twpayne/chezmoi/issues/2027.
Fixes #2027.

fix: Don't cache negative results of path lookups

---

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md
pkg/chezmoi/sourcestate.go
pkg/cmd/testdata/scripts/externalarchiveinclude.txt

Fixes #2056
Also updates the documentation and adds a test which checks the new
behaviour.
archive centent:
```
bsl-develop/LICENSE
bsl-develop/Makefile
bsl-develop/README.org
bsl-develop/src/
bsl-develop/src/bsl_logging.bash
bsl-develop/src/bsl_misc.bash
bsl-develop/src/bsl_path.bash
bsl-develop/src/bsl_string.bash
bsl-develop/src/load.bash
bsl-develop/test/
bsl-develop/test/bsl_logging.bats
bsl-develop/test/bsl_misc.bats
bsl-develop/test/bsl_path.bats
bsl-develop/test/bsl_string.bats
bsl-develop/test/test_helper.bash
```
.chezmoiexternal.yaml:
```yaml
---
.local/lib/bash/bsl:
type: 'archive'
url: 'https://github.com/ktetzlaff/bsl/archive/develop.tar.gz'
include:
- '**/src/*.bash'
stripComponents: 2
```
Extract `*.bash` from `bsl-develop/src/` to `~/.local/lib/bash/bsl`.
Nothing will be …

fix #2056: extract files from sub-directory of external archive with include but w/o excludes

---

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md
assets/chezmoi.io/docs/user-guide/include-files-from-elsewhere.md
pkg/chezmoi/sourcestate.go

This is an add on to the previous fix for #2056 which adds an example of
how to use `input` filters in `.chezmoiexternal.toml` to the
user guide (`docs/user-guide/include-files-from-elsewhere.md`).
The first commit also includes an update to
`docs/reference/special-files-and-directories/chezmoiexternal-format.md`
which uses the new simplified `input` filter syntax and makes a minor
change to the comment about excluded directory trees in
`pkg/chezmoi/sourcestate.go`.
A second commit adds a link from the `chezmoiexternal` related page in the *user-guide* to the corresponding page in the *reference* docs (and vice versa).
~~I haven't checked the HTML output of the markdown changes (I couldn't figure out how to build it). Is there a way to look at the output of the `build-website` job of the …

docs: Add example of extracting selected files from external archive

---

assets/chezmoi.io/docs/links/related-software.md
assets/chezmoi.io/docs/user-guide/manage-different-types-of-file.md

Add a hint in the section on `modify` as well as in related software.
Also in a separate commit I organized related software page into sub-sections. So far I only added a separate section for Editor integration. In the future, as there is more software it may also make sense to split "Other" into further sections.

docs: chezmoi_modify_manager

---

assets/chezmoi.io/docs/user-guide/manage-different-types-of-file.md

When describing managing a file's permissions without managing the contents itself, and uses kubeconfig as an example, the docs note to create a file `dot_kube/private_dot_config` in the source directory, when based on the chezmoi source naming scheme, it should be `dot_kube/private_config`. This changes that disparity.
Signed-off by: Kendall Tauser <kttpsy@gmail.com>

Fixed typo in kubeconfig documentation

---

pkg/cmd/dumpcmd.go
pkg/cmd/testdata/scripts/issue2092.txt

Refs #2092.
@VorpalBlade I'm reasonably sure that this fixes the problem you reported. Are you able to test this to confirm?

fix: Fix dump command in the presence of config file templates

---

assets/scripts/install.sh
assets/scripts/stow-to-chezmoi.sh
internal/cmds/generate-install.sh/install.sh.tmpl

Hello, I've made some improvements to `install.sh` and `stow-to-chezmoi.sh`. I've made sure to update `install.sh.tmpl` and committed the output of generating that.
General improvements:
* Use `${N}` syntax for all parameter expansions.
* Supply `--` to commands whose positional arguments are based on environment variables, output of system utilities, or user input. This protects against an argument being interpreted as an option by a command.
* Avoid use of `echo` which behaves inconsistently between shells and platforms.
* Clean up temporary files when interrupted by `SIGINT` or `SIGTERM`.
`install.sh` improvements:
* Quote all variable assignments that involve parameter expansion or command substitution to protect them from pathname expansion and quote removal.
* Quote parameter …

fix: Improve quality of POSIX shell scripts

---

assets/chezmoi.io/docs/user-guide/machines/general.md

- WMI cmdlets have been [deprecated in favor of CIM](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/07-working-with-wmi?view=powershell-7.2) for some time now:
> The WMI cmdlets are deprecated so my recommendation is to use the CIM cmdlets instead of the older WMI ones.
- In PowerShell, `echo` is an alias for `Write-Output`, but it's possible to reassign the alias to something else, so it's better to be explicit.
- `trim` is required to remove the dangling CRLF line ending. Without this, the result is:
```toml
[data]
chassistype = "desktop\r\n" # or chassistype = "laptop\r\n"
```

docs: Refactor Windows chassisType template

---

pkg/chezmoi/abspath.go
pkg/chezmoi/errors.go
pkg/cmd/config.go
pkg/cmd/testdata/scripts/cat.txt

chore: Give a more explicit error when target is not in dest dir

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md
pkg/chezmoi/gpgencryption.go

Fixes #2139.
@craSH This adds a `gpg.recipients` configuration variable that should fix #2139. Are you able to test this?

feat: Support multiple GPG recipients

---

assets/chezmoi.io/docs/reference/commands/add.md
pkg/chezmoi/sourcestate.go
pkg/chezmoi/sourcestate_test.go
pkg/cmd/addcmd.go
pkg/cmd/addcmd_test.go
pkg/cmd/readdcmd.go
pkg/cmd/testdata/scripts/add.txt

feat: Make add command add empty files, remove --empty flag

---

pkg/cmd/testdata/scripts/archivezip.txt
pkg/cmd/testdata/scripts/externalzip.txt

Fixes #2169.
Fixes #2171.
Closes #2170.

chore: Skip zip tests on Windows

---

assets/chezmoi.io/.gitignore

This should prevent common `virtualenv` directory names (`{.}v{irtual}env`) from showing under `git status` etc. when working on website changes.

chore: Ignore virtualenv in website directory

---

assets/chezmoi.io/docs/user-guide/encryption/gpg.md

gpg sends some info messages to stderr instead of stdout. This commit
adds documentation on how to mute this output.
Closes #2192

add documentation for muting gpg output

---

assets/chezmoi.io/docs/index.md

This seems to be a bit more secure, and avoids a redirect to https:
```
❯ curl -v -fsLS chezmoi.io/get | head
*   Trying 185.199.110.153:80...
* Connected to chezmoi.io (185.199.110.153) port 80 (#0)
> GET /get HTTP/1.1
> Host: chezmoi.io
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: GitHub.com
< Content-Type: text/html
< Location: https://www.chezmoi.io/get
< X-GitHub-Request-Id: A05C:484F:C695C6:D56E92:62C6EB4B
< Content-Length: 162
< Accept-Ranges: bytes
< Date: Thu, 07 Jul 2022 14:18:56 GMT
< Via: 1.1 varnish
< Age: 5
< Connection: keep-alive
< X-Served-By: cache-lcy19224-LCY
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Timer: S1657203537.680928,VS0,VE1
< Vary: Accept-Encoding
< X-Fastly-Request-ID: …
```

Add `https://` to the `curl` install command

---

assets/chezmoi.io/docs/reference/commands/managed.md
assets/chezmoi.io/docs/reference/commands/unmanaged.md
pkg/cmd/managedcmd.go
pkg/cmd/testdata/scripts/managed.txt
pkg/cmd/testdata/scripts/unmanaged.txt
pkg/cmd/unmanagedcmd.go

Fixes twpayne/chezmoi#1985.
Allow arguments on chezmoi managed and unmanaged.  Per recommendations on twpayne/chezmoi#1985, no additional flags are added to either commands, and behaviors are very similar to the respective commands without arguments (such as not recursing into directories).
``` console
$ chezmoi unmanaged ~/.ssh ~/.gnupg
(list unmanaged files under the arguments)
$ chezmoi managed ~/.config/git ~/scripts
(list managed files under the arguments)
```
Note that in consideration of duplicated arguments and outputs, sorting and deduplication is done on both the arguments and the outputs for unmanaged, and on the outputs for managed.  This helps with the following hypothetical situation (exaggerated to hopefully convey the idea more clearly):
``` console
$ chezmoi unmanaged …
```

Add arguments to "chezmoi unmanaged" and "chezmoi managed"

---

assets/chezmoi.io/docs/user-guide/encryption/gpg.md

Fixes #2250
Fix typo in Gpg example

chore: Fix typo in Gpg example

---

assets/chezmoi.io/docs/reference/commands/diff.md
pkg/chezmoi/externaldiffsystem.go
pkg/cmd/config.go
pkg/cmd/testdata/scripts/diffcommand_unix.txt
pkg/cmd/testdata/scripts/externaldiff.txt

Fixes #2115.
- Show scripts
- Show directory creation
- Support diff.include and diff.exclude
- Pass `/dev/null` instead of filename when file does not exist
cc @latipun7

feat: Improve support for external diff commands

---

pkg/cmd/initcmd.go

fix: Detect SSH clones from URL when using builtin git

---

assets/chezmoi.io/docs/extra/refresh_on_toggle_dark_light.js
assets/chezmoi.io/mkdocs.yml

Mermaid diagrams in the documentation are currently hardly visible in dark mode.
It is because they are not switched on the fly between light and dark mode and hence they are displayed using light mode colors in both mode.
This PR fixes that issue, thanks to descriptions and instructions in [mkdocs-mermaid2-plugin's README](https://github.com/fralau/mkdocs-mermaid2-plugin/blob/master/README.md#material-theme-switching-the-mermaid-diagram-on-the-fly-between-light-and-dark-mode).

docs: Fix a coloring issue that lines and texts in Mermaid diagrams are hardly visible in dark mode

---

pkg/cmd/templatefuncs.go
pkg/cmd/templatefuncs_test.go
pkg/cmd/testdata/scripts/templatefuncs.txtar

fix: Only use quotes if necessary in toIni template function

---

pkg/chezmoi/entrytypeset.go
pkg/cmd/testdata/scripts/externalgitrepo.txtar

fix: Treat git-repo externals as directories of include/exclude purposes

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/chezmoi.io/docs/reference/templates/passhole-functions/index.md
assets/chezmoi.io/docs/reference/templates/passhole-functions/passhole.md
assets/chezmoi.io/docs/user-guide/password-managers/custom.md
assets/chezmoi.io/docs/user-guide/password-managers/passhole.md
assets/chezmoi.io/docs/what-does-chezmoi-do.md
assets/chezmoi.io/mkdocs.yml
pkg/cmd/config.go
pkg/cmd/doctorcmd.go
pkg/cmd/passholetemplatefuncs.go
pkg/cmd/testdata/scripts/doctor_unix.txtar
pkg/cmd/testdata/scripts/passhole.txtar

Co-authored-by: @JackTheMico
Replaces #2301.
This should not be merged until passhole supports reading a password from stdin (which [version 1.9.9 does not support](https://github.com/Evidlo/passhole/blob/v1.9.9/passhole/passhole.py#L370-L388)).

feat: Add passhole password manager support

---

assets/chezmoi.io/docs/quick-start.md

i have setup already my git to use with https - i got authentification errors when i used this settings. i have to find out why my authentification fails.
also GitHub recommends the https version
PS: maybe we show both variants here

docs: change remote origin - from ssh to https

---

pkg/cmd/sourcepathcmd.go
pkg/cmd/testdata/scripts/issue2380.txt

fix: Respect .chezmoiroot in source-path command with no arguments

---

assets/chezmoi.io/docs/reference/templates/functions/eqFold.md
assets/chezmoi.io/mkdocs.yml
pkg/cmd/config.go
pkg/cmd/templatefuncs.go
pkg/cmd/testdata/scripts/templatefuncs.txtar

Adds a template function which utilizes [`strings.EqualFold()`](https://pkg.go.dev/strings#EqualFold) for robust comparison.
Removes the need for `{{ if eq "foo" ("FOO" | lower) }}` and similar.
The name is placeholder, as "equal fold" doesn't seem to be a particularly standard name for case-insensitive string comparison, so I'm more than happy to change it if you know a better name.
Also, do you think it makes sense to accept an arbitrary number of strings, similar to `eq`? Perhaps something other than `strings.EqualFold()` would be required for this.

feat: Add eqFold template function

---

assets/chezmoi.io/docs/reference/templates/1password-functions/index.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordDetailsFields.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordDocument.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordItemFields.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordRead.md
assets/chezmoi.io/docs/user-guide/password-managers/1password.md
pkg/cmd/onepasswordtemplatefuncs.go
pkg/cmd/testdata/scripts/onepassword2.txtar

This is the long-promised draft of the 1Password account lookup table discussed in #1974.
Basic testing using `execute-template` with various values seems to work *very* well, but I have not yet modified the tests or test scripts to run this new functionality.

feat: 1Password account lookup table

---

pkg/cmd/onepasswordtemplatefuncs.go
pkg/cmd/onepasswordtemplatefuncs_test.go

Refs #2425. cc @halostatue
A couple of changes:
* Factor out `onepasswordAccountMap` function for testing.
* Add test for desired behavior, replacing comment.
* Simplify logic by detecting collisions after map has been built.
* Use [`strings.Cut`](https://pkg.go.dev/strings#Cut).
Please tell me if anything is missing.

chore: Refactor 1Password account map

---

assets/chezmoi.io/docs/index.md
assets/chezmoi.io/docs/install.md.tmpl
assets/chezmoi.io/docs/user-guide/daily-operations.md
assets/templates/install.sh

Refs #2430. cc @felipecrs 
I think this is correct. We should probably add an equivalent to `get.chezmoi.io` for PowerShell users.

docs: Use get.chezmoi.io for install links

---

.gitignore
.goreleaser.yaml
Makefile
assets/chezmoi.io/docs/developer/packaging.md
assets/scripts/generate-commit.sh
pkg/cmd/cmd.go

As [discussed](https://github.com/twpayne/chezmoi/pull/2442#issuecomment-1275066645) om #2442.
@FilippoBonazziSUSE this means that chezmoi versions 2.25.0 and later will have a `COMMIT` file in the source archive containing the git commit hash.

chore: Add COMMIT file to source archives

---

pkg/chezmoi/entrytypeset.go
pkg/chezmoi/sourcestate.go
pkg/chezmoi/sourcestateentry.go
pkg/chezmoi/targetstateentry.go
pkg/cmd/testdata/scripts/external.txtar
pkg/cmd/testdata/scripts/issue2427.txt

Fixes #2427.
@sm1999 would you be able to test this, and, ideally find a way where `--include` and `--exclude` don't behave as expected with these changes? I'll leave an explanatory comment in #2427.

feat: Improve handling of include and exclude for externals and encrypted files

---

assets/chezmoi.io/docs/reference/command-line-flags/common.md
pkg/chezmoi/entrytypeset.go
pkg/chezmoi/entrytypeset_test.go
pkg/chezmoi/sourcestate.go
pkg/chezmoi/sourcestateentry.go
pkg/cmd/config.go
pkg/cmd/testdata/scripts/managed.txtar

Refs @sm1999 in https://github.com/twpayne/chezmoi/issues/2427#issuecomment-1278819861.
This allows you to run commands like:
```console
$ chezmoi managed --include=templates
```
to list all your templates.
chezmoi still needs some work here. The `--include` and `--exclude` flags mix two separate concepts: target state (e.g. `files`, `dirs`,`symlinks`, etc.) and source state (e.g. `encrypted`, `externals`, `templates`). This leads to conflicts when both are specified, for example should `--include=files --exclude=templates` include templated files or not?
Fixing this properly is probably a task for chezmoi v3.

feat: Extend --include and --exclude flags to include templates

---

.github/ISSUE_TEMPLATE/01_support_request.md

I first noticed this when reading https://github.com/twpayne/chezmoi/issues/2446.
An alternative solution would be to add an index page to the user guide section.

chore: Fix user guide link in support issue template

---

pkg/chezmoi/sourcestate.go
pkg/cmd/config.go
pkg/cmd/templatefuncs.go
pkg/cmd/testdata/scripts/configstate.txtar
pkg/cmd/testdata/scripts/templatedirectives.txtar
pkg/cmd/testdata/scripts/templatefuncs.txtar

Fixes #2468
Template directives have been added, but some places were missed in the initial implementation and review (oops).
- pkg/cmd/templatefuncs.go (`includeTemplateTemplateFunc`)
- pkg/chezmoi/sourcestate.go (`addTemplatesDir`)
- pkg/cmd/config.go (`createConfigFile`)
- pkg/cmd/config.go (`gitautoCommit`)
The last is not necessary (since the template is only included as an asset and cannot be replaced), so it can be reversed without issue.

fix: Extend template directives functionality

---

assets/chezmoi.io/docs/user-guide/password-managers/bitwarden.md

[bitwarden/cli][1] is now archived and the code of Bitwarden CLI is now inside [bitwarden/clients][2]. However, since we are only using Bitwarden CLI here instead of trying to contribute to its code, linking to [documentation for Bitwarden CLI][3] may be more helpful.
[1]: https://github.com/bitwarden/cli
[2]: https://github.com/bitwarden/clients
[3]: https://bitwarden.com/help/cli

docs(bitwarden): Update outdated Bitwarden CLI link

---

pkg/chezmoi/actualstateentry.go
pkg/chezmoi/entrytypefilter.go
pkg/chezmoi/format.go
pkg/chezmoi/gitdiffsystem.go
pkg/chezmoi/sourcestateentry.go

This PR changes comments for some functions and structs that are started with the incorrect name.

chore: Fix comments that start from an incorrect name

---

.golangci.yml
assets/chezmoi.io/docs/docs.go
pkg/archivetest/archivetest.go
pkg/chezmoibubbles/chezmoibubbles.go

This enables the `stylecheck` linter's `ST1000` warning to be enabled, thanks to @alexandear in https://github.com/twpayne/chezmoi/pull/2484#issue-1420962977.

chore: Add package descriptions

---

assets/chezmoi.io/docs/reference/templates/bitwarden-functions/bitwardenFields.md

The example is about `token.value`, so `token` should be part of the `fields` of `bw get` output.

docs(bitwarden): Correct bitwardenFields example

---

assets/chezmoi.io/docs/developer/install-script.md
assets/chezmoi.io/docs/reference/command-line-flags/global.md
assets/chezmoi.io/docs/reference/commands/cat.md
assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoi-format-tmpl.md
assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md
assets/chezmoi.io/docs/reference/target-types.md
assets/chezmoi.io/docs/user-guide/encryption/gpg.md
assets/chezmoi.io/docs/user-guide/frequently-asked-questions/design.md
assets/chezmoi.io/docs/user-guide/password-managers/1password.md

(+ a typo fix)
I found these by RegEx searching `\b(\w+)\s+\1\b`.

docs: Remove duplicate words

---

pkg/cmd/onepasswordtemplatefuncs.go

Indirectly, the lack of setting `onepasswordArgs.account` in `onepasswordReadTemplateFunc` was causing 1Password to prompt me for an account, even though it's provided.
The selection is prompted by the `withSessionToken` handling, which depends on `onepasswordAccount.account`.
Discovered while investigating #2498.

Make `onepasswordRead` respect the passed account

---

pkg/cmd/config.go

Closes #2502
Round-tripping the template data via JSON caused a data regression such that values that were `map[string]any{nil}` (the default value) are turned into `null` in JSON and therefore `nil` in a template. Previously, the value of `map[string]any{nil}` would be rendered as `{}`.
Manual construction of the map restores the old functionality. For chezmoi version 3, we may want to consider *restoring* the behaviour from `v2.25.0` (`null`), but this is a regression version version 2.
```console
$ go run . execute-template '{{ .chezmoi.osRelease | toJson }}'
null%
$ go run . execute-template '{{ .chezmoi.osRelease | toJson }}'
{}%
```

fix: Construct `templateDataMap` manually

---

assets/chezmoi.io/mkdocs.yml

It appears we missed this in both https://github.com/twpayne/chezmoi/commit/2c440aba38f10c04af548da3c7ae263a2c411c6f and https://github.com/twpayne/chezmoi/commit/520e4a6d0663aeb6eeafb4352906fdffecbd6702.

chore: Reorder eqFold template function reference page

---

.github/workflows/main.yml

Partial fix for https://github.com/twpayne/chezmoi/issues/2526
This reverts the version "bump" done in https://github.com/twpayne/chezmoi/commit/d6da479e158236e14c584f5a0e915c70bf3c8370.
We may have to deal with the bot attempting to bump it again, should be as simple as telling it to stop in a comment if it opens another PR.

fix: Revert cpina/github-action-push-to-another-repository version bump

---

.github/workflows/main.yml

Fixes #2525.
Builds on #2527.
Draft PR for testing, but should do the full website deploy.
The "Disable jobs for testing" commit needs to be removed before merging.

chore: Install Go in test-website and deploy-website jobs

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
pkg/chezmoi/externaldiffsystem.go
pkg/chezmoi/gitdiffsystem.go
pkg/cmd/config.go
pkg/cmd/diffcmd.go
pkg/cmd/testdata/scripts/exclude.txtar
pkg/cmd/testdata/scripts/issue-2510.txtar
pkg/cmd/testdata/scripts/script_unix.txtar
pkg/cmd/testdata/scripts/scriptonce_unix.txtar

As requested by @halostatue in https://github.com/twpayne/chezmoi/issues/2536#issuecomment-1299402155.
You can set `diff.scriptContents` to `false` in your configuration file.

feat: Add --script-contents flag to diff command

---

assets/chezmoi.io/docs/reference/commands/init.md

I was a bit confused with the location of the `~` in the pattern and, sure enough, it didn't work when entered as documented. I also removed an incorrect `/`.

docs: Fix typos in Sourcehut repo patterns

---

assets/templates/versioninfo.json.tmpl
internal/cmds/execute-template/main.go

Previously, generating `versioninfo.json` required `git describe --abbrev=0 --tags` to succeed, which is not the case when chezmoi is forked (https://github.com/deivid-rodriguez/chezmoi/pull/2) or if chezmoi is built from a source archive (where there is no git repo). With this commit, `versioninfo.json` is generated in both cases, albeit without a correct version or commit hash. This allows the `test-release` job to succeed on forks.
cc @deivid-rodriguez

chore: Make generation of versioninfo.json work without tags or git repo

---

assets/chezmoi.io/docs/reference/commands/update.md
assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/chezmoi.io/docs/user-guide/advanced/customize-your-source-directory.md
pkg/cmd/testdata/scripts/issue2577.txt
pkg/cmd/updatecmd.go

Refs #2577. Refs #1801.
This allows you to override what happens when you run `chezmoi update`, which makes chemzoi much more usable with non-git VCSes. See the addition to the user guide in this PR for details.

feat: Make it easier to use non-git VCSes

---

assets/chezmoi.io/docs/reference/target-types.md

Adds an example of how interpreters are configured if using a YAML config file

Add YAML example for interpreters

---

assets/chezmoi.io/docs/reference/templates/functions/stat.md

I assumed that `stat(2)` in 
>stat runs stat(2) on name
was meant as a reference to the docs explaining what `stat` is , but then the `(2)` is strange, so maybe it means something else

docs: Update stat.md to reference os.Stat

---

assets/chezmoi.io/docs/reference/target-types.md

Noticed this small issue in the docs:

docs: Fix config path in scripts doc

---

assets/chezmoi.io/docs/user-guide/tools/merge.md

Noticed a small typo on the merge page of the user guide.

docs: Fix typo in merge user guide

---

pkg/chezmoi/archive.go
pkg/chezmoi/archive_test.go

Tarballs from `registry.npmjs.org` only include a flattened list of files, and thus don't contain any tar headers where `header.Typeflag == tar.TypeDir`.
This causes `chezmoi apply` to fail the first time it tries to create a file whose parent directory does not exist.
Here's an example of an `npm` tarball vs one from `GitHub`:
```sh
> curl -sL https://github.com/npm/node-semver/tarball/v7.3.8 --output gh.tgz
> curl -sL https://registry.npmjs.org/semver/-/semver-7.3.8.tgz --output npm.tgz
> tar ztvf npm.tgz | grep "^d" # no output
> tar ztvf gh.tgz | grep "^d"
drwxrwxr-x  0 root   root        0 Oct  4 12:37 npm-node-semver-dc0fe20/
drwxrwxr-x  0 root   root        0 Oct  4 12:37 npm-node-semver-dc0fe20/.github/
drwxrwxr-x  0 root   root        0 Oct  4 12:37 …
```

fix: walk flattened external archives

---

pkg/chezmoi/archive.go
pkg/chezmoi/archive_test.go

Fix for https://github.com/twpayne/chezmoi/issues/2700
Zip files can have multiple levels of directories that don't have files in them. This fix is similar to https://github.com/twpayne/chezmoi/commit/e74a926a464961f66cdb3476eb1f2ef79f56f5e9 but applies to .zip files.
Essentially a mkdir -p on the path to the file prior to writing the file.

fix: Support .zip files with empty internal directories

---

assets/chezmoi.io/docs/install.md.tmpl
assets/chezmoi.io/docs/quick-start.md

Issue on private GitHub repos: URL login is deprecared, SSH used instead.
When connecting to GitHub by URL, there was an error: "Support for password authentication was removed on August 13, 2021. Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication."

docs: note about actual auth types for GitHub private repos

---

assets/chezmoi.io/docs/reference/commands/chattr.md
assets/chezmoi.io/docs/reference/source-state-attributes.md
pkg/chezmoi/attr.go
pkg/chezmoi/attr_test.go
pkg/chezmoi/chezmoi.go
pkg/chezmoi/relpath.go
pkg/chezmoi/sourcestate.go
pkg/chezmoi/sourcestate_test.go
pkg/cmd/chattrcmd.go
pkg/cmd/chattrcmd_test.go
pkg/cmd/main_test.go
pkg/cmd/testdata/scripts/externaldir.txtar

Fixes #2714.
@peterbraden would you be able to test this? For each of your git submodules, you should add the `external_` attribute in their directories. In your case, the following should work:
```console
$ chezmoi chattr +external ~/.vim/bundle/*
```
You'll probably also not want chezmoi to copy `.git` directories from the git submodules. To prevent this, add
```
.vim/bundle/**/.git
```
to your `.chezmoiignore`.

feat: Add external_ attribute for directories

---

.github/workflows/winget.yml

[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
Before merging this:
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.
2. Fork https://github.com/microsoft/winget-pkgs under @twpayne. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.
You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).
If you want to …

ci: add Winget Releaser workflow

---

pkg/cmd/templatefuncs.go
pkg/cmd/templatefuncs_test.go

Closes #2768
In `fromIni`, the `iniFileToMap` function converts top-level keys (the so-called "default" section) to being members of a `DEFAULT` map key, which results in different data than expected. Specifically, roundtripping fails such that `{{ . | fromIni | toIni }}` does not produce the same output as input.
This change results in code duplication, but prevents the unnecessary creation of a new `map[string]any` or a second loop for merging.

fix: Eliminate [DEFAULT] section for `fromIni` map

---

pkg/chezmoi/sourcestate.go
pkg/cmd/testdata/scripts/issue2302.txtar

fix: Detect absolute paths in externals on Windows

---

assets/chezmoi.io/docs/reference/configuration-file/editor.md

Slight tweak to reference documentation to correct editor argument key.
Pretty sure this is right. It's at least what worked for me on
```bash
❯ chezmoi --version
chezmoi version v2.31.0, commit 4d2bc846212e27fae1e5bbd45d70e00908da603b, built at 2023-02-17T11:19:43Z, built by Homebrew
```

correct configuration file syntax for edit.args

---

pkg/cmd/initcmd.go
pkg/cmd/initcmd_test.go

fix: Allow underscores and dots in GitHub dotfile repo name guesses

---

pkg/cmd/cdcmd.go

This potentially fixes #2821 by setting the `$PS1` environment variable and stopping `chezmoi cd` subshells from nesting.
Review appreciated on this.

Improve chezmoi cd command

---

assets/chezmoi.io/docs/reference/command-line-flags/global.md
assets/chezmoi.io/docs/reference/commands/init.md
assets/chezmoi.io/docs/reference/configuration-file/index.md
assets/chezmoi.io/docs/reference/templates/functions/fromJsonc.md
assets/chezmoi.io/docs/user-guide/manage-different-types-of-file.md
assets/chezmoi.io/docs/user-guide/manage-machine-to-machine-differences.md
assets/chezmoi.io/mkdocs.yml
go.mod
go.sum
pkg/chezmoi/format.go
pkg/chezmoi/format_test.go
pkg/cmd/config.go
pkg/cmd/templatefuncs.go
pkg/cmd/testdata/scripts/config.txtar
pkg/cmd/testdata/scripts/templatefuncs.txtar

Fixes #2825.
@felipecrs can you test this?

feat: Add support for the JSONC format

---

pkg/chezmoi/sourcestate.go
pkg/cmd/addcmd.go
pkg/cmd/testdata/scripts/issue1832.txtar
pkg/cmd/testdata/scripts/issue2820.txtar

Refs #2820.
@bradenhilton I'd appreciate your thoughts on this. Right now, this stops `chezmoi add` from adding any path where `chezmoi` is one of the components, but it's a pretty simple check and there are probably improvements/fixes.

feat: Refuse to add chezmoi files to chezmoi

---

assets/chezmoi.io/docs/reference/command-line-flags/global.md
assets/chezmoi.io/docs/reference/configuration-file/index.md
assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml

This is an offshoot of #2773 that includes only documentation updates.
- Global flags that have configuration variables which can provide a default have that variable stated as part of the flag documentation.
- Added a JSONC configuration example after JSONC support was added.
- Improved information for config var defaults
- Clarify multiple config file behaviour

docs: Updated config / flags documentation information

---

main.go
pkg/chezmoi/chezmoi_unix.go
pkg/chezmoi/chezmoi_unix_test.go
pkg/chezmoi/path_unix.go
pkg/chezmoi/realsystem_unix.go
pkg/chezmoitest/chezmoitest_unix.go
pkg/cmd/doctorcmd_unix.go
pkg/cmd/keyringtemplatefuncs.go
pkg/cmd/keyringtemplatefuncs_freebsdnocgo.go
pkg/cmd/noupgradecmd.go
pkg/cmd/secretkeyringcmd.go
pkg/cmd/secretkeyringcmd_freebsdnocgo.go
pkg/cmd/upgradecmd.go
pkg/cmd/upgradecmd_test.go
pkg/cmd/util_unix.go
pkg/shell/shell_darwin.go
pkg/shell/shell_plan9.go
pkg/shell/shell_posix.go
pkg/shell/shellcgo.go
pkg/shell/shellnocgo.go

This PR removes `// +build` comments because the minimum supported version is Go 1.18 by running the command:
```
go fix -fix buildtag ./...
```

chore: Remove +build comments from modules

---

.golangci.yml

The PR modifies `.golangci.yml` to use [`run.go`](https://github.com/golangci/golangci-lint/blob/28a94fde5cd3a075e012683a43ae96e69ca6e3e8/.golangci.reference.yml#L73) option instead of [deprecated `gofumpt.lang-version`](https://github.com/golangci/golangci-lint/blob/28a94fde5cd3a075e012683a43ae96e69ca6e3e8/.golangci.reference.yml#L629).

chore: Use run.go instead of deprecated lang-version

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/chezmoi.io/docs/reference/templates/ejson-functions/ejsonDecrypt.md
assets/chezmoi.io/docs/reference/templates/ejson-functions/ejsonDecryptWithKey.md
assets/chezmoi.io/docs/reference/templates/ejson-functions/index.md
assets/chezmoi.io/docs/user-guide/password-managers/ejson.md
assets/chezmoi.io/mkdocs.yml
go.mod
go.sum
pkg/cmd/config.go
pkg/cmd/ejsontemplatefuncs.go
pkg/cmd/testdata/scripts/ejson.txtar

This adds support for [ejson](https://github.com/Shopify/ejson) which allows to store secrets in a git repository using asymmetric encryption. Since this is basically encrypted json, once decrypted it can be parsed pretty easily and made accessible to `chezmoi` as the full JSON data structure.
**Note:** I put this as part of the password managers, as it feels like it'd be used in a similar way (this does not encrypt full files like `age` or `gpg` but keeps the structured JSON view and only encrypts the values, i.e. encrypts secrets and not files).
e.g.
```bash
$ ejson keygen
Public Key:
d5f0647bc4eea75296381787c55d52996873f156874885d685ddaf26f3e61f13
Private Key:
xxxxxxxxxxxxxxx
```
```bash
$ cat /tmp/ejson-test.ejson
{
"_public_key": …
```

feat: Add support for ejson

---

assets/chezmoi.io/docs/reference/templates/functions/jq.md
assets/chezmoi.io/mkdocs.yml
go.mod
go.sum
pkg/cmd/config.go
pkg/cmd/templatefuncs.go
pkg/cmd/testdata/scripts/templatefuncs.txtar

feat: Add jq template function

---

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoi-format-tmpl.md
assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md
assets/chezmoi.io/docs/user-guide/setup.md
assets/chezmoi.io/docs/user-guide/templating.md

I _think_ these changes are correct. I wasn't sure if `jsonc` was only supported for the config file or not.

docs: Add missing `jsonc` to some formats

---

assets/chezmoi.io/docs/user-guide/machines/windows.md

I wish I had done this sooner to when I made the change locally to remember the exact details. But if I recall correctly, this was necessary to make sure that a PS script that was auto-elevating would fully complete before the next chezmoi step/script executes.  Without `-Wait`, `Start-Process` returns immediately and the elevated script could still be running while the "base" one that kicked it off exits and lets chezmoi progress; if anything after that step depends on the elevated script having finished, it might not work as expected.
Of note, in my local setup I removed `-NoExit` from the args passed to the elevated powershell, so it would exit on its own once it's done instead of leaving a open window that might have no output or indication if anything is happening, that the user …

docs: Wait for elevated PS process to return

---

assets/chezmoi.io/docs/reference/commands/add.md
pkg/cmd/addcmd.go
pkg/cmd/testdata/scripts/addautotemplate.txtar

Remove `--autotemplate` from `chezmoi --help` and print a message when it is used.
> > @twpayne Should `--autotemplate` be deprecated for removal in v3?
> Yes, I think it was too ambitious and too fragile.
Resolves #2873 and other related issues.

chore: Deprecate `--autotemplate`

---

pkg/cmd/config.go
pkg/cmd/testdata/scripts/scriptenv.txtar

fix: Only set $CHEZMOI_VERBOSE when --verbose is set

---

.goreleaser.yaml

According to the fish documentation[1], `/usr/share/fish/vendor_completions.d/` is the proper place for third-parties to install completion files.
[1] https://fishshell.com/docs/current/completions.html

fix: Change where fish completions are installed

---

assets/chezmoi.io/docs/user-guide/tools/diff.md
assets/chezmoi.io/docs/user-guide/tools/merge.md

I ran into this today and had to google a bit until I found the [answer on Stackoverflow](https://stackoverflow.com/q/17641887/110204).
Somewhat surprisingly, the [documentation](https://pkg.go.dev/text/template) doesn't seem to explain this directly: instead it just says that an "argument" can be a value like a Boolean, a string, etc, and a "pipeline" is a series of "commands" and, finally, a "command" can be a single "argument" :smile:

docs: Document how to escape `{{` and `}}` in templates

---

assets/chezmoi.io/docs/reference/templates/variables.md
pkg/cmd/config.go

feat: Add .chezmoi.config template variable

---

pkg/cmd/config.go
pkg/cmd/testdata/scripts/issue2865.txtar

fix: Set CHEZMOI_SOURCE_DIR env var in init when using .chezmoiroot

---

pkg/cmd/autobool.go
pkg/cmd/config_test.go
pkg/cmd/githubtemplatefuncs.go

Re-opens #3034. The original branch was deleted so I couldn't simply re-open the original PR.
Thanks for this @alexandear!
@bradenhilton was right in https://github.com/twpayne/chezmoi/pull/3034#issuecomment-1586907929 that this subtly changes the semantics of refresh periods, but refresh periods are more guidelines than rules and as Go records timestamps in nanoseconds, the chances of hitting this are minuscule and it wouldn't matter anyway.

chore: Simplify code by using strings.EqualFold, time.Before

---

pkg/chezmoi/sourcestate.go
pkg/cmd/upgradecmd.go

This PR refactors code by using https://pkg.go.dev/net/http#NoBody instead of `nil`.

chore: Use http.NoBody instead of nil

---

pkg/chezmoi/chezmoi.go
pkg/chezmoi/chezmoi_test.go

fix: Parse hostnames from all loopback addresses in /etc/hosts

---

assets/chezmoi.io/docs/user-guide/include-files-from-elsewhere.md

Unsure why `command = "tar"` doesn't work on windows, but for some reason it wants to read from a tape, not stdin.
Windows doesn't have /dev/stdin so any commands referencing it fail. It is the default anyway, so no need to specify it.

docs: Remove reference to tar and /dev/stdin so code works on Windows

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/chezmoi.io/docs/reference/templates/hcp-vault-secrets-functions/hcpVaultSecret.md
assets/chezmoi.io/docs/reference/templates/hcp-vault-secrets-functions/hcpVaultSecretJson.md
assets/chezmoi.io/docs/reference/templates/hcp-vault-secrets-functions/index.md
assets/chezmoi.io/docs/user-guide/password-managers/custom.md
assets/chezmoi.io/docs/user-guide/password-managers/hcp-vault-secrets.md
assets/chezmoi.io/docs/what-does-chezmoi-do.md
assets/chezmoi.io/mkdocs.yml
pkg/cmd/config.go
pkg/cmd/doctorcmd.go
pkg/cmd/hcpvaultsecretsttemplatefuncs.go
pkg/cmd/testdata/scripts/doctor_unix.txtar
pkg/cmd/testdata/scripts/hcpvaultsecrets.txtar

Fixes #3061.
WIP. Not ready for review or merge yet.

feat: Add support for HCP Vault Secrets

---

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md
pkg/chezmoi/sourcestate.go
pkg/cmd/testdata/scripts/external.txtar

feat: Allow executable bits to be overridden in archive-file externals

---

.github/workflows/main.yml

Temporary fix for the build website workflow until they fix upstream.
https://github.com/mkdocs/mkdocs/issues/3310
https://github.com/fralau/mkdocs-mermaid2-plugin/issues/80

chore: fix website build by pinning mkdocs version to 1.4.3

---

pkg/cmd/config.go
pkg/cmd/diffcmd.go
pkg/cmd/testdata/scripts/issue3113.txtar

fix: Respect setting diff.pager to the empty string as disabling the pager

---

pkg/cmd/config.go
pkg/cmd/mackupcmd_darwin.go
pkg/cmd/mackupcmd_nodarwin.go
pkg/cmd/mackupcmd_test_darwin.go
pkg/cmd/testdata/scripts/mackup_darwin.txt

Fixes #885. Refs #1458.
This still needs more reliable detection of the mackup applications directory, hence draft for now.

feat: Add undocumented mackup command

---

pkg/cmd/mackupcmd_darwin.go
pkg/cmd/testdata/scripts/mackup_darwin.txt

@eugenesvk this should resolve https://github.com/twpayne/chezmoi/issues/885#issuecomment-1656728570.

fix: Make detection of mackup config dir more robust

---

internal/chezmoi/chezmoi_windows.go

This is based on:
* https://www.nextofwindows.com/what-is-pathext-environment-variable-in-windows
* It goes back to at least Windows XP: https://ss64.com/nt/syntax-variables.html potentially further
fix: Provide some logic for `isExecutable` under windows for determining if it's an executable
BREAKING CHANGE: `isExecutable` no longer always returns false and tries to determine execution status by file extension

fix: Implement some logic for `isExecutable` for windows

---

internal/cmd/main_test.go
internal/cmd/testdata/scripts/templatefuncs.txtar

Refs #3157. cc @arran4 
The issue was that the `PATHEXT` environment variable was not set in the tests. In the end, it wasn't a line ending issue because the contents of the files are never used.

chore: Fix isExecutable tests on Windows

---

assets/chezmoi.io/docs/reference/commands/add.md
internal/chezmoi/autotemplate.go
internal/chezmoi/autotemplate_test.go
internal/chezmoi/sourcestate.go
internal/chezmoi/sourcestate_test.go
internal/cmd/addcmd.go
internal/cmd/testdata/scripts/addautotemplate.txtar

Refs #3166.
This restores `--autotemplate`, with an improved, more robust algorithm for finding substitutions.
@bryango would you be able to test this?

feat: Restore --autotemplate flag to add command

---

.goreleaser.yaml

Fixes #3125.
GitHub-generated release notes seem to incorrectly credit PR authors, not commit authors.
Refs #2438.

chore: Generate release notes from git log, not GitHub

---

assets/chezmoi.io/docs/user-guide/manage-machine-to-machine-differences.md
internal/cmd/testdata/scripts/issue3163.txtar

Fixes #3163.
@rioka this should fix the issue you reported. There was a lot going on, with a mix of templates and symlinks.
chezmoi doesn't need to use symlinks, so I've updated the documentation to not use them.

docs: Improve documentation on using separate source files

---

assets/chezmoi.io/docs/reference/target-types.md
internal/cmd/util_windows.go

I've started writing scripts in [Nushell](https://www.nushell.sh/), then they can run on Windows, Linux, MacOS at once.
This just adds the mapping so Windows knows what to do with the file extension.

feat: Support nushell scripts on Windows

---

assets/chezmoi.io/docs/reference/templates/github-functions/gitHubLatestTag.md
assets/chezmoi.io/docs/reference/templates/github-functions/gitHubReleases.md
assets/chezmoi.io/docs/reference/templates/github-functions/gitHubTags.md
internal/cmd/config.go
internal/cmd/githubtemplatefuncs.go
internal/cmd/statecmd.go
internal/cmd/testdata/scripts/configstate.txtar
internal/cmd/testdata/scripts/githubtemplatefuncs.txtar
internal/cmd/testdata/scripts/state_unix.txtar
internal/cmd/testdata/scripts/state_windows.txtar

Adds a feature requested in discussion #3161.
- This reworks `gitHubLatestTag` to use `gitHubTags` and share the caching between the two functions.
- Pagination for both (both size and page number) is not configurable. This will always return the first page of items, where the size of the page is the default specified by GitHub. That is currently thirty items, but is subject to change.

feat: Add gitHubReleases and gitHubTags

---

assets/chezmoi.io/docs/install.md.tmpl

[Homebrew on Linux was formerly referred to as Linuxbrew](https://docs.brew.sh/Homebrew-on-Linux). The two projects got merged.

docs: Linuxbrew -> Homebrew

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/chezmoi.io/docs/reference/templates/bitwarden-functions/bitwardenSecrets.md
assets/chezmoi.io/docs/reference/templates/bitwarden-functions/index.md
assets/chezmoi.io/docs/user-guide/password-managers/bitwarden.md
assets/chezmoi.io/mkdocs.yml
internal/cmd/bitwardensecretstemplatefuncs.go
internal/cmd/config.go
internal/cmd/doctorcmd.go
internal/cmd/testdata/scripts/bitwarden.txtar
internal/cmd/testdata/scripts/doctor_unix.txtar

Fixes #3193.
@fslef would you be able to test this?

feat: Add bitwardenSecrets template function

---

.goreleaser.yaml

Fixes https://github.com/twpayne/chezmoi/issues/3188.
Untested at the moment. [`goreleaser changelog` is a pro feature](https://goreleaser.com/cmd/goreleaser_changelog/) and I'm not sure how else to test it.
I can re-include `chore`s if preferred.

fix: Update goreleaser changelog

---

assets/chezmoi.io/docs/reference/application-order.md

The discussion in #3198 suggests some confusion about the order of application. This adds a little more context.

docs: Minor expansion of application order docs

---

assets/chezmoi.io/docs/developer/developing-locally.md

The added documentation serves as the rationale for this documentation change:
If you use `fish` as your primary shell, you may get warnings from Fish during the `.txtar` tests:
```
error: can not save history
warning-path: Unable to locate data directory derived from $HOME: '/home/user/.local/share/fish'.
warning-path: The error was 'Operation not supported'.
warning-path: Please set $HOME to a directory where you have write access.
```
These can be avoided with by running tests with `SHELL=bash` or `SHELL=zsh`:
```console
$ SHELL=bash make test
$ SHELL=zsh make smoketest
$ SHELL=bash go test ./...
```
---
As a note, I tried to make `make test` re-execute when under `fish`, but it requires some GNU make magic that may not work on all systems:
```Makefile
.PHONY: test
test:
ifeq ($(shell …
```

docs: Improve developer experience under fish

---

internal/cmd/templatefuncs.go

Recently ran across [`MarshalIndent`](https://pkg.go.dev/encoding/json#MarshalIndent) in the docs.
The final newline is needed for backwards compatibility.

chore: use json.MarshalIndent in toPrettyJson

---

.github/workflows/main.yml
.goreleaser.yaml

Mostly done I believe.
Without `url_template`, the URLs in `chocolateyinstall.ps1` point to my fork instead of this repo.
My local `chezmoi.nuspec` file contains `&#xA;` instead of newlines. I'm hoping this is just because I'm on Windows at the moment. I'm attempting to upload the choco files as artifacts to confirm. This should be removed before merging.
I'll also run the artifacts through [Chocolatey .nuspec Checker](https://community.chocolatey.org/packages/choco-nuspec-checker) pending their successful upload and post the output.
I'm not sure what would happen when attempting to publish, due to the existing package.

feat: Use Goreleaser's Chocolatey support

---

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md
internal/chezmoi/sourcestate.go
internal/cmd/testdata/scripts/external.txtar
internal/cmds/lint-whitespace/main.go

This is somewhere between a fix and a feature because it is a potential bug if an archive contains AppleDouble data, as such data would automatically be written out as parallel `._FILE` files and not reintegrated. I've marked it as a feature because it requires new configuration options.
With this change, we are still not reintegrating the data, but we are explicitly _ignoring_ the data unless `EXTERNAL.archive.extractAppleDoubleFiles = true`. There are tools such as https://github.com/SiviourBla/appledouble that can theoretically reintegrate this using `copyfile(3)` on macOS.
This checks that the extracted file name will be `._*` before trying to determine whether the file is an AppleDouble file.
Resolves: #3220
Closes: #3221

feat: Ignore AppleDouble files in externals

---

assets/chezmoi.io/docs/reference/templates/variables.md
internal/cmd/config.go

This change exports a provided variable from Go which practically makes it free in terms of implementation costs.
This functionality would be implemented by hand by most people without variance when it is provided to Chezmoi by Go.
References: https://github.com/twpayne/chezmoi/pull/3162
There seems to be reference to this here too: 
https://github.com/twpayne/chezmoi/pull/3261#issuecomment-1734136510

feat: Add Path Separator and Path List Separator to provided template values

---

assets/chezmoi.io/docs/user-guide/include-files-from-elsewhere.md

Add information about `.chezmoiignore` in "Include dotfiles from elsewhere" documentation section. 
Closes: #3267

doc: Add information how to ignore cache files in external dependencies

---

internal/cmd/upgradecmd_windows.go
internal/cmd/util_windows.go

Fixes #2736
Very basic, not ready for merge yet.

fix: Don't use `replace-executable` for WinGet installations

---

internal/cmd/inittemplatefuncs.go

fix: Make stdinIsATTY return false if --no-tty is passed

---

.github/workflows/main.yml
assets/chezmoi.io/docs/hooks.py

-by anchoring to the config path instead of the current working directory.
The background for this is that I'm trying to build a whole bunch of random mkdocs sites to make sure my changes to mkdocs itself aren't disruptive.
https://github.com/mkdocs/regressions/actions/runs/6826747067/job/18567342675

refactor: Allow `mkdocs build` from any origin

---

internal/cmd/doctorcmd.go
internal/cmd/testdata/scripts/doctor_unix.txtar

Refs #3339.
In this issue the output from `chezmoi doctor` included:
```
warning   bitwarden-command    found /opt/homebrew/bin/bw, cannot parse version from (node:1388) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2023.10.0
```
Further investigation shows that the Bitwarden CLI writes a bunch of garbage to stderr:
```console
$ uname
Darwin
$ brew install bitwarden-cli
==> Downloading https://ghcr.io/v2/homebrew/core/bitwarden-cli/manifests/2023.10
######################################################################### 100.0%
==> Fetching bitwarden-cli
==> Downloading https://ghcr.io/v2/homebrew/core/bitwarden-cli/blobs/sha256:d028 …
```

chore: Handle garbage stderr output from Bitwarden CLI

---

assets/chezmoi.io/docs/reference/configuration-file/hooks.md
assets/chezmoi.io/docs/user-guide/advanced/install-your-password-manager-on-init.md
assets/chezmoi.io/mkdocs.yml
internal/cmd/cmd.go
internal/cmd/config.go
internal/cmd/testdata/scripts/hooks.txtar

Refs #3342.
Work in progress. Small code change, big impact. Feedback appreciated.

feat: Add read-source-state hook

---

assets/chezmoi.io/docs/reference/commands/forget.md
assets/chezmoi.io/docs/reference/commands/remove.md
assets/chezmoi.io/docs/reference/commands/rm.md

As suggested in #3362, this should improve discoverability by
cross-linking between the two types of target removal.

docs: Add admonitions linking remove and forget

---

assets/chezmoi.io/docs/reference/source-state-attributes.md

Based on the implementation here: https://github.com/twpayne/chezmoi/blob/6effb0ab449d0a22403e3fbf8a8d5b103604f7eb/internal/chezmoi/attr.go#L241-L246
I believe the prefix order for regular files is:
- `encrypted_`
- `private_`
- `readonly_`
- `empty_`
- `executable_`
The drift between the documentation and the implementation looks like it happened in two steps:
- `readonly_` was added to the implementation but excluded from the docs in #1403 
- `empty_` was added to the docs but in the wrong order by #2997 
Thanks for the awesome tool @twpayne !!!

docs: Clarify prefix order for regular files

---

internal/chezmoi/format.go
internal/cmd/templatefuncs.go
internal/cmd/testdata/scripts/templatefuncs.txtar

fix: Fix fromJson template function deserializing non-objects

---

assets/chezmoi.io/docs/reference/templates/github-functions/gitHubKeys.md

I (used to) use just the `gitHubKeys` function to populate my `~/.ssh/authorized_keys` file, but as I usually access GitHub over HTTPS, GitHub removed one of my SSH Keys due to it being "[stale](https://docs.github.com/en/authentication/troubleshooting-ssh/deleted-or-missing-ssh-keys)". If I didn't have another key on a different device, I would have lost access to machines which I exclusively interact with over SSH. 
As such, this pr expands upon the existing warning in the documentation to advise users to have other keys alongside the `gitHubKeys` output to prevent the same mistake I made.

docs: add warning for GitHub SSH key deletion

---

internal/cmd/agecmd.go
internal/cmd/helpcmd.go
internal/cmd/internaltestcmd.go
internal/cmd/licensecmd.go
internal/cmd/secretkeyringcmd.go

Removed annotations from `cobra.Command` structs that do not set
`RunE` as it does not appear necessary.
Modified the annotation for `help` and `license` to not require valid
config.
Fixes #3424.

fix: add missing command annotations

---

internal/chezmoitest/chezmoitest.go
internal/cmd/doctorcmd.go
internal/cmd/doctorcmd_unix.go
internal/cmds/execute-template/main.go
internal/cmds/generate-install.sh/main.go

Before this, stderr was occasionally unconnected when running commands, meaning that error information was lost. With this PR it should be visible more often, making debugging of commands easier.

chore: Connect stderr when running commands

---

.github/workflows/main.yml
assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/chezmoi.io/docs/reference/templates/keepassxc-functions/index.md
assets/chezmoi.io/docs/user-guide/password-managers/keepassxc.md
go.mod
go.sum
internal/cmd/config.go
internal/cmd/doctorcmd.go
internal/cmd/errors.go
internal/cmd/keepassxctemplatefuncs.go
internal/cmd/keepassxctemplatefuncs_test.go
internal/cmd/testdata/scripts/doctor_unix.txtar
internal/cmd/testdata/scripts/keepassxc.txtar

feat: Add support for YubiKeys with KeePassXC

---

internal/chezmoi/abspath.go

fix: Always use forward slashes to separate Windows paths

---

internal/cmd/keepassxctemplatefuncs.go
internal/cmd/testdata/scripts/keepassxc.txtar

fix: Restore user args to keepassxc-cli in cache password mode

---

assets/chezmoi.io/docs/reference/commands/edit.md
assets/chezmoi.io/docs/reference/configuration-file/hooks.md
assets/chezmoi.io/docs/reference/templates/doppler-functions/index.md
assets/chezmoi.io/docs/reference/templates/hcp-vault-secrets-functions/index.md
assets/chezmoi.io/docs/user-guide/advanced/install-your-password-manager-on-init.md
assets/chezmoi.io/docs/user-guide/password-managers/doppler.md
assets/chezmoi.io/docs/user-guide/password-managers/hcp-vault-secrets.md

This is only a documentation change, but promotes several features to stable by removing warnings about using them from the documentation. None of these features have had issues raised about them, which means that they either work or nobody uses them :)

feat: Promote multiple features to stable

---

assets/chezmoi.io/docs/reference/commands/re-add.md
internal/cmd/config.go
internal/cmd/readdcmd.go
internal/cmd/testdata/scripts/re-add.txtar

Fixes #3490.
@bryango would you be able to test this? You'll find pre-built chezmoi binaries in the artifacts section of the checks run by GitHub Actions on this PR. Sorry, there's no way to provide a direct link.
Technically, this is a backwards-incompatible change because the default behavior of `chezmoi re-add` changes from not-recursive to recursive. However, I think this is OK because the use case that it breaks is using `chezmoi re-add` on a directory where you want re-add the directory itself but not its contents. I suspect that this use case is sufficiently rare that it's OK to make this change with only a patch version bump, especially as `chezmoi re-add` is likely used interactively rather than scripted.

feat: Add re-add --recursive flag and make it the default

---

internal/cmd/keepassxctemplatefuncs.go
internal/cmd/keepassxctemplatefuncs_test.go

fix: Handle more keepassxc-cli errors

---

internal/cmd/addcmd.go
internal/cmd/catconfigcmd.go
internal/cmd/config.go
internal/cmd/doctorcmd.go
internal/cmd/editconfigcmd.go
internal/cmd/editconfigtemplatecmd.go
internal/cmd/purgecmd.go
internal/cmd/testdata/scripts/init.txtar
internal/cmd/testdata/scripts/initconfig.txtar
internal/cmd/testdata/scripts/issue3127.txtar

Here is an updated version of my previous PR. I have checked that it does what's expected and that it doesn't break any existing tests.
It should still be considered as a proof of concept rather than something ready to be submitted. My claim is that it contains the required logic to achieve the desired goal without breaking any existing behavior but that's about it. I haven't tried to add tests, yet. More importantly some changes, like in particular the replacement of `configFileAbsPath` with `configFileAbsPathDefault` and `configFileAbsPathExplicit`, look ugly. Note also that I have no experience programming in Go.
The main benefit of this change is that it becomes possible to use `chezmoi` with an alternate config simply by defining an alias like the following one:
`alias …

fix: Change init to default to --config if --config-path is absent

---

assets/chezmoi.io/docs/reference/commands/execute-template.md
assets/chezmoi.io/docs/user-guide/manage-machine-to-machine-differences.md
assets/chezmoi.io/docs/user-guide/templating.md

This combines the two similar sections "testing templates" and "debugging templates".
I've also taken the liberty to link to the section where (I found it) appropriate, but feel free to revert that commit if that isn't your style.

docs: combine testing and debugging templates

---

.goreleaser.yaml
assets/chezmoi.io/docs/install.md.tmpl
assets/scripts/install-local-bin.sh
assets/scripts/install.sh
internal/cmds/generate-install.sh/install.sh.tmpl

Fixes #3507.
@Grimler91, as a Termux contributor, is checking for the existence of a `termux-info` command a good way to detect Termux? As far as I can tell, `uname -a` on Termux returns `Linux`.

feat: Build for Android (Termux)

---

internal/chezmoi/realsystem.go
internal/chezmoi/sourcestate.go
internal/chezmoi/sourcestate_test.go
internal/chezmoi/system.go
internal/chezmoi/targetstateentry.go
internal/cmd/testdata/scripts/issue2934.txtar

Fixes #2934. It only took nine months.
@VorpalBlade this sets the `$CHEZMOI_SOURCE_FILE` environment variable for `modify_` scripts (and also normal scripts), which should be useful for your excellent [chezmoi_modify_manager](https://github.com/VorpalBlade/chezmoi_modify_manager).
As background info, this change became possible after 7203d6bfc (in chezmoi v2.40.3).
Would you be able to test this?

feat: Set CHEZMOI_SOURCE_FILE env var for scripts

---

internal/cmd/doctorcmd.go

This is a very small PR.
The larger context of this PR is in #3551. In short, `chezmoi doctor` tries to pass `-version` to `rage` during checks. While `-version` works fine for `age`, it is not supported in `rage`.
Given that both `age` and `rage` support `--version`, this PR changes the flag passed during `chezmoi doctor` checks.
Fixes #3551.

fix: Fix age/rage check in doctor command

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/chezmoi.io/docs/reference/templates/1password-functions/index.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepassword.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordDetailsFields.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordDocument.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordItemFields.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordRead.md
assets/chezmoi.io/docs/user-guide/password-managers/1password.md
internal/cmd/config.go
internal/cmd/onepasswordtemplatefuncs.go
internal/cmd/testdata/scripts/onepassword2.txtar
internal/cmd/testdata/scripts/onepassword2connect.txtar
internal/cmd/testdata/scripts/onepassword2service.txtar

Added a new configuration option, `onepassword.mode`, that can be set to
`account` (the default value), `connect` (for 1Password Connect), or
`service` (for 1Password Service Accounts).
When in `onepassword.mode` is:
- `account`: the presence of `OP_SERVICE_ACCOUNT_TOKEN`,
`OP_CONNECT_HOST`, and/or `OP_CONNECT_TOKEN` will cause chezmoi to
immediately exit; their presence changes the behaviour of the
1Password CLI.
- `connect`: the presence of `OP_SERVICE_ACCOUNT_TOKEN` or absences of
`OP_CONNECT_HOST` and/or `OP_CONNECT_TOKEN` will cause chezmoi to
immediately exit.
Additionally, the use of `onepasswordDocument` or passing an `account`
parameter will cause immediate exits.
- `service`: the absence of `OP_SERVICE_ACCOUNT_TOKEN` or presence of
`OP_CONNECT_HOST` and/or `OP_CONNECT_TOKEN` …

feat: 1Password Secrets Automation Support

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/requirements.txt
assets/scripts/format-yaml.py

This is an alternative to #3575.

chore: Work around ruamel.yaml errors when formatting YAML

---

internal/cmd/cmd.go
internal/cmd/config.go
internal/cmd/doctorcmd.go
internal/cmd/upgradecmd.go
internal/cmd/upgradecmd_unix.go
internal/cmd/upgradecmd_windows.go

This abstraction was not used.
Realistically, the project will always be called chezmoi, so removing the `gitHubRepo` constant makes sense.
The project owner abstraction in `gitHubOwner` is not consistently used. When chezmoi moves from twpayne/chezmoi to chezmoi/chezmoi this can easily be done with a string replacement.

chore: Remove owner/repo abstraction

---

.github/workflows/main.yml
assets/chezmoi.io/docs/install.md.tmpl
assets/scripts/install.ps1

I've been wanting to do this for a long time but always seemed to find something else to do instead.
Changes:
- Use PowerShell's [Approved Verbs](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-5.1)
- Use PowerShell's built-in output streams
- Remove unused functions
- General style changes to align more with the [unofficial style guide](https://poshcode.gitbooks.io/powershell-practice-and-style)
- ~Use GitHub's REST API (I am concerned this may cause issues with actions but I'm not sure. If this is preferred I can also make this change in `install.sh.tmpl`)~
- Removed almost 100 lines
`get_goos` handled FreeBSD, but I'm struggling to even find any information about PowerShell being installable on …

chore: Refactor install.ps1

---

internal/cmd/config.go
internal/cmd/testdata/scripts/issue3590.txtar

fix: Don't leak internal default sentinel values in template data

---

.github/workflows/installer.yml
.github/workflows/main.yml

Refs https://github.com/twpayne/chezmoi/issues/3366#issuecomment-1949615942
Experimental. I fully expect it to fail.

chore: Separate installer CI tests

---

assets/chezmoi.io/docs/hooks.py
assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
assets/chezmoi.io/docs/reference/templates/1password-functions/index.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepassword.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordDetailsFields.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordDocument.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordItemFields.md
assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordRead.md

Fixes https://github.com/twpayne/chezmoi/issues/3598.
Without these changes, I can reproduce the warnings mentioned in https://github.com/twpayne/chezmoi/issues/3598.
The warnings mentioned in https://github.com/twpayne/chezmoi/actions/runs/8043964297/job/21966863415#step:5:30 appear to be mainly concerning the templated pages.
The `hooks.py` change should resolve the `package internal/cmds/execute-template is not in std (/opt/hostedtoolcache/go/1.22.0/x64/src/internal/cmds/execute-template)` output.

chore: Fix broken relative links

---

internal/cmd/config.go
internal/cmd/testdata/scripts/addautotemplate.txtar
internal/cmd/testdata/scripts/issue3602.txtar

fix: Ensure that all .chezmoi.config template variables have simple types

---

internal/cmd/config.go
internal/cmd/templatefuncs.go
internal/cmd/testdata/scripts/templatefuncs.txtar

Fixes https://github.com/twpayne/chezmoi/issues/3603.

fix: Make splitList return []any

---

go.mod
go.sum
internal/cmd/unmanagedcmd.go

Fixes #3588.
This also makes `--keep-going` the default for `chezmoi unmanaged`.

fix: Fix panic in unmanaged on some dir permission errors

---

assets/templates/COMMIT_MESSAGE.tmpl
internal/chezmoigit/status_test.go
internal/cmd/testdata/scripts/autocommit.txtar

fix: Handle copies in automatic commit messages

---

internal/cmd/upgradecmd_unix.go

This ensures that pacman doesn't re-install an already up-to-date package

fix: pass the `--needed` flag to pacman

---

internal/chezmoi/sourcestate.go
internal/cmd/addcmd.go
internal/cmd/importcmd.go
internal/cmd/mackupcmd_darwin.go
internal/cmd/readdcmd.go
internal/cmd/testdata/scripts/issue3525.txtar
internal/cmd/testdata/scripts/issue3652.txtar

fix: Skip adding entries in external dirs instead of erroring

---

go.mod
go.sum
internal/cmd/addcmd.go
internal/cmd/config.go
internal/cmd/mackupcmd_darwin.go
internal/cmd/testdata/scripts/add.txtar
internal/cmd/testdata/scripts/issue3630.txtar

fix: Don't traverse into ignored directories when adding files

---

.goreleaser.yaml

This reverts commit 9b57763a79e2e744d53eafb6483972e32afbd3b8.
Refs https://github.com/canonical/snapcraft/issues/4769.

chore: Re-enable snapcraft builds

---

.github/workflows/installer.yml
assets/scripts/install.ps1

Fixes https://github.com/twpayne/chezmoi/issues/3749.

fix: fix error when determining GOARCH in install.ps1

---

internal/chezmoi/interpreter.go
internal/cmd/config_tags_test.go
internal/cmd/config_test.go

- add tags to interpreter.go so it passes
This runs ahead of attempts to add `chezmoi dump-config -f toml` 
(and possibly a version of a default config/config-template from that with some documentation comments)

chore: add test to ensure config struct tags match across marshals

---

assets/chezmoi.io/docs/reference/commands/doctor.md
internal/cmd/config.go
internal/cmd/doctorcmd.go
internal/cmd/doctorcmd_unix.go
internal/cmd/doctorcmd_windows.go

feat: Add --no-network flag to doctor command

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
internal/cmd/config.go
internal/cmd/editcmd.go

Fixes #3846.
@kjkent would you be able to test this?
tl;dr set the `tempDir` configuration variable in your config file to be a directory in the same btrfs subvolume as your source directory. If it's in your source directory then be sure to add it to your `.gitignore` as well.

feat: Add tempDir configuration variable

---

internal/cmd/editcmd.go
internal/cmd/testdata/scripts/issue3887.txtar

fix: Don't modify ciphertext in edit command if plaintext did not change

---

.github/workflows/main.yml
.golangci.yml
assets/chezmoi.io/docs/developer-guide/index.md
assets/chezmoi.io/docs/install.md.tmpl
assets/scripts/install-local-bin.sh
assets/scripts/install.sh
go.mod
internal/chezmoi/encryption_test.go
internal/chezmoi/sourcestate.go
internal/chezmoi/sourcestate_test.go
internal/cmd/config.go
internal/cmd/doctorcmd_unix.go
internal/cmd/util.go

This is a draft PR for when Go 1.23 is released (sometime in August).
The release of Go 1.23 means that Go 1.21 will no longer be supported so we can use Go 1.22 features.

chore: Build with Go 1.23

---

assets/chezmoi.io/docs/reference/templates/keepassxc-functions/index.md
assets/chezmoi.io/docs/user-guide/password-managers/keepassxc.md
internal/cmd/keepassxctemplatefuncs.go

Fixes #3910.
@mihakrumpestar would you be able to test this? tl;dr replace `keepassxc.args` with `keepassxc.openArgs` in your config file and it should work.
It's not easy for me to write a test for it because I don't use KeePassXC, don't have a YubiKey, and the "open" mode has two processes communicating with each other through a terminal.

feat: Support YubiKeys in KeePassXC open mode

---

assets/scripts/install-local-bin.sh
assets/scripts/install.sh
internal/cmds/generate-install.sh/install.sh.tmpl

This adds two options to curl downloads in the install script:
* `-f` (long version `--fail`), which tells curl to fail fast on server errors.
* `-S` (long version `--show-error`) which tells curl to show an error when it fails.
Fixes #3756 (I hope). I could not find equivalent options for downloading with `wget`.

chore: Show curl download errors in install script

---

assets/chezmoi.io/docs/user-guide/encryption/age.md
assets/chezmoi.io/docs/user-guide/encryption/gpg.md
assets/chezmoi.io/docs/user-guide/encryption/rage.md
assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md

Follow up to #3980 
* Advice to append content to the config in `encryption.md` very likely will cause `encryption` set incorrectly if config is not empty. Replace it with instructions what to do because command to prepend file in bash is a bit cumbersome and may also lead to incorrect config if other global settings are specified already.
* Add notes to articles about each encryption method to be careful with placement of `encryption` setting.

docs: Add notes where to place 'encryption' setting

---

assets/chezmoi.io/docs/user-guide/machines/macos.md

Somehow I overlooked existense of `output` for executing arbitrary commands. I guess its name doesn't give a hint that it runs something.
Add an example in user guide section from #3983 to show one more case how it can be used.

docs: Add example for running script on macOS update

---

assets/chezmoi.io/docs/reference/commands/age.md
assets/chezmoi.io/docs/reference/commands/secret.md
assets/chezmoi.io/docs/reference/commands/state.md

Addressing feedback from #3997 
Downgrade `h1` headings to keep only one `h1` on each page.
This is how it looks like now. Structured and table of contents looks good.
If we agree on that, I can update docs for other commands to follow similar style. Add sections like "Flags", "Common flags", "Example", "Notes".

docs: Split docs into sections for age, secret and state

---

internal/cmd/config.go
internal/cmd/templatefuncs.go
internal/cmd/templatefuncs_test.go

Similar to #4009 but for `squote` this time.
As you correctly mentioned on #4007 current implementation of `squote` in `sprig` is far from being correct. Here is my attempt to fix it.
Unfortunately, Go maintainers are not willing to provide an easier way for this in `strconv`: https://github.com/golang/go/issues/69958
Use existing `strconv.Quote` implementation for heavy lifting and escaping chars like `\n` or `\x...`. The only place where `quote` character is used apart from wrapping the string is here: https://github.com/golang/go/blob/c1d9303d82de0bae1b861b17ec4f9812392ea3cb/src/strconv/quote.go#L69
This is effectively a replacement and it can be undone with reverse `replaceAll`.
The final result should be identical to what `quoteWith(s, '\'', false, false)` in Go stdlib would produce …

feat: Extend squote template func to handle more types

---

assets/chezmoi.io/docs/reference/commands/add.md
assets/chezmoi.io/docs/reference/commands/destroy.md
assets/chezmoi.io/docs/reference/commands/execute-template.md
assets/chezmoi.io/docs/reference/commands/import.md
assets/chezmoi.io/docs/reference/commands/init.md
assets/chezmoi.io/docs/reference/commands/purge.md
assets/chezmoi.io/docs/reference/commands/update.md
assets/chezmoi.io/docs/reference/commands/verify.md
internal/cmd/cmd.go
internal/cmd/config.go
internal/cmd/doctorcmd.go

This will make commands documentation much easier to maintain and keep in sync with actual implementation.
* Check if all non global command flags are documented on corresponding docs page.
* Check if all flags mentioned in documentation exist either in command itself or globally.
* All fixes in docs are found by this feature.
* Downgrade `doctor --no-network` from persistent to regular flag as it doesn't have subcommands.
* Support `stateInAdmonition` only in long description. Otherwise maintaining correct state is more difficult (need to remember previous state) and it's only used for omitting it from long description.
* It's probably a good idea to add optimisation to not run this on release build. I guess this requires some build tag on release build.

docs: Automatically check that all flags are documented

---

assets/chezmoi.io/docs/reference/command-line-flags/common.md
assets/chezmoi.io/docs/reference/command-line-flags/developer.md
assets/chezmoi.io/docs/reference/command-line-flags/global.md
assets/chezmoi.io/docs/reference/commands/add.md
assets/chezmoi.io/docs/reference/commands/apply.md
assets/chezmoi.io/docs/reference/commands/archive.md
assets/chezmoi.io/docs/reference/commands/diff.md
assets/chezmoi.io/docs/reference/commands/dump.md
assets/chezmoi.io/docs/reference/commands/edit.md
assets/chezmoi.io/docs/reference/commands/import.md
assets/chezmoi.io/docs/reference/commands/init.md
assets/chezmoi.io/docs/reference/commands/managed.md
assets/chezmoi.io/docs/reference/commands/re-add.md
assets/chezmoi.io/docs/reference/commands/status.md
assets/chezmoi.io/docs/reference/commands/update.md
assets/chezmoi.io/docs/reference/commands/verify.md
assets/chezmoi.io/mkdocs.yml
assets/chezmoi.io/snippets/common-flags/exclude.md
assets/chezmoi.io/snippets/common-flags/include.md

* Move global and common flags from `h2` to `h3` to have consistent formatting with commands docs.
* Add description for global flags page.
* Improve description for `--path-style`. Having long list of values in the title doesn't look good in table of contents. Describe values in a table instead.
* Similar for `--config-format`.
* Address feedback from #3997 to move available entry types to its own separate section.
* Use snippets to deduplicate descriptions for `--include` and `--exclude`. This requires `validation.absolute_links=relative_to_docs`. Rest will be done in the next PR.

docs: Improvements for command flags description

---

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/usage.md

Few small improvements here:
* Write `powershell` in the same format as other shells.
* Add note that for powershell, completions need to be installed manually. Neither winget nor scoop install them. And there is no common convention where these scripts should be placed on Windows.
* Add links to `completion` command and template function.
* Simplify example nearby, IMO it was overly complex. Basically this changes for 1-indexing to 0-indexing for week number. And the last 2-3 days of the year are treated as a new 53rd week.

docs: Update shell completions section

---

assets/chezmoi.io/docs/reference/commands/index.md
assets/chezmoi.io/docs/reference/index.md
assets/chezmoi.io/mkdocs.yml
internal/cmd/cmd.go

This page is opened from the top level menu and linked in multiple places. But it's currently empty: https://www.chezmoi.io/reference/
Fill it with high level table of contents.
* Add `commands/index.md` as well to have a link to this section.
* `// go:embed` doesn't allow excluding files from pattern, so just ignore `index.md` in the code.

docs: Fill reference title page

---

assets/chezmoi.io/docs/reference/command-line-flags/common.md
assets/chezmoi.io/docs/reference/commands/add.md
assets/chezmoi.io/docs/reference/commands/apply.md
assets/chezmoi.io/docs/reference/commands/archive.md
assets/chezmoi.io/docs/reference/commands/chattr.md
assets/chezmoi.io/docs/reference/commands/data.md
assets/chezmoi.io/docs/reference/commands/destroy.md
assets/chezmoi.io/docs/reference/commands/diff.md
assets/chezmoi.io/docs/reference/commands/dump-config.md
assets/chezmoi.io/docs/reference/commands/dump.md
assets/chezmoi.io/docs/reference/commands/edit.md
assets/chezmoi.io/docs/reference/commands/ignored.md
assets/chezmoi.io/docs/reference/commands/managed.md
assets/chezmoi.io/docs/reference/commands/merge-all.md
assets/chezmoi.io/docs/reference/commands/re-add.md
assets/chezmoi.io/docs/reference/commands/status.md
assets/chezmoi.io/docs/reference/commands/unmanaged.md
assets/chezmoi.io/docs/reference/commands/update.md
assets/chezmoi.io/docs/reference/commands/verify.md
assets/chezmoi.io/snippets/common-flags/format.md
assets/chezmoi.io/snippets/common-flags/init.md
assets/chezmoi.io/snippets/common-flags/parent-dirs.md
assets/chezmoi.io/snippets/common-flags/path-style.md
assets/chezmoi.io/snippets/common-flags/recursive.md
assets/chezmoi.io/snippets/common-flags/tree.md

Finish what was started for `--include`/`--exclude` and deduplicate remaining common flags descriptions.
* Update descriptions for `--init` and `--parent-dirs` a bit.
* Fix description for `chezmoi unmanaged --path-style`. It only supports 2 values there.
* Use ["snippet sections"](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippet-sections) for `--recursive` and `--path-style` to cover differences in behaviour for different commands.

docs: Replace common flags descriptions with snippets

---

internal/chezmoi/pathstyle.go
internal/cmd/config.go
internal/cmd/managedcmd.go
internal/cmd/statuscmd.go
internal/cmd/testdata/scripts/completion.txtar
internal/cmd/testdata/scripts/unmanaged.txtar
internal/cmd/unmanagedcmd.go

Currently `unmanaged --path-style` accepts the same options as `managed --path-style`. And this is reflected in `unmanaged --help`. Misleading help message is reason why I added unsupported values to documentation initially.
But in fact, only `relative` and `absolute` values are expected there, unmanaged files are not present in the source tree. Every value which is not `absolute` is treated as `relative` which doesn't seem right.
* Add `PathStyleSimple` similar to `PathStyle` but with only 2 values.
* This also fixes values for shell completion.
* Added test to validate new behaviour.
```console
Description:
List all unmanaged files in paths. When no paths are supplied, list all
unmanaged files in the destination directory.
It is an error to supply paths that are not found on the …
```

fix: Accept only supported values to 'unmanaged --path-style'

---

internal/chezmoi/archive.go
internal/cmd/archivecmd.go
internal/cmd/config.go
internal/cmd/managedcmd.go
internal/cmd/statuscmd.go
internal/cmd/testdata/scripts/completion.txtar

`chezmoi archive --format` is different from other `--format` flags and expects format of the archive.
I found cleaner way to override completion function for individual command while keeping `commonFlagCompletionFuncs` unchanged.

fix: Fix completion for 'archive --format'

---

assets/chezmoi.io/docs/reference/index.md
assets/chezmoi.io/mkdocs.yml

These pages are closely related to commands, it makes sense to have them next to each other.

docs: Move command line flags links closer to commands

---

assets/chezmoi.io/docs/reference/special-files/chezmoiexternal-format.md

Hello!
Thanks so much for `chezmoi`! It's made managing my dotfiles a _breeze_.
I was perusing the chezmoi external format documentation and noticed a straggling 'o' in a numbered list.
Tiny PR to remove the typo!
Best :heart:,
@nfielder

docs: Remove extra 'o' from chezmoi external reference

---

internal/cmd/config.go

Refs #4041.
cc @KapJI.
It turns out that [`cobra.OnFinalize`](https://pkg.go.dev/github.com/spf13/cobra#OnFinalize) modifies [global state](https://github.com/spf13/cobra/blob/v1.8.1/cobra.go#L43). This breaks the tests, as the global state persists between tests, and so `Config.finalizeRootCmd` was being called multiple times.
Specifically, this meant that `diffPagerCmd.Wait` was being called multiple times, and the second and subsequent calls returned the error `exec: Wait was already called`.

chore: Fix finalization in tests

---

internal/cmd/datacmd_test.go
internal/cmd/testdata/scripts/doctor_unix.txtar
internal/cmd/testdata/scripts/gpgencryption.txtar
internal/cmd/testdata/scripts/gpgencryptionsymmetric.txtar
internal/cmd/testdata/scripts/issue3582.txtar

While checking issue which was fixed by #4048, I ran `go test ./... -v` and noticed few warnings which were introduced by #3981 . Either fix or check them in tests.

chore: Fix encryption warnings in tests

---

.github/workflows/main.yml

* Set `GOPATH`, `GOCACHE` and `GOMODCACHE` on Windows jobs. Drive `C:/` on Windows workers is extremely slow and now these jobs are as fast as on MacOS or Linux.
* `test-windows` job is down to **6m8s** from **18m30s**, **67%** imrovement!
* `lint-windows-2022` is down to **58s** from **3m10s**, **70%** improvement!
* This also saves 1.2 GB per cache version for duplicated Windows cache.
* Enable cache for `codeql` job. Re-use cache key generated by `actions/setup-go`. Run time is improved from [**2m19s**](https://github.com/twpayne/chezmoi/actions/runs/11709612098?pr=4063) to [**1m49s**](https://github.com/twpayne/chezmoi/actions/runs/11710960439?pr=4064), by **~22%**.

chore: Optimize Go caches in Github Actions

---

.github/workflows/main.yml
assets/docker/entrypoint.sh
assets/docker/test.sh

With ~300 MB per OS, create unique Go caches for Docker builds.
Make `test.sh` a bit more robust by allowing it to run from any directory. And add usage error if no arguments passed.
- `test-alpine` is down to **47s** from **1m30s**, **48%** improvement
- `test-archlinux` is down to **1m15s** from **1m53s**, **34%** improvement

chore: Enable Go cache for Docker builds

---

assets/docker/entrypoint.sh

Noticed small typo from #4065 in `GOCACHE` printed value. Use variables instead.

chore: Fix typo in entrypoint.sh

---

.github/workflows/govulncheck.yml
.github/workflows/main.yml

I found few issues with current cache keys on Linux:
1. `codeql` doesn't reuse cache with other jobs because paths should also match exactly.
2. `test-ubuntu` writes cache for ubuntu20 and `test-release` reads it. `test-release` should have isolated cache because it builds binaries for many other platforms. `test-ubuntu` should share cache with `lint-ubuntu` and `codeql` jobs.
3. `test-website` writes to cache with the key that is later read by `lint-ubuntu`. `test-website` doesn't build everything and its cache is incomplete. It should have its own cache key.
For every hash there were 5 cache entries for Linux:
- **setup-go-Linux-x64-ubuntu22-go-1.22.9-\<go-sum-hash\>** 300MB `oldstable-go`(w)
- **setup-go-Linux-x64-ubuntu20-go-1.23.3-\<go-sum-hash\>** 400MB `test-ubuntu`(w), …

chore: Optimize Linux caches on CI

---

.github/workflows/clear-pr-caches.yml

When PR is closed, caches can be removed immediately to keep more space for caches on master branch. Caches can't be shared between different PRs. And PRs can only use cache from themself or master branch.
There is 10 GB limit for total cache size per repo, although Github allows to go above this limit for short time (caches above threshold seems to be deleted daily).

chore: Delete pull request caches on close

---

.github/workflows/clear-pr-caches.yml

`DELETE /actions/caches` endpoint required `action: write` permission.
Failed job: https://github.com/twpayne/chezmoi/actions/runs/11769128068/job/32779753381

chore: Fix permissions for clear-pr-caches job

---

.github/actions/setup-go/action.yml
.github/workflows/main.yml

- Upload caches from test jobs allows to run tests faster even if source code changes.
- Create custom composite action to deduplicate caching code.
- Switch macos jobs to the latest `macos-15`. They can share the same cache entry now, so this saves one cache entry.
- Swich `test-ubuntu` jobs to `ubuntu-22.04`. Using old glibc only makes sense for release jobs. Using the same ubuntu version as for all other jobs allows sharing cache more effectively.
- Update name for `test-ubuntu-umask0xx` job.
- `codeql`: **2m56s** -> **2m18s**, 21% faster
- `test-ubuntu-umask002`: **6m43s** -> **5m35s**, 17% faster
- `test-ubuntu-umask022`: **7m29s** -> **6m12s**, 17% faster
- `test-windows`: **7m14s** -> **6m12s**, 14% faster
- `test-macos`: **8m46s** -> **8m32s**. Here cache was already uploaded from …

chore: Upload cache only from test jobs

---

.github/workflows/clear-pr-caches.yml

It seems write permission can't be set on job level, but can be set on workflow level, similar to how `lock-threads` does this.

chore: Set permissions for clear-pr-caches workflow

---

.github/workflows/clear-pr-caches.yml

This is actually mentioned in docs: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#managing-caches
> To run the following example on cross-repository pull requests or pull requests from forks, you can trigger the workflow with the pull_request_target event. If you do use pull_request_target to trigger the workflow, there are security considerations to keep in mind.
Security consideration here is that running or building PR code in this workflow is unsafe. But as this workflow doesn't do that, it's fine.
More notes on security are in "warning" section here: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
Also implement …

chore: Change clear-pr-caches trigger to pull_request_target

---

.github/workflows/main.yml
internal/cmd/main_test.go

- Add `-filter` flag to `TestScript` which allows to filter scripts by filename using regex. This can be useful for tests sharding and running individual test locally.
- `go test -short` runs all tests except `TestScript`.
- Split tests into 2 jobs:
- `test-index: 0` runs `./... -short` and `TestScript` tests `^[a-h]`
- `test-index: 1` run `TestScript` remaining tests `^[i-z]`
- Split macos tests into 3 jobs:
- `test-index: 0` runs `./... -short` and `TestScript` tests `^[a-d]`
- `test-index: 1` run `TestScript` remaining tests `^[e-i]`
- `test-index: 2` run `TestScript` remaining tests `^[j-z]`
- Split all tests into 2 shards: Workflow completion is down from **9m30s** to **6m20s**, 33% faster.
- Split macos tests into 3 shards: Workflow completion is down from **9m30s** to …

chore: Run tests in parallel jobs

---

assets/chezmoi.io/docs/reference/special-files/chezmoiexternal-format.md
internal/chezmoi/sourcestate.go
internal/cmd/testdata/scripts/externalfileurl.txtar

feat: Support file:// URLs in externals

---

.github/workflows/main.yml

Tests on Windows perform differently than on Linux and the second group is significantly slower. Split them more evenly.

chore: Tune Windows tests split

---

assets/chezmoi.io/docs/links/social-media.md
assets/chezmoi.io/docs/why-use-chezmoi.md

Twitter search links seem to require you to be logged in, and direct links no longer seem to work.

chore: Remove links to Twitter

---

internal/cmd/config.go
internal/cmd/testdata/scripts/issue4107.txtar

Fixes #4107.
Of course, we can be more precise with our detection of the Helix editor, but right now the current Helix release has been buggy for five months, so I propose to add more refined detection if/when Helix releases a fix.

feat: Warn if the user is using the Helix editor with chezmoi edit

---

assets/chezmoi.io/docs/reference/special-files/chezmoiexternal-format.md
internal/chezmoi/sourcestate.go
internal/cmd/testdata/scripts/externalfileurl.txtar

feat: Add multiple URL support for externals

---

assets/chezmoi.io/docs/links/videos.md.yaml

**Root Cause**
The YAML parser interprets the vertical bar `|` in the title as a special character, causing a parsing error. In YAML, `|` is used for literal block scalars, so when it appears in a string, it needs to be escaped to avoid misinterpretation.
**Fix**
Escape the `|` character in the title to prevent YAML parsing issues in HTML docs. The vertical bar is interpreted as a special character in YAML, so adding a backslash `\|` resolves the issue.
Relevant link: https://github.com/twpayne/chezmoi/pull/4096
I couldn't find any configuration in the [[MkDocs documentation](https://www.mkdocs.org/user-guide/configuration/)](https://www.mkdocs.org/user-guide/configuration/) to resolve this bug, and I'm unsure of an alternative fix.
I tried using `""` and `>` in the YAML syntax, but …

fix: YAML parsing error by escaping `|` in `title`

---

assets/scripts/install.ps1

Value returned by `(Get-CimInstance -Class Win32_OperatingSystem).OSArchitecture` is locale dependant.
This version should work the same for any locale. And it works both in powershell.exe and pwsh.exe.
Fixes #4127

fix: More reliable arch detection in install.ps1

---

.github/workflows/main.yml

In #4128 we noticed that `test-ubuntu` is running 4 times in different configurations. But because testing is omitted there, all jobs are essentially running the same build. There is no need to do it more than once.
Unfortunately, `matrix` variable is not available on job level (https://github.com/actions/runner/issues/1985), so I added it to every step to make other 3 jobs empty.

chore: Run single Ubuntu build if there are no code changes

---

assets/scripts/install.ps1

`Expand-Archive` may work incorrectly if default locale is not `en-US`. There is the fix (https://github.com/PowerShell/Microsoft.PowerShell.Archive/pull/46) but it's not available by default, e.g. my Windows 11 only has `Microsoft.PowerShell.Archive` version `1.0.1.0`. And bug was fixed in `1.2.1.0`.
I remember there was another issue if [Pscx](https://github.com/Pscx/Pscx) is installed, it can mask default version of `Expand-Archive` with its own which has different arguments.
Using dotnet function should be safer.

fix: Replace Expand-Archive with System.IO.Compression.ZipFile

---

internal/chezmoi/sourcestate.go
internal/cmd/config.go
internal/cmd/testdata/scripts/external.txtar

I'd like to remove insecure hashes/checksums in the future.
I suspect that these are rarely used, but I don't want to break people who are relying on this feature now, so this PR only adds a warning for now.

feat: Warn about future removal of insecure hashes

---

.github/CODE_OF_CONDUCT.md
assets/chezmoi.io/docs/developer-guide/index.md

feat: Add initial policy on LLM-generated contributions

---

internal/chezmoi/chezmoi.go
internal/chezmoi/externaldiffsystem.go
internal/chezmoi/gitdiffsystem.go
internal/cmd/config.go
internal/cmd/testdata/scripts/externaldiff.txtar
internal/cmd/textconv.go

feat: Use textconv with external diff commands

---

internal/cmd/keepassxctemplatefuncs.go

This fixes fixes the failing lint checks introduced by #4149

fix: apply lint rules for missing keepassxc attributes

---

assets/chezmoi.io/docs/reference/templates/directives.md
go.mod
internal/chezmoi/sourcestate.go
internal/chezmoi/sourcestate_test.go
internal/chezmoi/template.go
internal/chezmoi/template_test.go
internal/cmd/catcmd_test.go
internal/cmd/config.go
internal/cmd/templatefuncs.go

Fixes #3873.
Implements @bradenhilton's suggestion in https://github.com/twpayne/chezmoi/pull/3875#issuecomment-2241866024.
This still needs some work, so this is draft PR.

feat: Add chezmoi:template:format-indent template directive

---

internal/chezmoi/persistentstate_test.go

On Windows, the temporary directory cannot be removed until the files in it are closed.

chore: Fix potential clean-up issue in test

---

internal/cmd/keepassxctemplatefuncs.go
internal/cmd/keepassxctemplatefuncs_test.go

This PR fixes nested groups for keepassxc when run in builtin mode and adds additional tests to assure the functionality.

fix: Correct nested groups for keepassxc builtin mode

---

internal/cmd/addcmd.go
internal/cmd/catconfigcmd.go
internal/cmd/config.go
internal/cmd/doctorcmd.go
internal/cmd/doctorcmd_unix.go
internal/cmd/doctorcmd_windows.go
internal/cmd/editconfigcmd.go
internal/cmd/editconfigtemplatecmd.go
internal/cmd/purgecmd.go
internal/cmd/testdata/scripts/doctor_unix.txtar
internal/cmd/testdata/scripts/issue4181.txtar

Fixes #4181.
This turned out to be a much larger change than I expected. I'm not sure if it's correct yet.

fix: Fix doctor command when --config is specified

---

internal/chezmoi/sourcestate.go
internal/chezmoi/sourcestate_test.go

feat: Support filenames containing # in ignore and remove files

---

internal/chezmoi/sourcestate.go
internal/cmd/readhttpresponse.go

Before this change the HTTP progress bars showed the final request URL after redirects, which makes no sense for the user.
After this change, the HTTP progress bars show the original URL, before redirects, which makes much more sense to the user.

feat: Show original URL in HTTP progress bars

---

internal/cmd/config.go

https://github.com/twpayne/chezmoi/issues/4235

fix(git): run git auto commit hook before ask commit message

---

assets/chezmoi.io/docs/reference/templates/functions/outputList.md
assets/chezmoi.io/mkdocs.yml
internal/cmd/config.go
internal/cmd/templatefuncs.go
internal/cmd/testdata/scripts/templatefuncs.txtar

feat: Add outputList template function

---

assets/chezmoi.io/docs/extra/refresh_on_toggle_dark_light.js
assets/chezmoi.io/mkdocs.yml
uv.lock

Force `mermaid2` to the latest version (11.4.1).
This resulted in a minor bug on rendering where the palette numbering was apparently changed from 1 (light) and 2 (dark) to 0 (light) and 1 (dark). Updated the `refresh_on_toggle_dark_light.js` script to work with either scenario. `document.getElementById("__palette_0")` will return `null` if using 1 indexing, so we swap the dark palette switcher with the light palette switcher and set the dark palette switcher to `__palette_2`.

chore: Upgrade Mermaid version

---

assets/chezmoi.io/docs/reference/commands/ignored.md
assets/chezmoi.io/docs/reference/commands/managed.md
assets/chezmoi.io/docs/reference/commands/unmanaged.md
assets/chezmoi.io/snippets/common-flags/nul-path-separator.md
internal/cmd/cmd.go
internal/cmd/config.go
internal/cmd/ignoredcmd.go
internal/cmd/managedcmd.go
internal/cmd/managedcmd_test.go
internal/cmd/unmanagedcmd.go
internal/cmd/unmanagedcmd_test.go

Refs #4194.
The goal here is to handle filenames with spaces so that a command like
chezmoi managed -0 | xargs -0 tar czf chezmoi-backup-$(date -Iseconds).tar.gz
would work.
PR in progress. Needs tests. Draft for now.

feat: Add -0 flag to ignored, managed, and unmanaged commands

---

assets/chezmoi.io/docs/quick-start.md
assets/chezmoi.io/docs/reference/commands/add.md
assets/chezmoi.io/docs/reference/special-directories/chezmoidata.md
assets/chezmoi.io/docs/reference/special-directories/chezmoiexternals.md
assets/chezmoi.io/docs/reference/special-directories/chezmoiscripts.md
assets/chezmoi.io/docs/reference/special-directories/chezmoitemplates.md
assets/chezmoi.io/docs/reference/special-directories/index.md
assets/chezmoi.io/docs/reference/special-files/chezmoi-format-tmpl.md
assets/chezmoi.io/docs/reference/special-files/chezmoidata-format.md
assets/chezmoi.io/docs/reference/special-files/chezmoiexternal-format.md
assets/chezmoi.io/docs/reference/special-files/chezmoiignore.md
assets/chezmoi.io/docs/reference/special-files/chezmoiversion.md
assets/chezmoi.io/docs/reference/special-files/index.md
assets/chezmoi.io/docs/reference/templates/hcp-vault-secrets-functions/hcpVaultSecret.md
assets/chezmoi.io/docs/reference/templates/hcp-vault-secrets-functions/hcpVaultSecretJson.md
assets/chezmoi.io/docs/reference/templates/hcp-vault-secrets-functions/index.md
assets/chezmoi.io/docs/user-guide/password-managers/hcp-vault-secrets.md
assets/chezmoi.io/docs/user-guide/password-managers/index.md
assets/chezmoi.io/mkdocs.yml

There are a few changes here:
- The index files are now _partial_ documentation for the files (blurb only), but more importantly express the processing order.
- All of the special directories now explicitly end with `/` in the documentation to be clear we are always referring to the directory form. I have not updated this in all locations.
- The external and data files and directories now cross-link explicitly.
- Since I expanded the `data` details, I felt it was worth being more explicit about what is permitted in the config file template used with `chezmoi init`. After trying to write a few non-confusing sentences, I gave up and fell back to a table.
- Added an example of a file with a `#` (see #4210) in `.chezmoiignore`.
- Expanded `.chezmoiroot` and `.chezmoiversion` documentation, …

docs: Extend special files and directories docs

---

.markdownlint-cli2.yaml
assets/.gitignore
internal/cmds/lint-whitespace/main.go

Since #3955 we use `uv` exclusively. This PR removes the last traces of the Python virtual environments that used to be used.

chore: Remove crumbs of Python virtual environment

---

.github/workflows/main.yml

This should eventually fix #4301. As I can't duplicate the problem locally this will be a bit noisy as I push various commits to find the flaky test.

chore: Fix flaky test on macOS GitHub Actions runner

---

assets/chezmoi.io/docs/user-guide/machines/macos.md

This option made my chezmoi fail.
See Homebrew/homebrew-bundle#1630

docs: Remove unnecessary `--no-lock` Brew option

---

assets/chezmoi.io/docs/user-guide/advanced/install-packages-declaratively.md

Hombrew removed the `--no-lock` option in [Commit 98d8ad7 ](https://github.com/Homebrew/homebrew-bundle/commit/98d8ad7ddcca7e7b700cd496207d51fa042c0b00)

Update doc on declarative package installation

---

.golangci.yml

This PR removes redundant `typecheck` from the `linters.enable` list.
`typecheck` is not a linter and it doesn't perform any analysis. It's just a way to identify, parse, and display compiling errors and some linter errors.
More info:
- https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors
- https://golangci-lint.run/welcome/faq/#why-is-it-not-possible-to-skipignore-typecheck-errors

chore: Remove typecheck linter

---

assets/scripts/install-local-bin.sh
assets/scripts/install.sh
internal/cmds/generate-install.sh/install.sh.tmpl

As the install script also detects the version of glibc on Linux, this makes it clear when the version refers to chezmoi's version.

chore: Improve info message in install script

---

assets/chezmoi.io/docs/docs.go
internal/cmd/license.gen.go
internal/cmd/licensecmd.go
internal/cmds/generate-license/license.go.tmpl
internal/cmds/generate-license/main.go
main.go

This avoids linking github.com/charmbracelet/glamour and its dependencies into the binary, which saves another 7MB.
Refs #4356.

chore: Pre-render license

---

internal/chezmoibubbles/multichoiceinputmodel.go

The default behavior from the gum multi-selection example when nothing is selected and we submit, is that the currently selected entry will be added to selection. In my eyes, this is counter intuitive, because if I want explicitly deselect an entry, it should not be submitted.
I want to use promptMultichoice as a "profile" where I can select which package-types (common, desktop, study, etc) i want to install. My config had a promptBool at the end of init asking if I wanted to do "manual" setup so don't install any packages. With the new promptMultichoice, I wanted to refactor and set manualSetup to true, wenn no package profiles are selected, sadly this didn't work because of the above mentioned behavior. 
If any more info is needed for this to merge, i'd be happy to provide.
Cheers

fix: remove default submission when nothing is selected during promptMultichoice

---

assets/chezmoi.io/docs/user-guide/password-managers/keepassxc.md

Fix minor reference link issue in KeePassXC password manager guide.
Currently looks like this on the docs site:
and GitHub Markdown:

docs: Fix reference to KeePassXC link

---

internal/cmd/config.go

fix: Don't invoke pager with shell on Windows

---

go.mod
go.sum

Refs #4353.
Refs https://github.com/gopasspw/gopass/issues/3132.
Refs https://github.com/gopasspw/gopass/pull/3133.
This reduces chezmoi's startup time by about 25ms.
When gopass makes a new release, this replacement can be deleted and the github.com/twpayne/zxcvbn-go repo can be deleted.

chore: Lazily initialize expensive dependency

---

assets/chezmoi.io/docs/user-guide/setup.md

correct the usage of execute-template with the prompt string in the user guide setup.
according to this issue https://github.com/twpayne/chezmoi/issues/3834#issuecomment-2201211679

docs: correct the usage of execute-template with the prompt string in the user guide setup

---

assets/chezmoi.io/docs/user-guide/machines/general.md

For newer M-series MacBooks, the `hw.data` reports strings of the type "Mac15,6" so it can no longer be used to determine if the Mac is a MacBook or not.  This change just switches to using the `system_profiler` output (in particular the `SPHardwareDataType`) to find the Macbook string.
Not a major or earth shattering change - but just to make sure the examples work as expected.

docs: Fix chassis detection for newer MacBooks

---

go.mod
go.sum
main.go

X.509 fallback roots are only needed on systems that do not have any CA certificates installed. This is likely very few, and costs everyone 8ms on every start up, so remove it.
Refs #4353.
Refs https://github.com/golang/go/issues/73691.

feat: Remove X.509 fallback roots

---

assets/chezmoi.io/docs/user-guide/tools/diff.md
internal/chezmoi/externaldiffsystem.go
internal/cmd/testdata/scripts/issue4454.txtar

Fixes #4454.
Draft PR because I would like to add tests for this.

fix: Fix ignoring exit code 1 from external diff commands for non-files

---

assets/chezmoi.io/docs/reference/target-types.md
assets/chezmoi.io/docs/user-guide/manage-different-types-of-file.md

I found that the documentation of the `modify_` target type [in the reference](https://www.chezmoi.io/reference/target-types/#modify-file) is a bit harder to comprehend and inconsistent with what is described [in the user guide](https://www.chezmoi.io/user-guide/manage-different-types-of-file/#manage-part-but-not-all-of-a-file) ("contains a line with the text `chezmoi:modify-template`" has a very different meaning from "containing the string").
This commit replaces the current explanation in the reference with the one that is in the user guide.

docs: Clarify `modify_` documentation

---

internal/chezmoi/targetstateentry.go
internal/cmd/testdata/scripts/issue4496.txtar

fix: Preserve, don't delete, whitespace-only files in external archives

---

assets/chezmoi.io/docs/reference/special-files/chezmoiexternal-format.md

I have created this PR based on feedback provided in: https://github.com/twpayne/chezmoi/issues/4497.
The intention of the PR to provide a clarifying example of how different archives can either include or not include a leading `./` in the file path within an archive.  The example shows two different packages which have differing paths.  Using the archive tooling you can see the correct path for each file.

docs: Add info about file paths for archive-file externals

---

assets/chezmoi.io/docs/reference/templates/functions/getRedirectedURL.md
assets/chezmoi.io/mkdocs.yml
internal/cmd/config.go
internal/cmd/templatefuncs.go
internal/cmd/templatefuncs_test.go

This function will allow me to drop the dependency on `curl` and `git` in my chezmoi templates, making them more portable and quicker to execute.
See the documentation for example uses of such function.
~I did not find any Go library that does this (like [Rust](https://docs.rs/follow-redirects/latest/follow_redirects/) or [JavaScript](https://www.npmjs.com/package/follow-redirects)), so I tried to keep the implementation simple.~ EDIT: this leverages [`net/http`'s redirection mechanism](https://cs.opensource.google/go/go/+/refs/tags/go1.24.4:src/net/http/client.go;l=456).
Disclaimer: I used Claude Sonnet 4 through GitHub Copilot to help me build this PR.

feat: Add `getRedirectedURL` template function

---

internal/chezmoi/abspath.go

Fixes https://github.com/twpayne/chezmoi/issues/4522
The method `AbsPath.JoinString` eventually calls `path.Join`, which strips the leading `\\` from UNC paths. In this case, `AbsPath.JoinString` is invoked here:
https://github.com/twpayne/chezmoi/blob/5188a2e950a2c36aeb5d1c7ae8059989e2b3e276/internal/chezmoi/system.go#L229

fix: Use filepath.Join() to join abspath

---

assets/chezmoi.io/docs/reference/configuration-file/variables.md.tmpl
assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
internal/cmds/execute-template/main.go
internal/cmds/execute-template/main_test.go

This PR changes the format of the configuration variables reference page from a large table (with one row per variable) to a hierarchy of sections (with one section per variable).
This permits directly linking directly to individual configuration variable (which should eventually improve the usability of the docs) and adding expanded variable descriptions (which should also help users).
I propose to add direct links to referenced configuration variables in a follow-up PR.
Requesting review from @halostatue because he's made many excellent contributions to chezmoi's documentation already and has direct experience of all the relevant tools.

docs: Refactor configuration variables reference page

---

internal/cmd/testdata/scripts/issue4479.txtar

If Git is not found in `$PATH`, the test looks like it should be skipped with the message 'git not found in $PATH'. Instead, the test fails with:
```go
[   45s]         testscript.go:584: > [!exec:git] 'skip git not found in $PATH'
[   45s]             FAIL: testdata/scripts/issue4479.txtar:1: unknown command "skip git not found in $PATH"
```

fix: Fix bad skip instruction in test script issue4479 

---

assets/chezmoi.io/docs/reference/commands/edit.md
internal/cmd/doctorcmd.go
internal/cmd/doctorcmd_unix.go
internal/cmd/doctorcmd_windows.go

This fixes #4587 
I had a look at adding test scripts, but the setup is pretty complicated:
- You need a tmpfs filesystem to set tempDir to.
- It needs to be a different tmpfs from the one the source dir potentially is in (the testscripts seem to create temporary home dirs in /tmp so you cannot use /tmp)
- Creating tmpfs needs root rights (`mount -t tmpfs tmpfs <PATH_TO_MOUNT_POINT>`), so we cannot do that ad-hoc
For my system, I can just set `tempDir` to `/run/user/1000` and test it that way, but that is very my-system-specific. There is also not really a way to check this and skip the test if you don't have a tmpfs at hand -> I don't feel comfortable just creating a test that works for me.

Watch hardlink dependency

---

assets/chezmoi.io/docs/reference/commands/generate.md
assets/chezmoi.io/docs/reference/commands/podman.md
assets/chezmoi.io/docs/reference/commands/ssh.md
assets/chezmoi.io/mkdocs.yml
assets/scripts/install-local-bin.sh
assets/scripts/install.sh
assets/templates/install-init-shell.sh.tmpl
assets/templates/templates.go
internal/chezmoi/sourcestate.go
internal/cmd/config.go
internal/cmd/generatecmd.go
internal/cmd/helps.gen.go
internal/cmd/podmancmd.go
internal/cmd/sshcmd.go
internal/cmd/templatefuncs.go
internal/cmds/generate-install.sh/install.sh.tmpl

Fixes #1410.
Fixes #3676.
This is a draft PR, but basically allows you to connect to a remote machine or container and get your shell with your dotfiles installed all in a single command:
```bash
chezmoi podman run $IMAGE_ID $GITHUB_USERNAME
chezmoi podman exec $CONTAINER_ID $GITHUB_USERNAME
chezmoi ssh $HOSTNAME $GITHUB_USERNAME
```
This means, that, for example, I can test my dotfiles in a new, Ubuntu container with:
```bash
chezmoi podman run ubuntu:latest twpayne
```
Or, if I want to login to some host and have my shell and my dotfiles, I can do:
```bash
chezmoi ssh hostname twpayne
```
**Please be really careful with the `chezmoi ssh` command**. This will overwrite your dotfiles in the machine you SSH into, and may do other damage to the target machine. Please, only use it on …

feat: Add `podman` and `ssh` commands

---

.github/workflows/main.yml

With the startup time improvements, sharding is no longer strictly needed.

chore: Un-shard tests on GitHub Actions

---

internal/chezmoi/actualstateentry.go
internal/chezmoi/archive.go
internal/chezmoi/archivereadersystem.go
internal/chezmoi/autotemplate.go
internal/chezmoi/compression.go
internal/chezmoi/diff.go
internal/chezmoi/dumpsystem.go
internal/chezmoi/dumpsystem_test.go
internal/chezmoi/errors.go
internal/chezmoi/gitdiffsystem.go
internal/chezmoi/gitdiffsystem_test.go
internal/chezmoi/glob.go
internal/chezmoi/mode.go
internal/chezmoi/nullsystem.go
internal/chezmoi/patternset.go
internal/chezmoi/patternset_test.go
internal/chezmoi/readonlysystem.go
internal/chezmoi/relpath.go
internal/chezmoi/sourcestate.go
internal/chezmoi/sourcestate_test.go
internal/chezmoi/sourcestateentry.go
internal/chezmoi/sourcestatetreenode.go
internal/chezmoi/sourcestatetreenode_test.go
internal/chezmoi/system.go
internal/chezmoi/targetstateentry.go
internal/chezmoi/tarwritersystem.go
internal/chezmoi/zipwritersystem.go
internal/cmd/dumpcmd.go

Refs #4628.
The goal of this PR is to make https://pkg.go.dev/chezmoi.io/chezmoi/internal/chezmoi more complete.
There are no functional changes. Only internal changes.
chezmoi has a bunch of internal packages that cannot be imported outside chezmoi. These internal packages currently have non-exported types and functions, but there is no point in not exporting these when the package is internal.
This PR exports several types and methods, which means that they will be now be documented on https://pkg.go.dev/chezmoi.io/chezmoi/internal/chezmoi, while still remaining internal to the project.

chore: Better internal docs
