twpayne/chezmoi

README.md
The template as presented would result in an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/twpayne/chezmoi/20)
=> Fix template conditional in readme

README.md, lib/chezmoi/any_actuator.go, lib/chezmoi/chezmoi.go, lib/chezmoi/chezmoi_test.go, lib/chezmoi/fs_actuator.go, lib/chezmoi/logging_actuator.go
This PR factors out a few structs to avoid returning a large number of values from source name parsing functions.
=> Refactor source name parsing and generation

README.md, cmd/add_test.go, lib/chezmoi/actuator.go, lib/chezmoi/any_actuator.go, lib/chezmoi/chezmoi.go, lib/chezmoi/chezmoi_test.go, lib/chezmoi/fs_actuator.go, lib/chezmoi/logging_actuator.go, lib/chezmoi/null_actuator.go
This PR adds symlink support. See the changes to `README.md` for more details.
=> Add symlink support, fixes #17

cmd/add.go, cmd/apply.go, cmd/cat.go, cmd/cd.go, cmd/chattr.go, cmd/cmd.go, cmd/cmd_test.go, cmd/diff.go, cmd/dump.go, cmd/edit.go, cmd/forget.go, cmd/keyring.go, cmd/keyring_get.go, cmd/keyring_set.go, cmd/lastpass.go, cmd/remove.go, cmd/root.go, cmd/source.go, cmd/verify.go, cmd/version.go, lib/chezmoi/chezmoi.go, lib/chezmoi/chezmoi_test.go, lib/chezmoi/fs_actuator.go, lib/chezmoi/logging_actuator.go, lib/chezmoi/null_actuator.go
Apart from fixing a bug in the `remove` command, there should be no user-visible changes.
=> Internal refactor

cmd/cmd.go, cmd/edit.go, go.mod, go.sum
Use `vfs.ReadOnlyFS` to ensure all changes are made via an `Actuator`.
=> Read-only protection

README.md, cmd/cmd.go, cmd/import.go, lib/chezmoi/chezmoi.go
See the changes to `README.md` for explanation.
=> Add import command

cmd/root.go
=> Restore default source VCS command

cmd/config.go, cmd/pass.go
As discussed in https://github.com/twpayne/chezmoi/issues/133
For now, this only takes the first line of output from `pass` (the same behavior as `pass -c`).
Thanks for chezmoi, very cool project!
=> Add support for pass

README.md
=> Fix template in example, fixes #161

README.md, cmd/config.go, cmd/init.go, cmd/init_test.go
This is #174 but without a typo-fix commit that conflicted with `master`.
=> Init command

README.md
Good day, as per https://github.com/twpayne/chezmoi/issues/149 I am submitting a PR to add git init instructions on a fresh install for the README file.
Thank you in advance.
=> Add first run git init instructions to README

scripts/stow-to-chezmoi.sh
=> Add stow-to-chezmoi.sh migration script

scripts/stow-to-chezmoi.sh
I found some cases where my dotfiles on another machine caused issues. So, more robust!
=> fix: several plausible failure modes for the script during routine run

cmd/doctor.go
=> Add suspicious files check

cmd/config.go, cmd/diff.go, cmd/edit.go, cmd/verify.go, lib/chezmoi/null_mutator.go
Reverts #196 and implements the fix described in https://github.com/twpayne/chezmoi/pull/196#issuecomment-460022568.
=> Fix diff command

lib/chezmoi/fs_mutator.go
Refs https://github.com/google/renameio/issues/13.
=> Use renameio correctly across multiple filesystems, fixes #197

cmd/os_release.go, cmd/os_release_test.go
=> Accomodate blank lines and comments in /etc/os-release

README.md, cmd/add.go, cmd/config.go, go.mod, go.sum, lib/chezmoi/chezmoi.go, lib/chezmoi/chezmoi_test.go, lib/chezmoi/file.go, lib/chezmoi/file_test.go, lib/chezmoi/target_state.go, lib/chezmoi/target_state_test.go
Fixes #218.
There are still a couple of rough edges, but it basically works. I'll open issues for these.
cc @jgoguen
=> Add gpg encryption

cmd/completion.go
Made a pass at implementing https://github.com/twpayne/chezmoi/issues/10
=> Add bash & zsh completion

cmd/chattr.go, cmd/edit.go, lib/chezmoi/target_state.go
=> Improve encryption support

HOW-TO.md, lib/chezmoi/pattern_set.go, lib/chezmoi/pattern_set_test.go, lib/chezmoi/target_state.go, lib/chezmoi/target_state_test.go
=> Add excluded ignores

README.md
This is @chrisshyi's commit from #268 rebased on `master`.
=> Fixed link to quick start guide

.goreleaser.yaml, cmd/config.go, cmd/root.go, cmd/upgrade.go, docs/HOWTO.md, docs/REFERENCE.md, lib/chezmoi/targetstate.go, lib/chezmoi/targetstate_test.go
=> Add minimum version check and document special files

Makefile, docs/INSTALL.md
=> Mark snap releases as stable

cmd/doctor.go, cmd/root.go
=> Add doctor version check

go.mod, go.sum
Thanks to @bakito in https://github.com/twpayne/go-difflib/pull/2.
=> Use latest go-difflib with improved colors

cmd/init.go, cmd/init_test.go
=> Make default data available in config file templates

cmd/apply_test.go, docs/REFERENCE.md, lib/chezmoi/targetstate.go, lib/chezmoi/targetstate_test.go
=> Add common templates

README.md, cmd/chattr.go, cmd/config.go, cmd/edit.go, docs/CHANGES.md, docs/HOWTO.md, docs/REFERENCE.md, lib/chezmoi/chezmoi_test.go, lib/chezmoi/gpg.go, lib/chezmoi/targetstate.go, lib/chezmoi/targetstate_test.go
=> Add symmetric encryption

cmd/upgrade.go
=> Exec new version after upgrade

cmd/add.go, cmd/add_test.go, cmd/helps.gen.go, docs/HOWTO.md, docs/REFERENCE.md, lib/chezmoi/targetstate.go
This assists migration from symlink-based systems.
=> Add --follow option to add command

cmd/secretbitwarden.go, cmd/secretgeneric.go, cmd/secretlastpass.go, cmd/secretonepassword.go, cmd/secretvault.go
This improves the debugability of template errors (#316).
=> Pass through stderr output from secret commands

cmd/helps.gen.go, docs/REFERENCE.md
Supersedes #342. Authored by @markstos.
=> Document that fish completion exists in REFERENCE.md

.goreleaser.yaml, goreleaser/goreleaser.yaml.tmpl
=> Install zsh completions

cmd/root.go, docs/HOWTO.md
=> Initialize persistent state even when no config file exists

cmd/edit.go, cmd/helps.gen.go, docs/INSTALL.md, docs/REFERENCE.md
This addresses the major comments in #366. There's some missing functionality, I'll open an issue for those.
=> Fix issue 336 comments

cmd/add.go, cmd/archive.go, cmd/cat.go, cmd/chattr.go, cmd/config.go, cmd/data.go, cmd/dump.go, cmd/edit.go, cmd/forget.go, cmd/import.go, cmd/merge.go, cmd/remove.go, cmd/sourcepath.go, cmd/unmanaged.go, lib/chezmoi/targetstate.go, lib/chezmoi/targetstate_test.go
=> Don't execute templates when editing source state

cmd/init.go, cmd/secretbitwarden.go, cmd/secretgeneric.go, cmd/secretkeepassxc.go, cmd/secretkeyring.go, cmd/secretlastpass.go, cmd/secretonepassword.go, cmd/secretpass.go, cmd/secretvault.go, lib/chezmoi/chezmoi.go, lib/chezmoi/chezmoi_test.go, lib/chezmoi/targetstate.go
=> Fix template error messages

cmd/cmd_test.go, cmd/config.go, cmd/helps.gen.go, cmd/remove.go, completions/chezmoi-completion.bash, completions/chezmoi.fish, docs/REFERENCE.md
=> Make remove command prompt by default

go.mod, go.sum
=> Use latest modules for Windows support

cmd/noupgrade.go, cmd/umask.go, cmd/upgrade.go
=> No upgrade on windows

.github/ISSUE_TEMPLATE/01_bug_report.md
@twpayne Hey Tom, great project! 👌
Been using it for a few months now, and I've been recommending it to countless people.
Figured I'd help you out close some of these tickets  🤝, starting with the easiest thing first. I conjured up this **Issue Template for Bug Reporting**, as I've seen some new issues come in.
Feel free to edit as you please. 🙏
Closes https://github.com/twpayne/chezmoi/issues/315
=> Add ‘Bug Report’ Issue Template

cmd/add.go, cmd/add_test.go, cmd/helps.gen.go, completions/chezmoi-completion.bash, completions/chezmoi.fish, docs/REFERENCE.md, lib/chezmoi/targetstate.go
This is @15cm's work from #394 rebased and squashed into a single commit and branch. Fixes #393. Thanks @15cm!
=> Disable autotemplate by default

cmd/secretkeepassxc.go, docs/HOWTO.md, docs/REFERENCE.md
=> Add keepassxcAttribute template function

cmd/edit.go
=> Execute templates after editing

go.mod, go.sum
=> Use latest version of github.com/Masterminds/sprig

cmd/apply.go, cmd/apply_test.go, cmd/cmd_test.go, cmd/config.go, cmd/config_test.go, cmd/diff.go, cmd/diff_posix_test.go, cmd/import_test.go, cmd/init.go, cmd/root.go, cmd/update.go, cmd/verify.go, lib/chezmoi/boltpersistentstate.go, lib/chezmoi/boltpersistentstate_test.go, lib/chezmoi/chezmoi.go
=> Only lock persistent state when writes are needed

docs/FAQ.md
=> Add FAQ entry on source/target filename bijection

cmd/root.go
=> Disable source state private check on Windows

cmd/add.go, cmd/config.go, cmd/config_test.go, cmd/edit.go, cmd/forget.go, cmd/gitvcs.go, cmd/hgvcs.go, cmd/init_test.go, cmd/remove.go, cmd/util_posix_test.go, cmd/util_windows_test.go, cmd/vcs.go, docs/HOWTO.md, docs/REFERENCE.md, go.mod, go.sum, internal/git/status.go, internal/git/status_test.go, templates/COMMIT_MESSAGE.tmpl
This is a draft PR working towards fixing #413.
cc @lewisacidic
=> Add autocommit and autopush

docs/CONTRIBUTING.md
=> Fix typo i make every day, and therefore see everywhere.

docs/FAQ.md
=> Add FAQ entry on running a command when a file changes

docs/HOWTO.md
=> Add how to import Oh My Zsh documentation

cmd/secretonepassword.go, docs/HOWTO.md, docs/REFERENCE.md
Fixes #501.
@rcorrear are you able to test this? I'm not a 1Password user, but can do some tests late this evening otherwise.
=> Add onepasswordDocument template function

cmd/add.go
=> Warn when skipping add of ignored files

.github/workflows/main.yml
=> Include generate step in release builds

cmd/add_test.go, cmd/cmd_test.go, cmd/config.go, cmd/root.go, go.mod, go.sum, internal/chezmoi/private.go, internal/chezmoi/private_posix.go, internal/chezmoi/private_windows.go, internal/chezmoi/targetstate.go
=> Preserve but don't enforce private on Windows

internal/chezmoi/debugmutator.go, internal/chezmoi/verbosemutator.go
=> Better diff logging

cmd/add_test.go, internal/chezmoi/targetstate.go
=> Treat adding an empty file without --empty as remove

docs/INSTALL.md
As [suggested by @tsaarni](https://github.com/twpayne/chezmoi/issues/408#issuecomment-569406281) in #408. Thanks @tsaarni!
=> Use more reliable install-from-source method

docs/HOWTO.md
=> Fix use of autotemplate in how-to doc

.github/workflows/main.yml, .golangci.yml, .goreleaser.yaml, Makefile
=> Release improvements

cmd/config.go, cmd/config_test.go, cmd/root.go, docs/HOWTO.md, docs/REFERENCE.md
=> Validate variable names in config data

cmd/config.go, cmd/data.go
=> Don't compute full target state in data command

cmd/add.go, cmd/apply.go, cmd/cat.go, cmd/chattr.go, cmd/completion.go, cmd/diff.go, cmd/dump.go, cmd/edit.go, cmd/forget.go, cmd/import.go, cmd/merge.go, cmd/remove.go, cmd/root.go, cmd/sourcepath.go, cmd/verify.go, completions/chezmoi.fish, completions/chezmoi.zsh
=> Add zsh completion for positional arguments

internal/chezmoi/targetstate.go
=> When looking for an entry, return an error if it does not exist

cmd/apply_test.go, internal/chezmoi/symlink.go
=> If a symlink is empty, remove the target

cmd/init.go, cmd/init_test.go
=> Make all template functions available in config file template

chezmoi.io/content/_index.md, internal/generate-chezmoi.io-content-docs/main.go
Fixes #614 
Thanks also to @stapelberg who also reported this privately.
=> Fix links on chezmoi.io

cmd/config.go, cmd/data_linux.go, cmd/data_linux_test.go
=> Make reading /proc/sys/kernel more tolerant of errors

cmd/cgo.go, cmd/config.go, cmd/nocgo.go
=> Only set group value if user.LookupGroupId succeeds

.github/workflows/main.yml, .goreleaser.yaml, Makefile, cmd/doctor.go, cmd/root.go, cmd/upgrade.go, main.go
=> Fix version

cmd/config.go, cmd/config_test.go, cmd/docs.gen.go, docs/HOWTO.md, docs/REFERENCE.md
Fixes #655.
@ihommani what do you think?
=> Include non-hermetic text functions from Sprig

cmd/docs.gen.go, docs/HOWTO.md
=> Add separate config files how-to entry

cmd/docs.gen.go, cmd/helps.gen.go, cmd/managed.go, cmd/managed_test.go, completions/chezmoi-completion.bash, completions/chezmoi.fish, completions/chezmoi.zsh, docs/FAQ.md, docs/REFERENCE.md
=> Add managed command

cmd/add_test.go
=> Add test for adding empty directory without recursion

cmd/add.go, cmd/add_test.go, cmd/docs.gen.go, docs/HOWTO.md, internal/chezmoi/targetstate.go
=> Create .keep files when adding directories non-recursively

cmd/config.go, cmd/root.go
=> Add warnings for features to be deprecated in v2

chezmoi.io/.gitignore, chezmoi.io/content/docs/menu/index.md, cmd/docs.gen.go, docs/MEDIA.md
=> Fix media page

cmd/docs.gen.go, docs/REFERENCE.md, go.mod, go.sum, internal/chezmoi/patternset.go, internal/chezmoi/patternset_test.go
=> Use doublestar.Match for path matching

cmd/docs.gen.go, docs/FAQ.md, docs/REFERENCE.md
=> Improve umask docs

docs/INSTALL.md
https://github.com/Homebrew/homebrew-core/commit/caa44f8aac7347b1846df70e66a73044123b4d62
this change will eventually be mirrored to Linuxbrew, but I'm not 100% sure of that process
=> install from homebrew-core

cmd/docs.gen.go, cmd/helps.gen.go, cmd/upgrade.go, completions/chezmoi.zsh, docs/REFERENCE.md
=> Don't attempt to upgrade dev versions without --force flag

internal/chezmoi/dir.go, internal/chezmoi/targetstate.go
Found with https://github.com/mvdan/gofumpt/pull/62 :)
=> Compact type declarations

cmd/secretgeneric.go
=> Make secret template function return a string, not a []byte

cmd/chattr.go, cmd/config_test.go, internal/git/status.go, internal/git/status_test.go
=> Fix git status parser and enable autocommit and autopush for attr changes

cmd/docs.gen.go, docs/HOWTO.md
=> Improve how to for tracking externally modified files

cmd/cd.go, cmd/docs.gen.go, cmd/helps.gen.go, docs/REFERENCE.md, testdata/scripts/cd.txt
=> Add cd.args configuration variable

main_test.go, testdata/scripts/archive.txt, testdata/scripts/cat.txt, testdata/scripts/cd.txt, testdata/scripts/cd_windows.txt, testdata/scripts/editconfig.txt, testdata/scripts/forget.txt, testdata/scripts/init.txt, testdata/scripts/verify.txt
Also enable as many of the test scripts as possible on Windows and update them as needed.
=> Add a Windows setup implementation for testscript

testdata/scripts/secretgeneric.txt, testdata/scripts/secretgopass.txt, testdata/scripts/secretlastpass.txt, testdata/scripts/secretpass.txt
=> Add Windows implementations for the secret testscripts.

cmd/diff.go, cmd/diff_test.go, internal/chezmoi/gitdiffmutator.go
=> Fix git diff format when file is absent from target dir

cmd/docs.gen.go, docs/HOWTO.md
The current link is broken, this fixes it.
=> gopass url needs www.

README.md, chezmoi.io/content/_index.md, cmd/docs.gen.go, docs/HOWTO.md
=> Improve documentation

cmd/docs.gen.go, docs/FAQ.md
=> Enlarge FAQ on source state representation

cmd/docs.gen.go, docs/HOWTO.md, docs/REFERENCE.md
=> Fix follow documentation

cmd/secretpass.go, testdata/scripts/secretpass.txt
=> Ensure pass is unlocked before requesting secrets

cmd/secretbitwarden.go, cmd/secretgeneric.go, cmd/secretgopass.go, cmd/secretkeepassxc.go, cmd/secretkeyring.go, cmd/secretlastpass.go, cmd/secretonepassword.go, cmd/secretpass.go, cmd/secretvault.go
As first spotted and fixed by @zb140 in https://github.com/twpayne/chezmoi/pull/771.
=> Reduce verbosity in secret template error messages

internal/chezmoi/targetstate.go, internal/chezmoi/targetstate_test.go, testdata/scripts/executetemplate.txt
Fixed #802 
Thanks to @zb140 for identifying the fix.
=> Allow all functions in .chezmoitemplates

cmd/config.go
I've recently had issues where a stuck chezmoi process kept the lock on the database causing a new run to stall forever. This ensures the user at least get an error instead of an infinite wait.
The 2 seconds are chosen completely arbitrarily :smile:
=> Add timeout when opening bolt database

cmd/config.go
This fixes a couple of problems in #815.
=> Fix persistent state timeout

testdata/scripts/sourcedir.txt
=> Add test for setting source dir in config file

docs/REFERENCE.md
Hey! I'm offering another example in this reference document because it took me a little while to get this syntax correct. Let me know if I got the lingo correct or if it needs an edit.
=> Add example of ignoring a directory

cmd/docs.gen.go, docs/REFERENCE.md
=> Clarify configuration variables

cmd/docs.gen.go, cmd/secretonepassword.go, docs/HOWTO.md, docs/REFERENCE.md, testdata/scripts/secretonepassword.txt
=> Add onepasswordDetailsFields function

cmd/docs.gen.go, docs/QUICKSTART.md
Contributed by @ASDFGamer, replaces #826 and fixes #825.
@ASDFGamer the commit has you as the author, to preserve credit.
=> Added description how to add folders

cmd/chattr.go, completions/chezmoi.zsh
=> Use encrypted, not encrypt, in chattr

cmd/docs.gen.go, docs/INSTALL.md
=> Add Guix installation command

cmd/docs.gen.go, docs/HOWTO.md
- Set `sourceDir` so further calls of `chezmoi` will pick-up the right source directory without need to `--source`.
- Install `chezmoi` to a known binary folder, only if it's not installed already.
- A safer installation script (because of `set -e`).
Closes https://github.com/twpayne/chezmoi/issues/760 and closes https://github.com/twpayne/chezmoi/issues/818.
=> Enhance Codespaces documentation

cmd/config_test.go, cmd/docs.gen.go, cmd/gitvcs.go, cmd/helps.gen.go, cmd/hgvcs.go, cmd/init.go, cmd/vcs.go, completions/chezmoi-completion.bash, completions/chezmoi.zsh, docs/HOWTO.md, docs/REFERENCE.md, testdata/scripts/init.txt
As suggested by @felipecassiors in #855. Fixes #855.
=> Remove init --clone flag and only clone repo if needed

cmd/root.go
=> Remove private check on source directory

README.md, chezmoi.io/Makefile, chezmoi.io/content/_index.md, chezmoi.io/content/docs/menu/index.md, cmd/docs.gen.go, docs/TEMPLATING.md, main.go
=> Add templating doc skeleton

README.md, chezmoi.io/content/_index.md, cmd/config.go, cmd/docs.gen.go, cmd/helps.gen.go, cmd/secretkeyring.go, cmd/secretkeyringget.go, cmd/secretkeyringset.go, completions/chezmoi-completion.bash, completions/chezmoi.zsh, docs/HOWTO.md, docs/REFERENCE.md, go.mod, go.sum
=> Restore keyring support

cmd/docs.gen.go, docs/TEMPLATING.md
This is the documentation I've written so far. It's not yet finished, so you can decide to not put it in master yet.
I'm planning to do a lot more documentation, so let me know what you think of this.
=> Initial templating docs

cmd/docs.gen.go, docs/INSTALL.md
=> Add void linux installation instructions to INSTALL.md

cmd/docs.gen.go, docs/HOWTO.md, docs/REFERENCE.md, docs/TEMPLATING.md
Hi, i've added more templating documentation (and fixed a typo).
In #792 you mentioned a few issues surrounding template documentation. I've addressed the following ones:
- For #774, #787 and #790 I just pointed to the reference in the relevant places.
- #749 I fixed in my last PR
- #722 doesn't need to be documented
- I didn't do anything with #780 yet.
Are there any more  specific things you would like to see in the template documentation? 
I could add some complete examples at the end.
=> Add templating docs on logical operators

cmd/docs.gen.go, cmd/secretbitwarden.go, docs/HOWTO.md, docs/REFERENCE.md, testdata/scripts/bitwarden.txt
=> Add bitwardenFields template function

chezmoi.io/content/_index.md
Fixes #806 again, the fix in #807 was reverted by #898.
=> Fix chezmoi.io links again

cmd/doctor.go, cmd/secretgopass.go, testdata/scripts/gopass.txt, testdata/scripts/secretgopass.txt
=> Use --password option when calling gopass

cmd/docs.gen.go, docs/TEMPLATING.md
Minor typo! This time I updated the generated code too 😄
=> Fix minor typo

cmd/docs.gen.go, docs/REFERENCE.md
=> Minor minor typo

cmd/config.go
=> Allow user and group lookups to fail

assets/scripts/install.sh
=> Fix exit code of install script

chezmoi2/internal/chezmoi/chezmoi_windows.go
=> chezmoi2: Populate fqdnHostname data on Windows

chezmoi2/cmd/applycmd.go, chezmoi2/cmd/cmd.go, chezmoi2/cmd/config.go, chezmoi2/cmd/initcmd.go, chezmoi2/cmd/keepassxctemplatefuncs.go, chezmoi2/cmd/secretkeyringcmd.go, chezmoi2/cmd/terminal.go, chezmoi2/docs/CHANGES.md, chezmoi2/testdata/scripts/apply.txt, chezmoi2/testdata/scripts/keepassxc.txt, chezmoi2/testdata/scripts/scriptonce_unix.txt
This PR will accumulate miscellaneous fixes and clean-ups for chezmoi2.
Refs #989.
=> chezmoi2: Miscellaneous fixes and clean-ups

chezmoi2/main_test.go, chezmoi2/testdata/scripts/edit.txt, chezmoi2/testdata/scripts/scriptonce_windows.txt, chezmoi2/testdata/scripts/scriptorder_windows.txt, chezmoi2/testdata/scripts/scriptsubdir_windows.txt, chezmoi2/testdata/scripts/state_windows.txt
=> chezmoi2: Update the edit testscript for Windows

cmd/docs.gen.go, docs/FAQ.md
As identified by @sersorrel in #994.
Commit credited to @sersorrel.
=> Fix umask format in FAQ

assets/scripts/install.ps1, chezmoi2/cmd/docs.gen.go, cmd/docs.gen.go, docs/INSTALL.md, internal/cmd/lint-whitespace/main.go
=> Add a Powershell install script

.github/workflows/main.yml, .goreleaser.yaml, chezmoi2/cmd/config.go, chezmoi2/completions/chezmoi2-completion.bash, chezmoi2/completions/chezmoi2.fish, chezmoi2/completions/chezmoi2.ps1, chezmoi2/completions/chezmoi2.zsh, chezmoi2/main.go, chezmoi2/testdata/scripts/completion.txt, chezmoi2/testdata/scripts/version.txt, internal/cmd/lint-whitespace/main.go
cc @JustinGrote as you might be modifying the same files at the moment.
=> chezmoi2: Build cleanups

.github/workflows/main.yml, chezmoi2/cmd/config.go, chezmoi2/cmd/reference.gen.go, chezmoi2/docs/REFERENCE.md, cmd/config.go, cmd/docs.gen.go, docs/REFERENCE.md
@JustinGrote what do you think of this approach?
=> Only check minimum version in non-snapshot builds

chezmoi2/cmd/bitwardentemplatefuncs.go, chezmoi2/cmd/config.go, chezmoi2/cmd/reference.gen.go, chezmoi2/docs/REFERENCE.md, chezmoi2/testdata/scripts/bitwarden.txt
In case https://github.com/twpayne/chezmoi/pull/1019 gets accepted and merged, this PR adds the same support for `chezmoi2`. 
For more information, see https://github.com/twpayne/chezmoi/pull/1019
=> Chezmoi2: Add bitwardenAttachment support

chezmoi2/cmd/config.go, chezmoi2/cmd/helps.gen.go, chezmoi2/cmd/initcmd.go, chezmoi2/cmd/reference.gen.go, chezmoi2/docs/REFERENCE.md, chezmoi2/internal/chezmoi/actualstateentry.go, chezmoi2/internal/chezmoi/chezmoi.go, chezmoi2/internal/chezmoi/entrystate.go, chezmoi2/internal/chezmoi/hexbytes.go, chezmoi2/internal/chezmoi/hexbytes_test.go, chezmoi2/internal/chezmoi/lazy.go, chezmoi2/internal/chezmoi/persistentstate.go, chezmoi2/internal/chezmoi/targetstateentry.go, chezmoi2/testdata/scripts/configstate.txt, chezmoi2/testdata/scripts/state_unix.txt, chezmoi2/testdata/scripts/state_windows.txt
=> Warn when config file template has changed

chezmoi2/cmd/executetemplatecmd.go, chezmoi2/cmd/initcmd.go, chezmoi2/internal/chezmoi/recursivemerge.go, chezmoi2/internal/chezmoi/recursivemerge_test.go, chezmoi2/internal/chezmoi/sourcestate.go, chezmoi2/internal/chezmoi/sourcestate_test.go, chezmoi2/testdata/scripts/configstate.txt
=> chezmoi2: Make user data available to config file template

chezmoi2/cmd/addcmd.go, chezmoi2/cmd/chattrcmd.go, chezmoi2/cmd/config.go, chezmoi2/cmd/reference.gen.go, chezmoi2/docs/REFERENCE.md, chezmoi2/internal/chezmoi/ageencryption.go, chezmoi2/internal/chezmoi/attr.go, chezmoi2/internal/chezmoi/attr_test.go, chezmoi2/internal/chezmoi/debugencryption.go, chezmoi2/internal/chezmoi/encryption.go, chezmoi2/internal/chezmoi/encryption_test.go, chezmoi2/internal/chezmoi/gpgencryption.go, chezmoi2/internal/chezmoi/noencryption.go, chezmoi2/internal/chezmoi/sourcerelpath.go, chezmoi2/internal/chezmoi/sourcerelpath_test.go, chezmoi2/internal/chezmoi/sourcestate.go, chezmoi2/main_test.go, chezmoi2/testdata/scripts/age.txt, chezmoi2/testdata/scripts/gpg.txt, chezmoi2/testdata/scripts/gpgencryption.txt
=> chezmoi2: Add optional encrypted suffix

cmd/config.go
=> Fix typo in pre apply function

cmd/config.go, cmd/templatefuncs.go, docs/REFERENCE.md, testdata/scripts/templatefuncs.txt
=> chezmoi2: Add output template function

.golangci.yml, internal/chezmoi/gitdiffsystem.go, testdata/scripts/diff.txt
=> Fix diffs where actual and target types differ

internal/chezmoi/gitdiffsystem.go
This is a follow-up to #1053 that makes the code shorter and more robust.
=> Simplify diff code

.goreleaser.yaml
=> Remove temporary version override

cmd/config.go, docs/CHANGES.md, main_test.go, testdata/scripts/ageencryption.txt, testdata/scripts/gpgencryption.txt
=> Detect encryption if config group set in config file

docs/REFERENCE.md
Documents the ability to use `after`, `before`, and `once` with `chattr` command.
=> Add new attributes to chattr reference documentation.

cmd/editcmd.go, testdata/scripts/gpgencryption.txt
=> Fix editing of encrypted files in subdirectories

Makefile, cmd/noupgradecmd.go
=> Fix noupgrade build tags

.goreleaser.yaml
=> Build libc-specific archives

.github/workflows/main.yml, .goreleaser.yaml, Makefile, assets/scripts/install.sh, docs/CONTRIBUTING.md, internal/cmd/generate-install.sh/install.sh.tmpl
=> Make install script install glibc or musl libc version as appropriate

cmd/config.go, cmd/mergecmd.go, internal/chezmoi/boltpersistentstate.go, internal/chezmoi/boltpersistentstate_test.go, internal/chezmoi/mockpersistentstate.go, internal/chezmoi/mockpersistentstate_test.go
=> Unlock state when running editor or merge command

docs/REFERENCE.md, internal/chezmoi/realsystem.go, testdata/scripts/scriptsubdir_unix.txt, testdata/scripts/scriptsubdir_windows.txt
This tidies up a couple of things from #1100.
=> Tidy up handling of script working directories

cmd/config.go, main_test.go, testdata/scripts/templatedata.txt
=> Make .chezmoi.sourceDir template variable a string

cmd/managedcmd_test.go, internal/chezmoi/actualstateentry.go, internal/chezmoi/lazy.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/targetstateentry.go, internal/chezmoi/targetstateentry_test.go, testdata/scripts/managed.txt
=> Only evaluate target states when needed

internal/chezmoi/path.go
Refs #1124.
Thanks @Flygrounder for spotting and fixing this - the commit credits you as the author.
=> Fix absolute path check

main_test.go, testdata/scripts/gpgencryption_symmetric.txt
=> Add tests for symmetric GPG encryption

internal/chezmoi/sourcerelpath.go, testdata/scripts/import.txt
=> Fix import command when destination already exists

.editorconfig, .github/workflows/main.yml, .goreleaser.yaml, assets/scripts/install.ps1, assets/scripts/install.sh, internal/cmd/generate-install.sh/install.sh.tmpl
Fixes #1136. Refs #1115, #1117, #1123.
=> Fix use of checksums file

assets/scripts/install.sh, internal/cmd/generate-install.sh/install.sh.tmpl
=> Only install glibc/musl-specific binaries when they are available

testdata/scripts/addencrypted.txt
=> Add test for re-adding file with and without --encrypt

docs/REFERENCE.md
Attempting to make script prefix rules more explicit in documentation.
=> Document script prefixes

.github/workflows/main.yml, Makefile, cmd/verifycmd_test.go, internal/chezmoi/dumpsystem_test.go, internal/chezmoi/entrystate.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/targetstateentry.go, internal/chezmoi/targetstateentry_test.go, internal/chezmoi/tarwritersystem_test.go, internal/chezmoi/zipwritersystem_test.go, internal/chezmoitest/chezmoitest.go, internal/chezmoitest/chezmoitest_unix.go, internal/chezmoitest/chezmoitest_windows.go, main_test.go, testdata/scripts/diff.txt, testdata/scripts/dumpjson.txt, testdata/scripts/dumpyaml.txt, testdata/scripts/exclude.txt, testdata/scripts/modify.txt, testdata/scripts/runscriptdir_unix.txt, testdata/scripts/scriptsubdir_unix.txt, testdata/scripts/umask.txt, testdata/scripts/verify.txt
This is a work-in-progress fix for #1066, not ready for merging yet.
=> Store actual umasks in state file

cmd/config.go, cmd/diffcmd_test.go, internal/chezmoi/entrytypeset.go, testdata/scripts/exclude.txt
=> Fix panic when using diff --exclude

docs/REFERENCE.md, docs/TEMPLATING.md
=> Explicitly document need for data in template action

cmd/addcmd.go, cmd/config.go, cmd/terminal.go, cmd/util.go, cmd/util_test.go, internal/chezmoi/sourcestate.go, testdata/scripts/addattributes.txt, testdata/scripts/addencrypted.txt
=> Warn user when removing encrypted, private, or template attributes

internal/chezmoi/chezmoi_unix.go, internal/chezmoi/chezmoi_unix_test.go
=> Don't atempt to use reverse DNS to determine FQDN hostname

assets/scripts/install.ps1
=> Add another method of detecting OS architecture for robustness

cmd/config.go, internal/chezmoi/chezmoi_unix.go, internal/chezmoi/chezmoi_unix_test.go, internal/chezmoi/chezmoi_windows.go
=> Use /etc/hostname to determine hostname, if available

cmd/initcmd.go, main_test.go, testdata/scripts/init.txt
Fixes #1197.
@sheeley is this what you had in mind?
=> Validate generate config before writing it in init command

internal/chezmoi/sourcestate.go, testdata/scripts/edgecases.txt
=> Update last written state when target and actual states are equivalent

docs/REFERENCE.md, internal/chezmoi/sourcestate.go, testdata/scripts/templatedata.txt
=> Add .chezmoi.sourceFile template variable

testdata/scripts/issue-1213.txt
=> Add test for template data in chezmoi init --apply

cmd/executetemplatecmd.go, cmd/initcmd.go, docs/REFERENCE.md, testdata/scripts/templatefuncs.txt
=> Add writeToStdout init template function

docs/REFERENCE.md, docs/TEMPLATING.md
=> Reference .chezmoidata in template data documentation

docs/REFERENCE.md, internal/chezmoi/boltpersistentstate_test.go, internal/chezmoi/dumpsystem_test.go, internal/chezmoi/path.go, internal/chezmoi/realsystem.go, internal/chezmoi/realsystem_test.go, internal/chezmoi/realsystem_unix.go, internal/chezmoi/realsystem_windows.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/targetstateentry_test.go, internal/chezmoi/tarwritersystem_test.go, internal/chezmoi/zipwritersystem_test.go, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/testdata/scripts/script.txt, internal/cmd/testdata/scripts/script_interpreters.txt, internal/cmd/testdata/scripts/script_perl.txt, internal/cmd/testdata/scripts/script_python.txt, internal/cmd/testdata/scripts/script_ruby.txt, internal/cmd/util_unix.go, internal/cmd/util_windows.go
Fixes #1238.
Thanks to @bradenhilton for the most well thought-through enhancement request I've ever seen.
cc @zb140 for Windows expertise (please read #1238).
Not quite ready for merge yet...
=> Allow script interpreters to be configured on Windows

docs/HOWTO.md, docs/REFERENCE.md, internal/chezmoi/ageencryption.go, internal/cmd/main_test.go, internal/cmd/testdata/scripts/addautotemplate.txt, internal/cmd/testdata/scripts/ageencryption_symmetric.txt, internal/cmd/testdata/scripts/configstate.txt, internal/cmd/testdata/scripts/data.txt, internal/cmd/testdata/scripts/exclude.txt, internal/cmd/testdata/scripts/executetemplate.txt, internal/cmd/testdata/scripts/init.txt, internal/cmd/testdata/scripts/symlinks.txt
=> Add support for symmetric encryption with age

docs/HOWTO.md, docs/REFERENCE.md, internal/chezmoi/ageencryption.go
=> Add support for age's passphrase encryption

docs/REFERENCE.md
I confess I didn't test building the site after this change. BTW, thanks for the great tool!
=> Fix typo in REFERENCE.md

docs/REFERENCE.md, internal/chezmoi/boltpersistentstate_test.go, internal/chezmoi/debugsystem.go, internal/chezmoi/dryrunsystem.go, internal/chezmoi/dumpsystem.go, internal/chezmoi/dumpsystem_test.go, internal/chezmoi/gitdiffsystem.go, internal/chezmoi/interpreter.go, internal/chezmoi/realsystem.go, internal/chezmoi/realsystem_test.go, internal/chezmoi/realsystem_unix.go, internal/chezmoi/realsystem_windows.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/system.go, internal/chezmoi/targetstateentry.go, internal/chezmoi/targetstateentry_test.go, internal/chezmoi/tarwritersystem.go, internal/chezmoi/tarwritersystem_test.go, internal/chezmoi/zipwritersystem.go, internal/chezmoi/zipwritersystem_test.go, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/testdata/scripts/modify_python_windows.txt, internal/cmd/testdata/scripts/modify_unix.txt, internal/cmd/testdata/scripts/modify_windows.txt, internal/cmd/util_unix.go, internal/cmd/util_windows.go
=> Enable `modify_` scripts on Windows

README.md, chezmoi.io/content/_index.md
I think this is the last of #459 😢
=> Remove references to non-git VCSes

internal/chezmoi/chezmoi_unix.go, internal/chezmoi/chezmoi_unix_test.go
=> Prioritize /etc/hosts over /etc/hostname for FQDN hostname

docs/HOWTO.md, docs/REFERENCE.md
=> :memo: Update docs so that oh-my-zsh tarball goes to TMPDIR instead of HOME

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/gopasstemplatefuncs.go, internal/cmd/passtemplatefuncs.go, internal/cmd/testdata/scripts/gopass.txt, internal/cmd/testdata/scripts/pass.txt
=> Add gopassRaw and passRaw template functions

docs/REFERENCE.md, internal/cmd/onepasswordtemplatefuncs.go
=> boom, adding support for account

docs/FAQ.md, docs/REFERENCE.md, internal/chezmoi/attr.go, internal/chezmoi/attr_test.go, internal/chezmoi/chezmoi.go, internal/cmd/testdata/scripts/literal.txt
=> Make all filenames representable in the source state

docs/REFERENCE.md, internal/cmd/onepasswordtemplatefuncs.go, internal/cmds/lint-whitespace/main.go
=> Misc cleanups

docs/HOWTO.md
=> Update doc on how to migrate away from chezmoi

internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/scriptinterpreterstemplate.txt
=> Use script extension to determine interpreter

docs/HOWTO.md
Spotted by @Gellardo - shamelessly plucked from [his branch](https://github.com/Gellardo/chezmoi/tree/patch-1), maintaining author credit.
=> Fix config file code snippet in HOWTO

internal/chezmoi/path.go
=> Fix panic when destination directory is /

internal/chezmoi/data.go, internal/chezmoi/data_test.go, internal/cmd/config.go, internal/cmd/doctorcmd.go, internal/cmd/upgradecmd_unix.go, internal/cmd/util.go, internal/cmd/util_test.go
=> Make .chezmoi.osRelease template variable more generic

internal/chezmoi/sourcestate.go, internal/chezmoi/system.go, internal/cmd/testdata/scripts/edgecases.txt, internal/cmd/unmanagedcmd.go
=> Allow source directory to be a symlink

internal/cmd/initcmd.go
I was unable to clone a private chezmoi repo when bootstrapping on a system that did not have git installed
(https://github.com/twpayne/chezmoi/discussions/1310)
This commit allows this, by allowing the user to enter their username/
password at the command prompt.
=> allow entering username/password when using builtin git clone

docs/REFERENCE.md, internal/cmd/initcmd.go
=> Tidy up password handling

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/mergecmd.go, internal/cmd/testdata/scripts/merge_unix.txt
=> Make order of arguments to merge command configurable

internal/cmd/autobool.go, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/diffcmd.go, internal/cmd/initcmd.go, internal/cmd/testdata/scripts/config.txt, internal/cmd/updatecmd.go
=> Fix crash when color was set to auto in config file

docs/REFERENCE.md, internal/chezmoi/debugsystem.go, internal/chezmoi/dryrunsystem.go, internal/chezmoi/externaldiffsystem.go, internal/chezmoi/gitdiffsystem.go, internal/chezmoi/readonlysystem.go, internal/chezmoi/realsystem.go, internal/chezmoi/system.go, internal/cmd/config.go, internal/cmd/diffcmd.go, internal/cmd/mergecmd.go, internal/cmd/testdata/scripts/diff_unix.txt
Fixes #793. Work in progress. Much more work to be done.
=> Add configurable diff command

docs/FAQ.md, docs/REFERENCE.md, internal/chezmoi/mode.go, internal/chezmoi/sourcestate.go, internal/cmd/addcmd.go, internal/cmd/config.go, internal/cmd/main_test.go, internal/cmd/testdata/scripts/modesymlink.txt
=> Add symlink mode

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/datacmd.go, internal/cmd/dataformat.go, internal/cmd/dumpcmd.go, internal/cmd/statecmd.go, internal/cmd/testdata/scripts/config.txt
=> Add --config-type option so config file can be read from stdin

internal/chezmoi/sourcestate.go, internal/cmd/config.go, internal/cmd/executetemplatecmd.go, internal/cmd/testdata/scripts/executetemplate.txt
=> Fix chezmoi execute-template --init to not read chezmoidata

internal/chezmoi/actualstateentry.go, internal/chezmoi/dryrunsystem.go, internal/chezmoi/gitdiffsystem.go, internal/chezmoi/path.go, internal/chezmoi/path_unix.go, internal/chezmoi/path_windows.go, internal/chezmoi/path_windows_test.go, internal/chezmoi/realsystem_windows.go, internal/chezmoi/sourcestate.go, internal/chezmoi/targetstateentry.go, internal/cmd/main_test.go, internal/cmd/symlinks_test.go, internal/cmd/testdata/scripts/symlinks_windows.txt
=> Normalize symlinks on Windows

internal/chezmoi/ageencryption.go, internal/chezmoi/debugencryption.go, internal/chezmoi/encryption.go, internal/chezmoi/encryption_test.go, internal/chezmoi/gpgencryption.go, internal/chezmoi/noencryption.go, internal/cmd/editcmd.go, internal/cmd/mergecmd.go, internal/cmd/testdata/scripts/init.txt, internal/cmd/testdata/scripts/merge_unix.txt, internal/cmd/testdata/scripts/mergeencrypted_unix.txt
=> Transparently decrypt files in merge command

internal/cmd/config.go, internal/cmd/testdata/scripts/edgecases.txt
=> Fix bug where adding a dir with a trailing slash added it twice

internal/cmd/config.go, internal/cmd/removecmd.go, internal/cmd/testdata/scripts/remove.txt
=>  Make remove command remove entries from persistent state

internal/chezmoi/externaldiffsystem.go, internal/cmd/testdata/scripts/issue1365.txt
=> Fix bug when using custom diff tool on a file in a subdirectory

docs/COMPARISON.md, docs/HOWTO.md, docs/REFERENCE.md, internal/chezmoi/chezmoi.go, internal/chezmoi/dumpsystem_test.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/tarreadersystem.go, internal/chezmoi/tarwritersystem_test.go, internal/chezmoi/zipwritersystem_test.go, internal/cmd/applycmd.go, internal/cmd/archivecmd.go, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/diffcmd.go, internal/cmd/dumpcmd.go, internal/cmd/editcmd.go, internal/cmd/executetemplatecmd.go, internal/cmd/importcmd.go, internal/cmd/initcmd.go, internal/cmd/main_test.go, internal/cmd/statuscmd.go, internal/cmd/testdata/scripts/external.txt, internal/cmd/testdata/scripts/externalencrypted.txt, internal/cmd/testdata/scripts/purge.txt, internal/cmd/updatecmd.go, internal/cmd/verifycmd.go
Fixes #256.
Fixes #662.
Fixes #1159.
Refs #1221.
Refs #1277.
Refs #1295.
=> Add .chezmoiexternal for external files and archives

internal/chezmoi/realsystem.go, internal/chezmoi/realsystem_unix.go, internal/chezmoi/realsystem_windows.go, internal/cmd/config.go
In testing, this speeds up chezmoi by about 30% which is irrelevant when the runtime is a few seconds.
=> Add undocumented --safe=false command line flag

docs/HOWTO.md
=> Add how-to entry on using private dotfile repos

docs/HOWTO.md, docs/REFERENCE.md, internal/chezmoi/attr.go, internal/chezmoi/attr_test.go, internal/chezmoi/chezmoi.go, internal/chezmoi/sourcestate.go, internal/cmd/config.go, internal/cmd/testdata/scripts/applyremove.txt, internal/cmd/testdata/scripts/remove.txt
=> Add remove_ attribute

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/onepasswordtemplatefuncs.go, internal/cmd/testdata/scripts/onepassword.txt
=> Add onepasswordItemFields template function

.github/workflows/main.yml, Makefile, internal/cmd/doctorcmd.go
=> Conceal the user's username in doctor command output

docs/REFERENCE.md, internal/chezmoi/externaldiffsystem.go, internal/cmd/config.go, internal/cmd/mergecmd.go, internal/cmd/testdata/scripts/diff_unix.txt, internal/cmd/testdata/scripts/merge_unix.txt
Fixes #1392.
Refs #1324.
Refs #1328.
=> Append path arguments to diff and merge command if not provided by user

docs/REFERENCE.md, go.mod, go.sum, internal/chezmoi/ageencryption.go, internal/chezmoi/ageencryption_test.go, internal/chezmoitest/chezmoitest.go, internal/cmd/autobool.go, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/diffcmd.go, internal/cmd/initcmd.go, internal/cmd/main_test.go, internal/cmd/testdata/scripts/ageencryption.txt, internal/cmd/testdata/scripts/builtinage.txt, internal/cmd/testdata/scripts/gpgencryption.txt, internal/cmd/updatecmd.go
=> Add --use-builtin-age option

internal/cmd/initcmd.go, internal/cmd/initcmd_test.go
Not quite right yet. Draft PR.
=> Extend init command to guess the user's username for private repos

internal/chezmoi/archivereadersystem.go, internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/externalguess.txt
=> Detect archive format from content if needed

docs/FAQ.md, docs/REFERENCE.md, internal/chezmoi/attr.go, internal/chezmoi/attr_test.go, internal/chezmoi/chezmoi.go, internal/chezmoi/chezmoi_unix.go, internal/chezmoi/chezmoi_windows.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go
=> Add readonly_ attribute for files and directories

internal/chezmoi/diff.go, internal/cmd/testdata/scripts/issue1365.txt
=> Fix permissions in diff when user sets a stricter umask

.github/workflows/main.yml, internal/chezmoi/gpgencryption_test.go, internal/cmd/testdata/scripts/addencrypted.txt, internal/cmd/testdata/scripts/applyskipencrypted.txt, internal/cmd/testdata/scripts/externalencrypted.txt, internal/cmd/testdata/scripts/gpg.txt, internal/cmd/testdata/scripts/gpgencryption.txt, internal/cmd/testdata/scripts/gpgencryptionsymmetric.txt
=> Disable GPG tests on Windows

.github/workflows/main.yml, internal/chezmoi/gpgencryption_test.go, internal/cmd/testdata/scripts/addencrypted.txt, internal/cmd/testdata/scripts/applyskipencrypted.txt, internal/cmd/testdata/scripts/externalencrypted.txt, internal/cmd/testdata/scripts/gpg.txt, internal/cmd/testdata/scripts/gpgencryption.txt, internal/cmd/testdata/scripts/gpgencryptionsymmetric.txt
=> Revert "Disable GPG tests on Windows"

docs/HOWTO.md
=> Add how-to entry on managing file permissions but not contents

docs/REFERENCE.md, internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/externalfilter.txt
=> Add filter option for externals

docs/REFERENCE.md, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/cmd/testdata/scripts/external.txt
=> Add support for .chezmoiexternal files in subdirectories

internal/chezmoi/chezmoi.go, internal/chezmoi/data.go, internal/chezmoi/data_test.go, internal/chezmoi/patternset.go, internal/cmd/config.go, internal/cmd/doctorcmd.go, internal/cmd/doctorcmd_unix.go, internal/cmd/doctorcmd_windows.go, internal/cmd/main_test.go, internal/cmd/testdata/scripts/doctor_unix.txt, internal/cmd/upgradecmd.go
=> Add doctor check for multiple config files

internal/cmd/config.go
=> Fix CLI flags not taking precedence over configuration

internal/cmd/config.go, internal/cmd/initcmd.go, internal/cmd/testdata/scripts/config.txt
Refs #1431 and #1441.
Thanks @felipecrs for spotting the problems!
=> Fix more command line flags overriding config vars

internal/cmd/initcmd.go, internal/cmd/testdata/scripts/init.txt
Refs #891.
cc @felipecrs 
I don't think this fixes everything, but it should address [this comment about `chezmoi init`](https://github.com/twpayne/chezmoi/issues/891#issuecomment-922379179).
=> Detect when the source directory is already in a git working copy

.github/workflows/main.yml, .goreleaser.yaml, docs/CONTRIBUTING.md
=> chore: Switch to conventional commits

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/editcmd.go, internal/cmd/initcmd.go, internal/cmd/testdata/scripts/edit.txt
As [requested by](https://github.com/twpayne/chezmoi/issues/891#issuecomment-926240841) @felipecrs.
=> feat: Make chezmoi edit with no args open working tree

docs/REFERENCE.md, internal/chezmoi/path.go, internal/cmd/addcmd.go, internal/cmd/cdcmd.go, internal/cmd/cmd.go, internal/cmd/config.go, internal/cmd/doctorcmd.go, internal/cmd/editcmd.go, internal/cmd/gitcmd.go, internal/cmd/initcmd.go, internal/cmd/testdata/scripts/workingtree.txt, internal/cmd/updatecmd.go
=> feat: Add working tree config option

docs/FAQ.md
=> docs: Add FAQ entry on diff colors not working

internal/cmd/testdata/scripts/templatefuncs.txt
=> chore: Add test for failing commands in output template function

internal/chezmoi/attr.go, internal/cmd/testdata/scripts/createencrypted.txt, internal/cmd/testdata/scripts/modifyencrypted.txt
=> fix: Allow modify_ scripts to be encrypted

docs/REFERENCE.md, internal/chezmoi/encryption_test.go, internal/cmd/applycmd.go, internal/cmd/archivecmd.go, internal/cmd/config.go, internal/cmd/diffcmd.go, internal/cmd/dumpcmd.go, internal/cmd/editcmd.go, internal/cmd/statuscmd.go, internal/cmd/updatecmd.go, internal/cmd/verifycmd.go
=> feat: Add --init flag to all relevant commands

docs/HOWTO.md, docs/REFERENCE.md, internal/chezmoi/format.go, internal/chezmoi/format_test.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go
Fixes #1450. Refs #1451.
cc @felipecrs
=> feat: Add refreshPeriod option for externals

go.mod, internal/chezmoi/abspath.go, internal/chezmoi/relpath.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/sourcestatetreenode.go, internal/chezmoi/sourcestatetreenode_test.go, internal/cmd/config.go, internal/cmd/managedcmd.go, internal/cmd/readdcmd.go, internal/cmd/testdata/scripts/external.txt, internal/cmd/unmanagedcmd.go
=> feat: Create parent directories for externals if needed

internal/chezmoi/chezmoi.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/sourcestateentry.go, internal/chezmoi/sourcestatetreenode.go, internal/cmd/testdata/scripts/external.txt
=> feat: Allow equivalent directory entries in source state and externals

docs/INSTALL.md
=> docs: Add OpenIndiana package install command

internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/add.txt
=> fix: Make chezmoi add command respect .chezmoiignore

docs/REFERENCE.md, internal/cmd/chattrcmd.go, internal/cmd/chattrcmd_test.go, internal/cmd/testdata/scripts/chattr.txt
=> feat: Extend chattr command to change target types

docs/REFERENCE.md
=> docs: Fix docs now that parent directories are created automatically

docs/REFERENCE.md, internal/chezmoi/externaldiffsystem.go, internal/chezmoi/gitdiffsystem.go, internal/cmd/config.go, internal/cmd/diffcmd.go, internal/cmd/testdata/scripts/chattr.txt, internal/cmd/testdata/scripts/diff.txt, internal/cmd/testdata/scripts/diff_unix.txt
=> feat: Add --reverse option to diff command

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/testdata/scripts/state_unix.txt
=> feat: Add --persistent-state option for location of persistent state file

docs/REFERENCE.md
=> docs: fix typo in REFERENCE.md

docs/HOWTO.md
=> docs: Add how-to on using HTTP proxies

Makefile, docs/CONTRIBUTING.md, internal/cmd/config.go
=> chore: Update Makefile to match conventional standards

docs/HOWTO.md, docs/REFERENCE.md, internal/chezmoi/chezmoi.go, internal/cmd/config.go, internal/cmd/testdata/scripts/root.txt
=> feat: Add .chezmoiroot to allow source state to be subdir of source dir

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
=> chore: Improve devcontainer

docs/REFERENCE.md, internal/cmd/gopasstemplatefuncs.go, internal/cmd/testdata/scripts/gopass.txt
=> fix: Return unparsed gopass output in gopassRaw template func

internal/cmds/lint-whitespace/main.go
=> chore: Add .idea to lint-whitespace ignore

assets/templates/COMMIT_MESSAGE.tmpl, docs/REFERENCE.md, internal/chezmoi/ageencryption.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/system.go, internal/cmd/doctorcmd.go, internal/cmd/testdata/scripts/templatedata.txt, internal/cmd/unmanagedcmd.go
=> feat: Make .chezmoidata.<format> and .chezmoitemplates available in .chezmoiignore

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/githubtemplatefuncs.go
=> feat: Add gitHubLatestRelease template function

go.mod, go.sum, internal/chezmoi/sourcestate.go, internal/cmd/config.go, internal/cmd/upgradecmd.go, internal/cmd/util.go
=> feat: Add cache HTTP client

internal/cmd/githubtemplatefuncs.go, internal/cmd/upgradecmd.go, internal/cmd/util.go
=> feat: Caching the response of the GitHub API

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/templatefuncs.txt
=> feat: Add toYaml template function

internal/chezmoi/archivereadersystem.go, internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/externalzip.txt, internal/cmd/upgradecmd.go
=> fix: Handle symlinks in zip archives

docs/REFERENCE.md
=> docs: Remove references untested config file formats

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/templatefuncs.txt
=> feat: Add fromYaml template function

docs/REFERENCE.md, internal/cmd/config.go
=> feat: Make verbose settable in the config file

internal/cmd/config.go, internal/cmd/testdata/scripts/root.txt
=> fix: Respect .chezmoiroot when generating config file

docs/REFERENCE.md, internal/chezmoi/entrytypeset.go, internal/chezmoi/gitdiffsystem.go, internal/cmd/config.go, internal/cmd/diffcmd.go, internal/cmd/testdata/scripts/applyverbose.txt
=> feat: Apply diff.exclude to all diffs

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/editcmd.go, internal/cmd/testdata/scripts/edithardlink.txt
=> feat: Add edit.hardlink config var and edit --hardlink flag

assets/chezmoi.io/.gitignore, docs/REFERENCE.md, internal/chezmoi/chezmoi.go, internal/chezmoi/sourcestate.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/scriptsdir_unix.txt
=> feat: Add .chezmoiscripts directory

docs/HOWTO.md, docs/REFERENCE.md, internal/chezmoi/boltpersistentstate.go, internal/chezmoi/debugpersistentstate.go, internal/chezmoi/mockpersistentstate.go, internal/chezmoi/nullpersistentstate.go, internal/chezmoi/persistentstate.go, internal/cmd/config.go, internal/cmd/statecmd.go, internal/cmd/testdata/scripts/state_unix.txt
=> feat: Add state get-bucket and state delete-bucket commands

docs/REFERENCE.md, internal/cmd/config.go
Use case:
```console
> cat ~/.dotfiles/home/repos/symlink_dotfiles.tmpl
{{- .chezmoi.workingTree -}}
```
=> feat: Add .chezmoi.workingTree template variable

internal/chezmoi/chezmoi.go, internal/chezmoi/sourcestate.go, internal/cmd/config.go, internal/cmd/testdata/scripts/errors.txt
=> fix: Check for .chezmoiversion outside .chezmoiroot

assets/docker/test.sh, docs/REFERENCE.md, internal/chezmoi/abspath.go, internal/chezmoi/archive.go, internal/chezmoi/archivereadersystem.go, internal/chezmoi/chezmoi.go, internal/chezmoi/sourcestate.go, internal/cmd/main_test.go, internal/cmd/noupgradecmd.go, internal/cmd/testdata/scripts/upgrade.txt, internal/cmd/upgradecmd.go, internal/cmd/util.go, internal/cmd/util_unix.go, internal/cmd/util_windows.go
=> feat: Add initial support for upgrade command on Windows

docs/COMPARISON.md
Since there is particular reason those specific emojis, pick
ones that are much easier to tell apart without reliance on
color. Red/orange/green can be quite difficult to tell apart
for some people.
=> docs: Make comparison table more accessible

internal/chezmoi/chezmoi.go, internal/chezmoi/dumpsystem_test.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/system.go, internal/chezmoi/tarwritersystem_test.go, internal/chezmoi/zipwritersystem_test.go, internal/cmd/config.go, internal/cmd/upgradecmd.go
=> fix: Read .chezmoiversion before other files

internal/chezmoi/chezmoi.go, internal/cmd/testdata/scripts/doctor_unix.txt
=> fix: Don't mark .chezmoiscripts as suspicious in doctor command

internal/chezmoi/sourcestate.go
=> fix: Fix .chezmoiversion check when using dev version

docs/HOWTO.md, internal/chezmoi/format.go, internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/doctor_unix.txt
=> chore: Fix typo in filename

internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/executetemplate.txt
=> feat: Follow symlinks in .chezmoitemplates

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/testdata/scripts/config.txt
=> feat: Add --cache option and .chezmoi.cacheDir template variable

internal/chezmoi/debugsystem.go, internal/chezmoi/sourcestate.go, internal/chezmoilog/chezmoilog.go, internal/cmd/config.go, internal/cmd/upgradecmd.go
=> chore: Log duration of commands and HTTP requests

docs/REFERENCE.md, internal/chezmoi/sourcestatetreenode.go, internal/cmd/applycmd.go, internal/cmd/archivecmd.go, internal/cmd/catcmd.go, internal/cmd/chattrcmd.go, internal/cmd/chattrcmd_test.go, internal/cmd/config.go, internal/cmd/diffcmd.go, internal/cmd/docscmd.go, internal/cmd/dumpcmd.go, internal/cmd/editcmd.go, internal/cmd/forgetcmd.go, internal/cmd/mergecmd.go, internal/cmd/readdcmd.go, internal/cmd/removecmd.go, internal/cmd/sourcepathcmd.go, internal/cmd/statuscmd.go, internal/cmd/testdata/scripts/completion.txt, internal/cmd/testdata/scripts/completion_unix.txt, internal/cmd/verifycmd.go
=> feat: Add more intelligent completion of targets, attributes, and docs

docs/REFERENCE.md, internal/cmd/secretkeyringcmd.go
=> feat: Improve keyring support

docs/REFERENCE.md, internal/chezmoi/chezmoi.go, internal/cmd/addcmd.go, internal/cmd/cmd.go, internal/cmd/config.go, internal/cmd/doctorcmd.go, internal/cmd/main_test.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/templatefuncs.txt, internal/cmd/util.go, internal/cmd/util_test.go, internal/cmd/verifycmd.go
=> feat: Add exit template function

internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/sourcestateentry.go, internal/cmd/testdata/scripts/edgecases.txt
=> feat: Improve inconsistent state error with removes

internal/chezmoi/path_unix.go, internal/chezmoi/path_windows.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/templatefuncs.txt
=> fix: Fix include function on Windows with absolute path

.github/workflows/main.yml, internal/chezmoi/gpgencryption_test.go, internal/cmd/testdata/scripts/addencrypted.txt, internal/cmd/testdata/scripts/applyskipencrypted.txt, internal/cmd/testdata/scripts/externalencrypted.txt, internal/cmd/testdata/scripts/gpg.txt, internal/cmd/testdata/scripts/gpgencryption.txt, internal/cmd/testdata/scripts/gpgencryptionsymmetric.txt
=> chore: Disable gpg tests on Windows

docs/REFERENCE.md, internal/cmd/config.go, internal/cmd/passtemplatefuncs.go, internal/cmd/testdata/scripts/pass.txt
=> feat: Add passFields template function

internal/chezmoitest/chezmoitest.go
=> chore: Update gpg integration tests

docs/COMPARISON.md
I recently saw this comparison page referenced, and noticed some inaccuracies (at least regarding yadm).
Cheers
=> yadm comparison

docs/INSTALL.md
`nix-env` also works for Nix on MacOS
=> Update INSTALL.md for Nix

docs/REFERENCE.md
=> Fixes #1791

internal/cmd/config.go, internal/cmd/testdata/scripts/completion_unix.txt
=> fix: Fix shell completion for relative paths

docs/REFERENCE.md, internal/cmd/managedcmd.go
=> feat: Add list command as an alias for managed

internal/chezmoi/sourcestate.go, internal/chezmoi/system.go, internal/cmd/testdata/scripts/edgecases.txt, internal/cmd/testdata/scripts/executetemplate.txt
=> fix: Ignore files and directories beginning with . in .chezmoitemplates

internal/chezmoi/sourcestate.go, internal/cmd/datacmd.go, internal/cmd/executetemplatecmd.go, internal/cmd/testdata/scripts/templatedata.txt
=> fix: Make data and execute-commands not depend on valid source state

internal/chezmoi/entrytypeset.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/sourcestateentry.go, internal/chezmoi/targetstateentry.go, internal/chezmoi/targetstateentry_test.go, internal/cmd/addcmd_test.go, internal/cmd/testdata/scripts/issue1832.txt
=> fix: Fix add command when parent dir permissions have changed

assets/chezmoi.io/docs/reference/commands/chattr.md, assets/chezmoi.io/docs/reference/source-state-attributes.md, assets/chezmoi.io/htmltest.yml, internal/chezmoi/attr.go, internal/chezmoi/attr_test.go, internal/chezmoi/debugsystem.go, internal/chezmoi/dryrunsystem.go, internal/chezmoi/erroronwritesystem.go, internal/chezmoi/externaldiffsystem.go, internal/chezmoi/gitdiffsystem.go, internal/chezmoi/path_unix.go, internal/chezmoi/path_windows.go, internal/chezmoi/realsystem.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/chezmoi/system.go, internal/cmd/chattrcmd.go, internal/cmd/config.go, internal/cmd/testdata/scripts/removedir.txt
Fixes #754.
@youam I think this provides the functionality you asked for. With this PR, directories with the `remove_` attribute will be removed if they are empty. If you can test for your use case, that would be awesome.
=> feat: Add remove_ attribute for directories

assets/chezmoi.io/docs/user-guide/tools/editor.md, pkg/cmd/testdata/scripts/issue1866.txt
=> chore: Add test for ignoring emacs symbolic link locks

assets/chezmoi.io/docs/hooks.py, pkg/chezmoi/sourcestate.go, pkg/chezmoi/sourcestate_test.go, pkg/cmd/testdata/scripts/issue1869.txt
=> fix: Fix race condition with multiple .chezmoiignore files

pkg/chezmoi/sourcestate.go, pkg/chezmoi/sourcestate_test.go
=> fix: Disable problematic concurrent source dir read

assets/chezmoi.io/docs/developer/developing-locally.md, assets/vagrant/debian11-i386.Vagrantfile, pkg/chezmoi/archive.go, pkg/cmd/testdata/scripts/importxz.txt
=> chore: Miscellaneous xz fixes

.github/workflows/main.yml, assets/chezmoi.io/docs/reference/commands/target-path.md, assets/chezmoi.io/mkdocs.yml, pkg/chezmoi/sourcestate.go, pkg/cmd/config.go, pkg/cmd/initcmd.go, pkg/cmd/main_test.go, pkg/cmd/sourcepathcmd.go, pkg/cmd/targetpathcmd.go, pkg/cmd/testdata/scripts/add.txt, pkg/cmd/testdata/scripts/applytype.txt, pkg/cmd/testdata/scripts/re-add.txt, pkg/cmd/testdata/scripts/targetpath.txt
=> feat: Add target-path command

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/testdata/scripts/issue1794.txt
=> docs: Add how-to on passphrase-protected private keys

assets/chezmoi.io/docs/developer/website.md, assets/chezmoi.io/docs/index.md, assets/chezmoi.io/docs/quick-start.md, assets/chezmoi.io/docs/user-guide/daily-operations.md, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/design.md, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/troubleshooting.md, assets/chezmoi.io/docs/user-guide/setup.md, assets/chezmoi.io/docs/user-guide/use-scripts-to-perform-actions.md, assets/chezmoi.io/mkdocs.yml
@ihommani designed the images as part of [Chezmoi, visite guidée](https://blog.wescale.fr/chezmoi-visite-guidee/) and so is co-author on the commit.
Fixes #708, although more images can be added.
=> docs: Add mermaid diagrams

pkg/cmd/cdcmd.go, pkg/cmd/config.go, pkg/cmd/main_test.go, pkg/cmd/testdata/scripts/cd_unix.txt, pkg/cmd/testdata/scripts/cd_windows.txt, pkg/cmd/testdata/scripts/doctor_unix.txt
=> feat: Support arguments in Windows SHELL variable

assets/chezmoi.io/docs/install.md.tmpl
=> docs: Fix chocolatey typo

assets/chezmoi.io/docs/reference/command-line-flags/common.md, assets/chezmoi.io/docs/user-guide/tools/diff.md, pkg/chezmoi/entrytypeset.go, pkg/chezmoi/entrytypeset_test.go, pkg/chezmoi/sourcestate.go, pkg/chezmoi/sourcestateentry.go, pkg/cmd/testdata/scripts/external.txt
=> feat: Add option to exclude externals

assets/chezmoi.io/docs/reference/configuration-file/variables.md, pkg/cmd/config.go, pkg/cmd/statuscmd.go, pkg/cmd/verifycmd.go
=> feat: Add status.exclude and verify.exclude config variables

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md, assets/chezmoi.io/docs/user-guide/include-dotfiles-from-elsewhere.md, pkg/chezmoi/entrytypeset.go, pkg/chezmoi/persistentstate.go, pkg/chezmoi/sourcerelpath.go, pkg/chezmoi/sourcestate.go, pkg/chezmoi/sourcestateentry.go, pkg/chezmoi/targetstateentry.go, pkg/cmd/main_test.go, pkg/cmd/testdata/scripts/externalgitrepo.txt
=> feat: Add git-repo externals

pkg/chezmoi/chezmoi.go, pkg/cmd/doctorcmd.go, pkg/cmd/testdata/scripts/doctor_unix.txt
Refs #713 #915 #1031 #1213 #1926.
=> chore: Add check for chezmoi config files to doctor command

assets/chezmoi.io/docs/reference/configuration-file/variables.md, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/troubleshooting.md, pkg/chezmoi/realsystem.go, pkg/chezmoi/realsystem_unix.go, pkg/chezmoi/realsystem_windows.go, pkg/cmd/config.go, pkg/cmd/doctorcmd.go, pkg/cmd/testdata/scripts/scripttempdir.txt
=> feat: Add scriptTempDir config var for temporary scripts

assets/chezmoi.io/docs/reference/command-line-flags/global.md, pkg/cmd/initcmd.go
=> fix: Fix confusing error message when using builtin git to init over SSH

pkg/cmd/testdata/scripts/issue1237.txt
=> chore: Add test for ignoring directories

.github/workflows/main.yml, .goreleaser.yaml
=> feat: Release raw binaries

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/troubleshooting.md
=> docs: Improve docs on empty files in chezmoi edit

assets/chezmoi.io/docs/reference/configuration-file/variables.md, pkg/cmd/diffcmd.go
=> feat: Add diff.reverse configuration variable

assets/chezmoi.io/docs/reference/templates/functions/onepassword.md, assets/chezmoi.io/docs/reference/templates/functions/onepasswordDetailsFields.md, assets/chezmoi.io/docs/reference/templates/functions/onepasswordDocument.md, assets/chezmoi.io/docs/reference/templates/functions/onepasswordItemFields.md, assets/chezmoi.io/docs/user-guide/password-managers/1password.md, pkg/cmd/onepasswordtemplatefuncs.go
=> chore: 1Password fixes

assets/chezmoi.io/docs/reference/templates/functions/keepassxcAttachment.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/keepassxctemplatefuncs.go, pkg/cmd/testdata/scripts/keepassxc.txt
=> feat: Add keepassxcAttachment command

assets/chezmoi.io/docs/reference/commands/ignored.md, assets/chezmoi.io/docs/user-guide/manage-machine-to-machine-differences.md, assets/chezmoi.io/mkdocs.yml, pkg/chezmoi/sourcestate.go, pkg/chezmoi/sourcestate_test.go, pkg/cmd/config.go, pkg/cmd/ignoredcmd.go, pkg/cmd/targetpathcmd.go, pkg/cmd/testdata/scripts/ignore.txt, pkg/cmd/testdata/scripts/ignored.txt
Refs #1959. This needs more tests before it can be merged.
=> feat: Add ignored command

assets/chezmoi.io/docs/reference/templates/functions/onepassword.md, assets/chezmoi.io/docs/reference/templates/functions/onepasswordDetailsFields.md, assets/chezmoi.io/docs/reference/templates/functions/onepasswordDocument.md, assets/chezmoi.io/docs/reference/templates/functions/onepasswordItemFields.md, assets/chezmoi.io/docs/user-guide/password-managers/1password.md, pkg/cmd/onepasswordtemplatefuncs.go
=> fix: Prefer id over label for onepasswordDetailsFields template function

pkg/cmd/keepassxctemplatefuncs.go, pkg/cmd/keepassxctemplatefuncs_test.go
=> fix: Fix parsing of multiline KeepassXC attributes

pkg/cmd/keepassxctemplatefuncs.go, pkg/cmd/testdata/scripts/keepassxc.txt
=> chore: Always pass --quiet to keepassxc-cli

pkg/cmd/config.go, pkg/cmd/readdcmd.go
=> chore: Tidy up re-add help and flags

.github/workflows/main.yml, assets/chezmoi.io/docs/install.md.tmpl
=> fix: Fix one line install instructions for Windows

.golangci.yml, pkg/chezmoi/externaldiffsystem.go, pkg/cmd/config.go, pkg/cmd/diffcmd.go, pkg/cmd/testdata/scripts/diffcommand_unix.txt
=> feat: Use diff.command for all verbose output

assets/chezmoi.io/docs/user-guide/setup.md, assets/chezmoi.io/docs/user-guide/templating.md
=> docs: Miscellaneous fixes

pkg/chezmoi/externaldiffsystem.go, pkg/cmd/testdata/scripts/diffcommand_unix.txt
=> fix: Fix apply --verbose when diff.command is set

pkg/chezmoi/sourcestate.go, pkg/chezmoi/sourcestate_test.go
Fixing https://github.com/twpayne/chezmoi/issues/2000 by modifiying the ignore map within a lock.
I moved the append of the ignored element into the method `Ignore` itself - mainly to reuse the existing lock. Even though this might look like an unwanted sideeffect of this method in the first place, i thought it's the right place instead of bloating it into all the various places or introducing an additional method.
=> fix: Fix concurrent map writes on sourcestate.ignoredRelPaths

assets/chezmoi.io/docs/reference/templates/keepassxc-functions/index.md, assets/chezmoi.io/docs/reference/templates/keepassxc-functions/keepassxc.md, assets/chezmoi.io/docs/reference/templates/keepassxc-functions/keepassxcAttachment.md, assets/chezmoi.io/docs/reference/templates/keepassxc-functions/keepassxcAttribute.md, assets/chezmoi.io/docs/user-guide/password-managers/keepassxc.md
=> docs: Improve KeepassXC and Yubikey docs

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/troubleshooting.md
For troubleshooting, I feel this workaround can help other as well.
=> troubleshooting: workaround for twpayne/chezmoi#2006

.github/workflows/main.yml, .goreleaser.yaml, pkg/chezmoi/sourcestate.go
=> chore: Connect stdin, stdout, and stderr when running git

assets/chezmoi.io/docs/reference/templates/functions/glob.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/testdata/scripts/templatefuncs.txt
=> feat: Add glob template function

assets/scripts/install.ps1
Fixes #2044.
@bradenhilton @HRXN @zb140 are co-authors.
=> chore: Remove unused variable from PowerShell install script

assets/chezmoi.io/docs/reference/commands/init.md, pkg/cmd/config.go, pkg/cmd/initcmd.go
=> feat: Add --guess-repo-url option to init command

assets/chezmoi.io/docs/developer/contributing-changes.md
Add instructions on how to:
* run tests
* build (and view) the documentation
=> docs: Add some additional details to contributing-changes.md

pkg/chezmoi/patternset.go, pkg/chezmoi/realsystem.go, pkg/cmd/templatefuncs.go
Fixes #2063.
Co-authored-by: @neersighted
=> fix: Fix use of slashes in glob on Windows

completions/chezmoi.zsh, pkg/cmd/completioncmd.go, pkg/cmd/testdata/scripts/completion.txt
=> fix: Don't complete _chezmoi in zsh completion

assets/chezmoi.io/docs/reference/configuration-file/variables.md, assets/chezmoi.io/docs/reference/templates/keeper-functions/index.md, assets/chezmoi.io/docs/reference/templates/keeper-functions/keeper.md, assets/chezmoi.io/docs/reference/templates/keeper-functions/keeperDataFields.md, assets/chezmoi.io/docs/reference/templates/keeper-functions/keeperFindPassword.md, assets/chezmoi.io/docs/user-guide/password-managers/custom.md, assets/chezmoi.io/docs/user-guide/password-managers/keeper.md, assets/chezmoi.io/docs/what-does-chezmoi-do.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/doctorcmd.go, pkg/cmd/keepertemplatefuncs.go, pkg/cmd/testdata/scripts/doctor_unix.txt, pkg/cmd/testdata/scripts/keeper.txt
Fixes #2061.
@tajetaje this is an initial implementation and probably contains a few bugs. Would you be able to test this?
=> feat: Add support for Keeper password manager

pkg/chezmoi/chezmoi.go, pkg/chezmoi/mode.go, pkg/cmd/autobool.go, pkg/cmd/config.go, pkg/cmd/datacmd.go, pkg/cmd/dataformat.go, pkg/cmd/statecmd.go, pkg/cmd/testdata/scripts/completion.txt
=> feat: Complete auto bool, format, and mode flag values

go.mod, go.sum, pkg/cmd/cdcmd.go, pkg/cmd/config.go, pkg/cmd/config_test.go, pkg/cmd/doctorcmd.go
=> fix: Parse $EDITOR and $VISUAL environment variables as shell commands

assets/chezmoi.io/docs/reference/templates/variables.md, go.mod, go.sum, pkg/cmd/config.go, pkg/cmd/config_unix.go, pkg/cmd/config_windows.go
=> feat: Add windowsVersion to builtin template data

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/design.md
=> docs: Use modeline to set filetype in VIM

go.mod, go.sum
Thanks to https://github.com/google/btree/pull/48 :)
=> chore: Update google/btree dependency

pkg/chezmoi/chezmoi_unix.go
OpenBSD hosts configure their hostname via the /etc/myname file.
This file should contain a single line that is the host's FQDN.
See myname(5) for details.
=> Support determining FQDN via /etc/myname

pkg/chezmoi/autotemplate.go, pkg/chezmoi/autotemplate_test.go, pkg/cmd/testdata/scripts/addautotemplate.txt
=> feat: Make --autotemplate escape template markers

pkg/cmd/config_windows.go, pkg/cmd/util_windows.go
=> feat: Give more context in Windows errors

pkg/cmd/config.go, pkg/cmd/config_test.go, pkg/cmd/initcmd.go, pkg/cmd/initcmd_test.go, pkg/cmd/testdata/scripts/issue2137.txt
=> fix: Check .chezmoiversion in init command

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md
No functionality changes,just updated documentation to be little more explicit.
I just wasted more time that I care to admit by misinterpreting what `source sate` means.
=> Documentation: Clarified what 'source state' means

assets/chezmoi.io/docs/reference/commands/add.md
=> add extra documentation to autotemplate

pkg/chezmoi/sourcestate.go, pkg/cmd/addcmd.go, pkg/cmd/config.go
=> feat: Implement documented add --prompt flag

assets/chezmoi.io/docs/quick-start.md, assets/chezmoi.io/docs/reference/concepts.md
=> docs: Improve documentation of chezmoi's concepts

pkg/cmd/mergecmd.go, pkg/cmd/testdata/scripts/mergeencryptedage_unix.txt
=> fix: Fix merge command for encrypted files in subdirectories

pkg/cmd/config.go, pkg/cmd/config_test.go, pkg/cmd/util.go
=> feat: Allow dashes in keys in template data in config file

pkg/chezmoi/attr.go, pkg/chezmoi/chezmoi.go, pkg/chezmoi/chezmoi_test.go, pkg/chezmoi/chezmoi_unix.go, pkg/chezmoi/chezmoi_unix_test.go, pkg/chezmoi/chezmoi_windows.go, pkg/cmd/config.go
=> fix: Fix FQDN hostname on FreeBSD

assets/chezmoi.io/docs/reference/templates/functions/fromToml.md, assets/chezmoi.io/docs/reference/templates/functions/toToml.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/testdata/scripts/templatefuncs.txt
=> feat: Add fromToml and toToml template functions

assets/chezmoi.io/docs/install.md.tmpl
=> docs: Add Termux package install and prioritize packages

assets/chezmoi.io/docs/reference/templates/init-functions/promptBoolOnce.md, assets/chezmoi.io/docs/reference/templates/init-functions/promptIntOnce.md, assets/chezmoi.io/docs/reference/templates/init-functions/promptStringOnce.md, assets/chezmoi.io/docs/user-guide/encryption/gpg.md, assets/chezmoi.io/docs/user-guide/setup.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/executetemplatecmd.go, pkg/cmd/inittemplatefuncs.go, pkg/cmd/testdata/scripts/inittemplatefuncs.txt, pkg/cmd/testdata/scripts/templatefuncs.txt
Fixes #2184.
WIP. Needs tests and documentation.
=> feat: Add prompt*Once init template functions

.github/workflows/main.yml
Refs https://github.com/actions/virtual-environments/issues/5583.
Refs https://github.com/actions/virtual-environments/pull/5854.
=> chore: Switch to macOS 12 for tests requiring Vagrant

assets/chezmoi.io/mkdocs.yml
Added the native dark and light mode toggle for mkdocs-material
=> Added toggle for dark and light mode

assets/chezmoi.io/docs/reference/commands/generate.md, assets/chezmoi.io/docs/user-guide/machines/containers-and-vms.md, assets/chezmoi.io/mkdocs.yml, assets/templates/install.sh, assets/templates/templates.go, pkg/cmd/config.go, pkg/cmd/generatecmd.go, pkg/cmd/testdata/scripts/generate.txt
Fixes #2186.
@segevfiner is this what you had mind? Would you be able to test this?
=> feat: Add generate command to generate install script

assets/chezmoi.io/docs/reference/templates/functions/comment.md, assets/chezmoi.io/docs/reference/templates/functions/replaceAllRegex.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/testdata/scripts/templatefuncs.txt
=> feat: Add more template functions

assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordRead.md, assets/chezmoi.io/docs/user-guide/password-managers/1password.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/onepasswordtemplatefuncs.go, pkg/cmd/testdata/scripts/onepassword.txt
=> feat: Add onepasswordRead template function

assets/chezmoi.io/docs/reference/commands/init.md, pkg/cmd/initcmd.go, pkg/cmd/inittemplatefuncs.go
As [suggested by](https://github.com/twpayne/chezmoi/pull/2204#issuecomment-1198823555) @felipecrs in #2204.
=> feat: Add --prompt flag to init command

assets/chezmoi.io/docs/reference/command-line-flags/common.md, pkg/cmd/cmd.go, pkg/cmd/config.go
Fixes #2245.
With this you can do:
```console
$ chezmoi apply --interactive
```
and you'll be prompted for each changed entry.
@sm1999 is this what you had in mind? Would you be able to test this?
=> feat: Add --interactive flag

assets/chezmoi.io/docs/install.md.tmpl
=> docs: Improve install instructions

assets/chezmoi.io/docs/reference/templates/functions/fromIni.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/templatefuncs_test.go
=> feat: Add fromIni template function

assets/chezmoi.io/docs/reference/templates/github-functions/gitHubLatestRelease.md, assets/chezmoi.io/docs/reference/templates/github-functions/gitHubLatestTag.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/githubtemplatefuncs.go, pkg/cmd/testdata/scripts/githubtemplatefuncs.txt
=> feat: Add gitHubLatestTag template function

assets/chezmoi.io/docs/reference/commands/edit.md, assets/chezmoi.io/docs/reference/configuration-file/variables.md, assets/chezmoi.io/docs/user-guide/advanced/use-chezmoi-with-watchman.md, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/usage.md, assets/chezmoi.io/mkdocs.yml, go.mod, pkg/cmd/editcmd.go
=> feat: Add initial --watch flag to edit command

assets/chezmoi.io/docs/reference/commands/execute-template.md, assets/chezmoi.io/docs/reference/commands/init.md, pkg/cmd/initcmd.go, pkg/cmd/inittemplatefuncs.go, pkg/cmd/testdata/scripts/init.txt
=> feat: Add --prompt* flags to init command

assets/chezmoi.io/docs/reference/templates/functions/toIni.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/templatefuncs_test.go, pkg/cmd/testdata/scripts/templatefuncs.txtar
Refs #2215.
@mcexit would you be able to test this? The tests in this PR give an idea of what `toIni` produces for various inputs. Does this particular variant of ini look reasonable?
=> feat: Add toIni template function

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/reference/templates/secret-functions/secret.md, assets/chezmoi.io/docs/reference/templates/secret-functions/secretJSON.md, pkg/cmd/secrettemplatefuncs.go, pkg/cmd/testdata/scripts/secret.txtar
=> feat: Add secret.args configuration variable

pkg/chezmoi/sourcestate.go, pkg/cmd/testdata/scripts/issue2302.txt
=> fix: Fix panic when absolute paths are used in externals

pkg/cmd/config.go, pkg/cmd/datacmd.go, pkg/cmd/dumpcmd.go, pkg/cmd/statecmd.go
=> fix: Respect format configuration variable in data, dump, and state commands

assets/chezmoi.io/docs/reference/templates/functions/includeTemplate.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/testdata/scripts/templatefuncs.txtar
Fixes #2310.
@joshuaspence is this what you had in mind?
=> feat: Add includeTemplate template function

pkg/cmd/editcmd.go, pkg/cmd/main_test.go, pkg/cmd/testdata/scripts/issue2300.txtar
=> fix: Apply changes to directories when editing directories

assets/chezmoi.io/docs/reference/templates/functions/includeTemplate.md, pkg/chezmoi/chezmoi.go, pkg/chezmoi/sourcestate.go, pkg/chezmoi/system.go, pkg/cmd/templatefuncs.go, pkg/cmd/testdata/scripts/templatefuncs.txtar
=> fix: Make includeTemplate function first search in .chezmoitemplates

pkg/cmd/templatefuncs.go, pkg/cmd/templatefuncs_test.go
As identified with @mcexit in https://github.com/twpayne/chezmoi/issues/2279#issuecomment-1235854442.
=> fix: Fix handling of newlines in comment template function

go.mod, go.sum, pkg/chezmoi/glob.go, pkg/chezmoi/patternset.go, pkg/chezmoi/realsystem.go, pkg/cmd/templatefuncs.go
Refs https://github.com/bmatcuk/doublestar/pull/69.
=> chore: Use an alternative method to avoid following symlinks in doublestar.Glob

assets/chezmoi.io/docs/user-guide/tools/diff.md, assets/chezmoi.io/docs/user-guide/tools/merge.md
=> docs: Add hints about escaping diff and merge args in config file template

pkg/cmd/sourcepathcmd.go, pkg/cmd/testdata/scripts/issue2354.txtar
=> fix: Only read source state if needed in source-path command

pkg/chezmoi/tarwritersystem.go, pkg/chezmoi/zipwritersystem.go, pkg/cmd/testdata/scripts/externalgitrepo.txtar
=> fix: Ignore commands when creating archives

pkg/cmd/config.go, pkg/cmd/util_unix.go, pkg/cmd/util_windows.go
=> feat: Always set and restore Windows console

assets/chezmoi.io/docs/reference/command-line-flags/global.md, assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, go.mod, pkg/chezmoi/sourcestate.go, pkg/cmd/config.go, pkg/cmd/readhttpresponse.go, pkg/cmd/readhttpresponse_test.go
=> feat: Add --progress flag to show progress when downloading externals

assets/chezmoi.io/docs/reference/source-state-attributes.md
I thought it would be useful to elaborate in the documentation a bit about `once` vs. `onchange` attributes. It's a bit hard to remember and I keep going to [this thread](https://github.com/twpayne/chezmoi/discussions/2210) to remind myself when needed, and so I thought it would be nicer to just check the reference instead.
=> docs: Elaborate on once vs onchange attributes

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/reference/configuration-file/warnings.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/testdata/scripts/configstate.txtar
Fixes #2378. Needs #2376 to land first.
=> feat: Add option to suppress warnings

pkg/cmd/config.go, pkg/cmd/editcmd.go, pkg/cmd/mergeallcmd.go, pkg/cmd/sourcepathcmd.go, pkg/cmd/statuscmd.go
=> fix: Avoid double read of source state in merge-all and status commands

pkg/chezmoi/debugsystem.go, pkg/chezmoi/dryrunsystem.go, pkg/chezmoi/erroronwritesystem.go, pkg/chezmoi/erroronwritesystem_test.go, pkg/chezmoi/externaldiffsystem.go, pkg/chezmoi/externaldiffsystem_test.go, pkg/chezmoi/format.go, pkg/chezmoi/format_test.go, pkg/chezmoi/gitdiffsystem.go, pkg/chezmoi/realsystem.go, pkg/chezmoi/sourcestate.go, pkg/chezmoi/system.go
=> feat: Improve performance of the externals cache

assets/chezmoi.io/docs/reference/command-line-flags/global.md, pkg/chezmoi/refreshexternals.go, pkg/chezmoi/sourcestate.go, pkg/chezmoi/sourcestate_test.go, pkg/cmd/config.go, pkg/cmd/testdata/scripts/externalgitrepo.txtar
=> feat: Add always/auto/never options to --refresh-externals flag

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/design.md
Refs #189, #226, #1992, #2021, and #2390.
=> docs: Add FAQ entry on multiple source states

pkg/cmd/testdata/scripts/textconv.txtar
=> chore: Add test that chezmoi apply uses textconv

pkg/chezmoi/gitdiffsystem.go, pkg/cmd/config.go, pkg/cmd/testdata/scripts/textconv.txtar, pkg/cmd/textconv.go
=> fix: Use textconv in interactive diffs

pkg/chezmoi/entrytypeset.go, pkg/chezmoi/entrytypeset_test.go, pkg/cmd/addcmd.go, pkg/cmd/applycmd.go, pkg/cmd/archivecmd.go, pkg/cmd/cmd.go, pkg/cmd/config.go, pkg/cmd/diffcmd.go, pkg/cmd/dumpcmd.go, pkg/cmd/editcmd.go, pkg/cmd/importcmd.go, pkg/cmd/managedcmd.go, pkg/cmd/readdcmd.go, pkg/cmd/statuscmd.go, pkg/cmd/testdata/scripts/completion_unix.txtar, pkg/cmd/updatecmd.go, pkg/cmd/verifycmd.go
=> feat: Add shell completion for --include and --exclude flags

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/reference/target-types.md, assets/chezmoi.io/docs/user-guide/use-scripts-to-perform-actions.md, pkg/chezmoi/realsystem.go, pkg/chezmoi/realsystem_unix.go, pkg/chezmoi/realsystem_windows.go, pkg/cmd/config.go, pkg/cmd/testdata/scripts/scriptenv.txtar
Refs #2418.
Refs https://github.com/halostatue/chezmoi/commit/fd75d6be45e3bb8b34d45a9ba60d4197b843b394.
cc @halostatue 
Co-authored-by: Austin Ziegler <austin@zieglers.ca>
=> feat: Add scriptEnv configuration variable

.github/workflows/main.yml
=> chore: Automatically deploy website after release

assets/chezmoi.io/docs/install.md.tmpl
Add instructions to install chezmoi in openSUSE Tumbleweed
=> Add instructions for openSUSE Tumbleweed

Makefile, pkg/cmd/chattrcmd.go, pkg/cmd/testdata/scripts/chattrencrypted.txtar
=> fix: Make chattr {no,}encrypted decrypt and encrypt source file

pkg/chezmoi/data.go, pkg/chezmoi/data_test.go, pkg/chezmoi/realsystem.go, pkg/cmd/config.go, pkg/cmd/doctorcmd.go, pkg/cmd/initcmd.go, pkg/cmd/sourcepathcmd.go, pkg/cmd/testdata/scripts/scriptenv.txtar, pkg/cmd/testdata/scripts/templatevars.txtar, pkg/cmd/upgradecmd.go, pkg/cmd/util.go, pkg/cmd/util_test.go
Fixes #2418.
Refs #2423.
Not quite ready yet...
=> feat: Expose template data in environment variables

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/usage.md, assets/chezmoi.io/docs/user-guide/use-scripts-to-perform-actions.md
Refs https://github.com/twpayne/chezmoi/discussions/1817
=> docs: Add faq entry for templates pre-requisites

assets/chezmoi.io/docs/reference/target-types.md
Refs https://github.com/twpayne/chezmoi/issues/2472#issuecomment-1285705018
=> docs: Add note on setting .ps1 interpreter to pwsh

pkg/chezmoi/persistentstate.go, pkg/chezmoi/targetstateentry.go, pkg/cmd/testdata/scripts/configstate.txtar, pkg/cmd/testdata/scripts/state_unix.txtar, pkg/cmd/testdata/scripts/state_windows.txtar
=> fix: Include git repo external state in state dump output

assets/chezmoi.io/docs/install.md.tmpl, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/troubleshooting.md
Fixes #2486.
Refs #2364.
cc @galou
=> docs: Add FAQ entry on snap stdin/stdout redirect bug

assets/chezmoi.io/docs/user-guide/daily-operations.md, pkg/chezmoi/targetstateentry.go, pkg/cmd/testdata/scripts/issue2500.txtar, pkg/cmd/updatecmd.go
=> chore: Improve error messages from git-repo externals

assets/chezmoi.io/docs/reference/commands/init.md, pkg/cmd/config.go, pkg/cmd/initcmd.go
=> feat: Add --recurse-submodules flag to init command

assets/chezmoi.io/docs/reference/command-line-flags/common.md, assets/chezmoi.io/docs/reference/commands/managed.md, pkg/chezmoi/entrytypeset.go, pkg/cmd/managedcmd_test.go, pkg/cmd/testdata/scripts/managed.txtar
As spotted by @sm1999 in #2473.
=> chore: Fix refactored --include and --exclude flags

pkg/cmd/testdata/scripts/issue-2510.txtar
=> chore: Add test for .chezmoiignore and scripts

go.mod, pkg/chezmoi/dumpsystem_test.go, pkg/chezmoi/tarwritersystem_test.go, pkg/chezmoi/zipwritersystem_test.go
Pending resolution of https://github.com/bmatcuk/doublestar/issues/73.
=> chore: Blacklist buggy version of github.com/bmatcuk/doublestar/v4

pkg/chezmoi/chezmoi_unix.go, pkg/chezmoi/chezmoi_windows.go, pkg/chezmoi/sourcestate.go, pkg/chezmoi/sourcestate_test.go, pkg/chezmoi/template.go, pkg/chezmoi/template_test.go, pkg/cmd/config.go, pkg/cmd/templatefuncs.go
=> feat: Add line ending template directive

assets/chezmoi.io/docs/reference/templates/functions/setValueAtPath.md, assets/chezmoi.io/docs/user-guide/manage-different-types-of-file.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/templatefuncs_test.go, pkg/cmd/testdata/scripts/modify_unix.txtar, pkg/cmd/testdata/scripts/templatefuncs.txtar
=> feat: Add setValueAtPath template function

pkg/cmd/mergeallcmd.go, pkg/cmd/testdata/scripts/mergeall_unix.txtar
=> fix: Don't merge non-files in merge-all command

assets/chezmoi.io/docs/reference/templates/directives.md
It's quite rough at the moment, I'm happy to make changes.
=> docs: Add line endings directive documentation

go.mod, go.sum, pkg/chezmoi/glob.go, pkg/cmd/managedcmd_test.go
Draft PR. Requires https://github.com/bmatcuk/doublestar/issues/73 to be fixed.
=> chore: Better handle errors when globbing

assets/chezmoi.io/docs/reference/templates/init-functions/promptBoolOnce.md, assets/chezmoi.io/docs/reference/templates/init-functions/promptIntOnce.md, assets/chezmoi.io/docs/reference/templates/init-functions/promptStringOnce.md, pkg/cmd/executetemplatecmd.go, pkg/cmd/inittemplatefuncs.go, pkg/cmd/templatefuncs.go, pkg/cmd/templatefuncs_test.go, pkg/cmd/testdata/scripts/inittemplatefuncs.txtar
=> feat: Allow prompt*Once template functions to take paths

pkg/chezmoi/debugsystem.go, pkg/chezmoi/dryrunsystem.go, pkg/chezmoi/dumpsystem.go, pkg/chezmoi/dumpsystem_test.go, pkg/chezmoi/erroronwritesystem.go, pkg/chezmoi/externaldiffsystem.go, pkg/chezmoi/gitdiffsystem.go, pkg/chezmoi/realsystem.go, pkg/chezmoi/system.go, pkg/chezmoi/targetstateentry.go, pkg/chezmoi/tarwritersystem.go, pkg/chezmoi/zipwritersystem.go, pkg/cmd/testdata/scripts/issue1666.txtar, pkg/cmd/testdata/scripts/runscriptdir_unix.txtar, pkg/cmd/testdata/scripts/script_unix.txtar, pkg/cmd/testdata/scripts/script_windows.txtar, pkg/cmd/testdata/scripts/scriptsubdir_unix.txtar, pkg/cmd/testdata/scripts/scriptsubdir_windows.txtar
As [spotted by](https://github.com/twpayne/chezmoi/discussions/1666#discussioncomment-4109617) @felipecrs.
=> fix: Don't show always scripts in apply --verbose when excluded from diffs

pkg/cmd/config.go, pkg/cmd/readdcmd.go
=> fix: Make re-add command respect --interactive flag

assets/chezmoi.io/docs/reference/commands/cd.md, pkg/cmd/cdcmd.go, pkg/cmd/testdata/scripts/cd_unix.txtar
=> feat: Add an optional path argument to the cd command

pkg/chezmoi/externaldiffsystem.go, pkg/cmd/testdata/scripts/issue2573.txt
=> fix: Respect diff filter in removes with external diff tool

assets/chezmoi.io/docs/quick-start.md
=> Fix minor typos

pkg/chezmoi/targetstateentry.go, pkg/cmd/testdata/scripts/issue2599.txtar
=> fix: Don't attempt to run empty scripts

pkg/chezmoi/sourcestate.go, pkg/cmd/config.go, pkg/cmd/testdata/scripts/issue2609.txtar
=> fix: Respect config file umask setting when creating entries

assets/chezmoi.io/docs/reference/templates/functions/lstat.md, assets/chezmoi.io/docs/reference/templates/functions/stat.md, assets/chezmoi.io/mkdocs.yml, pkg/chezmoi/chezmoi.go, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/testdata/scripts/templatefuncs.txtar
=> feat: Add lstat template function

assets/chezmoi.io/docs/reference/commands/managed.md, assets/chezmoi.io/docs/reference/commands/unmanaged.md, pkg/cmd/config.go, pkg/cmd/managedcmd.go, pkg/cmd/pathstyle.go, pkg/cmd/testdata/scripts/managed.txtar, pkg/cmd/testdata/scripts/unmanaged.txtar, pkg/cmd/unmanagedcmd.go
=> feat: Add --path-style option to managed and unmanaged commands

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md, pkg/chezmoi/chezmoi.go, pkg/chezmoi/sourcestate.go, pkg/cmd/testdata/scripts/external.txtar
=> feat: Add verification of external checksums

assets/chezmoi.io/docs/reference/commands/managed.md, pkg/cmd/managedcmd.go, pkg/cmd/pathstyle.go, pkg/cmd/testdata/scripts/managed.txtar
=> feat: Add support for source paths in managed command

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md
=> docs: Fix passphrase-once encryption instructions

pkg/cmd/cdcmd.go, pkg/cmd/testdata/scripts/cd_unix.txtar
=> feat: Allow cd command to take the destination directory as an argument

pkg/chezmoi/boltpersistentstate.go
=> fix: Improve error message when state database cannot be locked

pkg/cmd/config.go, pkg/cmd/editcmd.go
=> fix: Fix bug where edit --watch only applied the first change

assets/chezmoi.io/docs/reference/templates/functions/hexDecode.md, assets/chezmoi.io/docs/reference/templates/functions/hexEncode.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/testdata/scripts/templatefuncs.txtar
=> feat: Add hexDecode and hexEncode template functions

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoitemplates.md
=> Fix redundant sentence

pkg/cmd/initcmd.go, pkg/cmd/initcmd_test.go
=> fix: Fix init --ssh

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/reference/templates/keepassxc-functions/index.md, pkg/cmd/config.go, pkg/cmd/keepassxctemplatefuncs.go
Fixes https://github.com/twpayne/chezmoi/issues/2676.
=> feat: Add keepassxc.prompt config variable

assets/chezmoi.io/docs/reference/templates/1password-functions/onepasswordItemFields.md
=> redoing typo fix in op command

pkg/cmd/chattrcmd.go, pkg/cmd/config.go, pkg/cmd/testdata/scripts/chattr.txtar
=> feat: Add --recursive flag to chattr command

pkg/cmd/annotation.go, pkg/cmd/catconfigcmd.go, pkg/cmd/cdcmd.go, pkg/cmd/cmd.go, pkg/cmd/cmd_test.go, pkg/cmd/completioncmd.go, pkg/cmd/config.go, pkg/cmd/doctorcmd.go, pkg/cmd/dumpconfigcmd.go, pkg/cmd/editconfigcmd.go, pkg/cmd/generatecmd.go, pkg/cmd/testdata/scripts/issue2695.txtar
=> feat: Check config file format in doctor command

pkg/cmd/keepassxctemplatefuncs.go
=> fix: Only prompt once for KeePassXC password

pkg/cmd/initcmd.go, pkg/cmd/initcmd_test.go
=> fix: Remove problematic username guessing in init command

go.mod, go.sum
=> fix: Revert buggy diff library

.golangci.yml, assets/chezmoi.io/docs/developer/developing-locally.md, assets/chezmoi.io/docs/reference/commands/import.md, assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md, go.mod, go.sum, pkg/archivetest/zip.go, pkg/archivetest/zip_test.go, pkg/chezmoi/archive.go, pkg/chezmoi/zipwritersystem.go, pkg/chezmoi/zipwritersystem_test.go, pkg/cmd/archivecmd.go, pkg/cmd/testdata/scripts/importtarzst.txtar
=> feat: Add zstd compression support

pkg/cmd/config.go, pkg/cmd/initcmd.go, pkg/cmd/purgecmd.go
=> fix: Make chezmoi init --purge-binary always remove binary

assets/chezmoi.io/docs/install.md.tmpl
=> docs: Add install command for winget

assets/chezmoi.io/docs/reference/commands/cd.md, assets/chezmoi.io/docs/reference/target-types.md, pkg/cmd/config.go, pkg/cmd/testdata/scripts/cd_unix.txtar
=> Set CHEZMOI* environment variables when running cd command

assets/chezmoi.io/docs/user-guide/use-scripts-to-perform-actions.md
=> docs: Improve documentation on scripts

assets/chezmoi.io/docs/reference/templates/functions/deleteValueAtPath.md, assets/chezmoi.io/docs/reference/templates/functions/pruneEmptyDicts.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/templatefuncs_test.go, pkg/cmd/testdata/scripts/templatefuncs.txtar
Fixes #2748.
@felipecrs would you be able to test this?
=> Add deleteValueAtPath and pruneEmptyDicts template functions

assets/chezmoi.io/docs/reference/templates/functions/toPrettyJson.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/templatefuncs.go, pkg/cmd/testdata/scripts/templatefuncs.txtar
Fixes #2749.
Another one for you, @felipecrs. I'm pretty sure this one works, but feel free to test it if you like :)
=> feat: Extend toPrettyJson template function to take indent

pkg/cmd/targetpathcmd.go, pkg/cmd/testdata/scripts/issue2752.txtar
=> fix: Fix chezmoi target-path when using .chezmoiroot

assets/chezmoi.io/docs/reference/commands/add.md, pkg/chezmoi/sourcestate.go, pkg/cmd/addcmd.go, pkg/cmd/testdata/scripts/add.txtar
=> feat: Print a warning when chezmoi add is called with an ignored entry

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/reference/templates/github-functions/index.md, pkg/chezmoi/persistentstate.go, pkg/chezmoi/sourcestate.go, pkg/chezmoi/targetstateentry.go, pkg/cmd/config.go, pkg/cmd/executetemplatecmd.go, pkg/cmd/githubtemplatefuncs.go, pkg/cmd/statecmd.go, pkg/cmd/testdata/scripts/configstate.txtar, pkg/cmd/testdata/scripts/state_unix.txtar, pkg/cmd/testdata/scripts/state_windows.txtar
=> feat: Cache GitHub API results by default to stay under rate limit

assets/chezmoi.io/docs/reference/command-line-flags/global.md, pkg/cmd/config.go, pkg/cmd/readhttpresponse.go
=> feat: Display progress bars by default when stdout is a TTY

assets/chezmoi.io/docs/reference/templates/bitwarden-functions/bitwardenAttachmentByRef.md, assets/chezmoi.io/docs/user-guide/password-managers/bitwarden.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/bitwardentemplatefuncs.go, pkg/cmd/config.go, pkg/cmd/testdata/scripts/bitwarden.txtar
=> feat(bitwarden): Grab attachment by object name

assets/chezmoi.io/docs/reference/commands/execute-template.md, pkg/cmd/executetemplatecmd.go, pkg/cmd/testdata/scripts/executetemplate.txtar
=> feat: Add --with-stdin flag to execute-template command

assets/chezmoi.io/docs/user-guide/include-files-from-elsewhere.md
=> docs: Improve documentation on externals

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md, assets/chezmoi.io/docs/reference/templates/directives.md, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/externals.md, assets/chezmoi.io/docs/user-guide/include-files-from-elsewhere.md, assets/chezmoi.io/mkdocs.yml
=> docs: Improve documentation on git-repo externals

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/reference/templates/dashlane-functions/dashlanePassword.md, assets/chezmoi.io/docs/reference/templates/dashlane-functions/index.md, assets/chezmoi.io/docs/user-guide/password-managers/dashlane.md, assets/chezmoi.io/docs/what-does-chezmoi-do.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/dashlanetemplatefuncs.go, pkg/cmd/testdata/scripts/dashlane.txtar
=> feat: Add Dashlane password manager support

assets/chezmoi.io/docs/reference/templates/dashlane-functions/dashlaneNote.md, assets/chezmoi.io/docs/user-guide/password-managers/dashlane.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/dashlanetemplatefuncs.go, pkg/cmd/testdata/scripts/dashlane.txtar
=> feat: Add Dashlane secure notes support

pkg/cmd/testdata/scripts/targetpath.txtar
=> chore: Add test for target-path, .chezmoiscripts, and .chezmoiroot

assets/chezmoi.io/docs/reference/commands/re-add.md, assets/chezmoi.io/docs/reference/templates/aws-secrets-manager-functions/awsSecretsManager.md, assets/chezmoi.io/docs/reference/templates/directives.md, assets/chezmoi.io/docs/reference/templates/keeper-functions/keeper.md, go.mod
=> docs: Fix typo

pkg/cmd/testdata/scripts/diffcommand_unix.txtar
=> chore: Add test that diff.exclude excludes dirs from external diff tool

assets/chezmoi.io/docs/reference/configuration-file/hooks.md, assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/mkdocs.yml, pkg/cmd/applycmd.go, pkg/cmd/archivecmd.go, pkg/cmd/cdcmd.go, pkg/cmd/config.go, pkg/cmd/datacmd.go, pkg/cmd/diffcmd.go, pkg/cmd/dumpcmd.go, pkg/cmd/editcmd.go, pkg/cmd/executetemplatecmd.go, pkg/cmd/initcmd.go, pkg/cmd/mergeallcmd.go, pkg/cmd/sourcepathcmd.go, pkg/cmd/statuscmd.go, pkg/cmd/testdata/scripts/hooks.txtar, pkg/cmd/updatecmd.go, pkg/cmd/verifycmd.go
=> feat: Add pre- and post-command hooks

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/reference/templates/bitwarden-functions/index.md, assets/chezmoi.io/docs/reference/templates/bitwarden-functions/rbw.md, assets/chezmoi.io/docs/reference/templates/bitwarden-functions/rbwFields.md, assets/chezmoi.io/mkdocs.yml, pkg/cmd/config.go, pkg/cmd/doctorcmd.go, pkg/cmd/rbwtemplatefuncs.go, pkg/cmd/testdata/scripts/rbw.txtar
=> feat: Add rbw template function for Bitwarden

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/externals.md, assets/chezmoi.io/mkdocs.yml, pkg/chezmoi/sourcestate.go, pkg/cmd/config.go, pkg/cmd/testdata/scripts/issue2858.txtar, pkg/cmd/unmanagedcmd.go
=> fix: Don't list entries in git-repo externals as unmanaged

pkg/cmd/testdata/scripts/issue2865.txtar
=> chore: Add test for reported .chezmoiroot issue

pkg/cmd/inittemplatefuncs.go, pkg/cmd/testdata/scripts/init.txtar
=> fix: Fix init --promptBool for promptBoolOnce template function

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md
=> docs: update encryption md to account for chezmoiroot

pkg/cmd/removecmd.go, pkg/cmd/testdata/scripts/applyremove.txtar, pkg/cmd/testdata/scripts/issue2954.txtar
=> fix: Fix chezmoi rm with files in exact_ directories

pkg/cmd/catcmd.go, pkg/cmd/chattrcmd.go, pkg/cmd/config.go, pkg/cmd/editcmd.go, pkg/cmd/forgetcmd.go, pkg/cmd/mergecmd.go, pkg/cmd/removecmd.go, pkg/cmd/testdata/scripts/dumpjson.txtar, pkg/cmd/testdata/scripts/issue2977.txtar, pkg/cmd/testdata/scripts/remove.txtar, pkg/cmd/testdata/scripts/sourcepath.txtar, pkg/cmd/testdata/scripts/tilde.txtar
=> fix: Fix commands for managed files in exact_ directories

assets/chezmoi.io/docs/user-guide/password-managers/bitwarden.md
=> docs: Improved Bitwarden login documentation

assets/chezmoi.io/docs/reference/source-state-attributes.md, pkg/chezmoi/attr.go, pkg/chezmoi/attr_test.go, pkg/chezmoi/sourcestate.go, pkg/cmd/chattrcmd.go, pkg/cmd/testdata/scripts/issue2995.txtar
=> fix: Only create empty files if they have the empty_ attribute

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoidata-format.md, pkg/chezmoi/sourcestate.go, pkg/cmd/testdata/scripts/edgecases.txtar, pkg/cmd/testdata/scripts/executetemplate.txtar
=> feat: Add support for .chezmoidata directory

pkg/chezmoi/archivereadersystem.go, pkg/chezmoi/debugsystem.go, pkg/chezmoi/dryrunsystem.go, pkg/chezmoi/dumpsystem.go, pkg/chezmoi/erroronwritesystem.go, pkg/chezmoi/externaldiffsystem.go, pkg/chezmoi/gitdiffsystem.go, pkg/chezmoi/nullsystem.go, pkg/chezmoi/readonlysystem.go, pkg/chezmoi/realsystem.go, pkg/chezmoi/system.go, pkg/chezmoi/tarwritersystem.go, pkg/chezmoi/zipwritersystem.go, pkg/cmd/config.go, pkg/cmd/testdata/scripts/issue3005.txtar
=> fix: Fix init --debug flag

pkg/cmd/secretkeyringcmd.go
=> fix: Fix parsing of flags to secret keyring delete command

assets/chezmoi.io/docs/reference/commands/init.md, pkg/chezmoi/realsystem.go, pkg/chezmoi/sourcestate.go, pkg/cmd/interactivetemplatefuncs.go, pkg/cmd/prompt.go, pkg/cmd/testdata/scripts/issue3008.txtar
=> fix: Handle multiple files in .chezmoidata directory

pkg/chezmoi/sourcestate.go, pkg/cmd/testdata/scripts/issue3051.txtar
=> fix: Check .chezmoiignore before protected paths

pkg/cmd/config.go, pkg/cmd/testdata/scripts/issue3064.txtar
=> fix: Respect persistentState config variable

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md, assets/chezmoi.io/docs/user-guide/include-files-from-elsewhere.md, pkg/chezmoi/sourcestate.go, pkg/cmd/testdata/scripts/external.txtar
Fixes #3079.
Refs #3069.
Refs #3072.
@Sacro is this what you had in mind? Would you be able to test this?
=> feat: Add archive-file externals

pkg/chezmoi/chezmoi.go, pkg/chezmoi/chezmoi_test.go
=> fix: Never consider localhost.localdomain in /etc/hosts as the FQDN

assets/chezmoi.io/docs/user-guide/manage-machine-to-machine-differences.md
=> docs: Clarify use of exclude patterns in .chezmoiignore

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternals.md, assets/chezmoi.io/mkdocs.yml, pkg/chezmoi/chezmoi.go, pkg/chezmoi/sourcestate.go, pkg/cmd/testdata/scripts/external.txtar
=> feat: Add .chezmoiexternals directory for multiple externals

go.mod, pkg/chezmoi/template.go, pkg/cmd/testdata/scripts/issue3126.txtar
=> fix: Ensure that templates cannot modify each other's data

assets/chezmoi.io/docs/reference/commands/re-add.md, internal/cmd/readdcmd.go, internal/cmd/testdata/scripts/re-add.txtar
=> feat: Extend re-add command to accept an optional list of targets

internal/chezmoi/chezmoi_windows.go
Refs #3152, cc @arran4.
Rationale for changes:
* Computing the slice of extensions is cheap, so we don't need to do it lazily when first required. Instead, we can do it on startup. This also avoids any potential races. chezmoi executes templates concurrently when reading the source state.
* Windows environment variables are case-insensitive, so use the all-uppercase name as that seems to be the canonical form.
* We can simplify the logic by returning early as soon as we know that the file is not an executable.
=> chore: Tidy up implementation if isExecutable on Windows

internal/chezmoi/sourcestate.go
Fixes #3154.
cc @dhruvinsh. Would you be able to test this? You can download a compiled binary from the artifacts of the GitHub Actions run on this PR.
=> fix: Avoid concurrent map access when evaluating multiple templates

assets/chezmoi.io/docs/reference/templates/functions/isExecutable.md, assets/chezmoi.io/mkdocs.yml, internal/chezmoi/chezmoi_unix.go, internal/chezmoi/chezmoi_windows.go, internal/chezmoi/sourcestate.go, internal/cmd/config.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/templatefuncs.txtar
Supersedes #3153. Note author is still credited as @arran4.
Changes compared to #3153 
* Includes #3156.
* Minor doc fix.
* Make code follow chezmoi's style more closely.
* Makes commit messages follow chezmoi's guidelines, as described in [the contributing guide](https://www.chezmoi.io/developer/contributing-changes/).
=> feat: Add isExecutable template function

internal/chezmoi/sourcestate.go
Fixes https://github.com/twpayne/chezmoi/issues/3154#issuecomment-1667024331, I think.
=> fix: Fix race condition in concurrent parsing of externals

assets/chezmoi.io/docs/reference/command-line-flags/common.md
=> docs: Document --source-path flag

assets/chezmoi.io/docs/reference/commands/execute-template.md, assets/chezmoi.io/docs/reference/commands/init.md, assets/chezmoi.io/docs/reference/templates/init-functions/promptBool.md, assets/chezmoi.io/docs/reference/templates/init-functions/promptChoice.md, assets/chezmoi.io/docs/reference/templates/init-functions/promptChoiceOnce.md, assets/chezmoi.io/mkdocs.yml, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/executetemplatecmd.go, internal/cmd/inittemplatefuncs_test.go, internal/cmd/interactivetemplatefuncs.go, internal/cmd/testdata/scripts/executetemplate.txtar, internal/cmd/testdata/scripts/init.txtar, internal/cmd/testdata/scripts/inittemplatefuncs.txtar
Fixes #3167.
WIP, needs testing and tests.
=> feat: Add promptChoice and promptChoiceOnce template functions

assets/chezmoi.io/docs/reference/commands/age.md, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md, assets/chezmoi.io/mkdocs.yml, internal/cmd/agecmd.go, internal/cmd/config.go, internal/cmd/lazyscryptidentity.go, internal/cmd/testdata/scripts/age.txtar
Refs #3198.
@arrrgi is this what you had in mind?
=> feat: Add age command

assets/chezmoi.io/docs/reference/templates/variables.md, internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/templatedata.txtar
=> feat: add .chezmoi.targetFile template variable

internal/chezmoi/sourcestate.go, internal/cmd/applycmd_test.go, internal/cmd/testdata/scripts/issue3206.txtar
=> fix: Handle .chezmoidata files in subdirectories when template has already been executed

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md, internal/chezmoi/ageencryption.go, internal/cmd/agecmd.go, internal/cmd/testdata/scripts/age.txtar
=> feat: Add decryption of non-armored files to age command

internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestate_test.go, internal/cmd/testdata/scripts/issue3232.txtar
=> feat: Allow overlapping, non-conflicting externals

assets/chezmoi.io/docs/reference/plugins.md, assets/chezmoi.io/mkdocs.yml, internal/cmd/cmd.go, internal/cmd/testdata/scripts/plugin.txtar
cc @felipecrs who previously requested plugin support (sorry I can't find the link)
=> feat: Add plugin support

internal/cmd/cdcmd.go
=> fix: provide a consistent error for cd to file

internal/chezmoilog/chezmoilog.go, internal/cmd/annotation.go, internal/cmd/config.go, internal/cmd/diffcmd.go, internal/cmd/mergeallcmd.go, internal/cmd/statuscmd.go, internal/cmd/testdata/scripts/issue3240.txtar
Fixes #3240.
WIP, do not merge.
=> fix: Use pager for all verbose output

assets/chezmoi.io/docs/reference/templates/github-functions/gitHubLatestTag.md, assets/chezmoi.io/docs/reference/templates/github-functions/gitHubReleases.md, assets/chezmoi.io/docs/reference/templates/github-functions/gitHubTags.md
=> docs: Fix cross-function link references

assets/chezmoi.io/docs/reference/templates/init-functions/promptChoice.md, assets/chezmoi.io/docs/reference/templates/init-functions/promptChoiceOnce.md
I struggled for quite a while to setup this function in my config template. For someone like me with no knowledge of Go, this would have been super helpful to have.
=> docs: Add examples for string init functions

internal/cmd/chattrcmd.go, internal/cmd/testdata/scripts/chattr.txtar
=> fix: Add chattr +remove support for files

internal/cmd/upgradecmd.go, internal/cmd/upgradecmd_unix.go, internal/cmd/upgradecmd_windows.go
=> chore: Eliminate duplicate upgrade code

internal/cmd/config.go, internal/cmd/statuscmd.go, internal/cmd/testdata/scripts/issue3257.txtar
Fixes #3257.
cc @felipecrs. Thank you for your help on this. This still needs a bit of testing and thinking about edge cases, so this PR is draft for now. If you could test this PR, that would be awesome.
=> fix: Only invoke diff pager if command modifies filesystem

assets/chezmoi.io/docs/reference/release-history.md.tmpl
Fixes table of contents, empty release notes, and adds full changelog to each release.
=> docs: Tidy up release notes

assets/chezmoi.io/docs/reference/commands/edit-config-template.md, assets/chezmoi.io/mkdocs.yml, internal/cmd/config.go, internal/cmd/editconfigtemplatecmd.go, internal/cmd/testdata/scripts/editconfigtemplate.txtar
Refs https://github.com/twpayne/chezmoi/discussions/2424#discussioncomment-7468568.
=> feat: Add edit-config-template command

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
=> docs: fix default value of persistentState variable

assets/chezmoi.io/docs/reference/commands/generate.md, assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/user-guide/daily-operations.md, assets/templates/COMMIT_MESSAGE.tmpl, internal/cmd/config.go, internal/cmd/generatecmd.go, internal/cmd/gitcmd.go, internal/cmd/testdata/scripts/autocommit.txtar, internal/cmd/testdata/scripts/edgecases.txtar, internal/cmd/testdata/scripts/generate.txtar
=> feat: Improve configurability of automatic git commit messages

internal/chezmoi/format.go, internal/chezmoi/relpath.go, internal/cmd/config.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/templatefuncs.txtar
=> fix: Don't escape HTML characters in JSON strings

assets/chezmoi.io/docs/reference/templates/pass-functions/index.md, assets/chezmoi.io/docs/what-does-chezmoi-do.md
=> docs: Document support for the passage password manager

assets/chezmoi.io/docs/developer/building-on-top-of-chezmoi.md, assets/chezmoi.io/docs/developer/website.md, assets/chezmoi.io/docs/reference/templates/variables.md, assets/chezmoi.io/docs/user-guide/password-managers/bitwarden.md, assets/scripts/install.ps1
=> chore: Fix typo

internal/cmd/testdata/scripts/issue3349.txtar
=> chore: Add test for symlinks in source directory

assets/chezmoi.io/docs/reference/templates/functions/fromJson.md, assets/chezmoi.io/mkdocs.yml, internal/cmd/config.go, internal/cmd/templatefuncs.go, internal/cmd/templatefuncs_test.go, internal/cmd/testdata/scripts/issue3325.txtar
Fixes #3325.
As suggested by @mcexit in https://github.com/twpayne/chezmoi/issues/3325#issuecomment-1818878011.
@mcexit I've put you as co-author on this obviously. Would you be able to review and/or test this code? GitHub won't let me add you as a reviewer.
=> feat: Preserve integer values in fromJson and fromJsonc template funcs

internal/cmd/config.go, internal/cmd/testdata/scripts/issue3371.txtar
=> fix: Set env vars from config file when re-reading config

internal/chezmoi/path_unix.go, internal/chezmoi/path_windows.go, internal/cmd/testdata/scripts/issue3374.txtar
=> fix: Handle extra slashes in path arguments

assets/chezmoi.io/docs/reference/configuration-file/hooks.md, internal/cmd/config.go, internal/cmd/templatefuncs.go
Refs https://github.com/twpayne/chezmoi/discussions/3342#discussioncomment-7716619.
=> feat: Add CHEZMOI_COMMAND_DIR env var for hooks

internal/cmd/testdata/scripts/mackupbrew_darwin.txtar
=> chore: Make mackup command test more realistic

internal/cmd/cdcmd.go
=> feat: Remove nested subshell check

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md
Found an error in the "encryption" documentation.
Fixed it for you. ;)
=> fix: key.txt is not written to home, but home/.config

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoi-format-tmpl.md, internal/chezmoi/sourcestate.go, internal/cmd/executetemplatecmd.go, internal/cmd/testdata/scripts/issue3418.txtar
=> fix: Make execute-template --init not read .chezmoitemplates

assets/chezmoi.io/docs/reference/source-state-attributes.md, internal/chezmoi/attr.go, internal/chezmoi/attr_test.go, internal/chezmoi/sourcestate.go, internal/cmd/chattrcmd.go, internal/cmd/testdata/scripts/chattr.txtar, internal/cmd/testdata/scripts/issue3415.txtar
Fixes #3415.
This PR has the nice stats of removing code and also increasing functionality :)
=> feat: Extend remove_ attribute to directories

assets/chezmoi.io/docs/user-guide/use-scripts-to-perform-actions.md, internal/cmd/testdata/scripts/issue3421.txtar
=> docs: Fix guide on clearing state of run_onchange_ scripts

assets/chezmoi.io/docs/reference/templates/bitwarden-functions/rbw.md, assets/chezmoi.io/docs/reference/templates/bitwarden-functions/rbwFields.md, internal/cmd/rbwtemplatefuncs.go, internal/cmd/testdata/scripts/rbw.txtar
=> feat: Extend rbw and rbwFields template funcs to take extra args

internal/chezmoi/entrytypeset.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestateentry.go, internal/cmd/testdata/scripts/issue3414.txtar
=> fix: Handle implicit directories in externals

internal/cmd/config.go, internal/cmd/datacmd_test.go, internal/cmd/diffcmd_test.go, internal/cmd/lazywriter.go, internal/cmd/testdata/scripts/diffcommand_unix.txtar
=> fix: Only invoke diff pager if there is diff output

internal/chezmoi/sourcestate.go, internal/cmd/applycmd_test.go, internal/cmd/config.go, internal/cmd/testdata/scripts/issue2132.txtar
=> fix: Fix detection of changes to remove_ directories

assets/chezmoi.io/docs/reference/commands/status.md
=> docs: Add explanation of status characters

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, internal/cmd/addcmd.go, internal/cmd/testdata/scripts/addencrypted.txtar
=> feat: Add add.encrypt configuration variable

internal/cmd/keepassxctemplatefuncs.go, internal/cmd/keepassxctemplatefuncs_test.go, internal/cmd/templatefuncs.go, internal/cmd/templatefuncs_test.go
=> fix: Improve robustness of keepassxc-cli integration in open mode

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
=> chore: move secrets-variable to the correct subsection

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, internal/chezmoi/ageencryption.go
=> docs: Fix names of age recipients files config variables

assets/chezmoi.io/docs/user-guide/manage-machine-to-machine-differences.md
=> docs: add link

internal/cmd/keepassxctemplatefuncs.go
=> fix: Reduce injection of terminal control characters into keepassxc-cli output

internal/cmd/onepasswordtemplatefuncs.go
=> chore: Remove unused function

.github/workflows/main.yml, assets/chezmoi.io/docs/developer/developing-locally.md, assets/chezmoi.io/docs/user-guide/encryption/rage.md, assets/chezmoi.io/mkdocs.yml, internal/chezmoi/ageencryption_test.go, internal/chezmoi/encryption.go, internal/chezmoi/gpgencryption.go, internal/chezmoitest/chezmoitest.go, internal/cmd/main_test.go
=> feat: Support rage as an alternative age encryption command

internal/chezmoi/lazy.go, internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestateentry.go, internal/chezmoi/targetstateentry.go, internal/cmd/testdata/scripts/issue3510.txtar
=> fix: Defer lookup of git in $PATH for git-repo externals

assets/chezmoi.io/docs/reference/templates/init-functions/promptStringOnce.md
=> docs: typo

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml
=> docs: Cross link "See REF" in config variables doc

internal/chezmoi/abspath.go, internal/chezmoi/chezmoi_unix.go, internal/chezmoi/chezmoi_windows.go, internal/cmd/config.go, internal/cmd/upgradecmd_unix.go, internal/cmd/upgradecmd_windows.go
Fixes #3561.
I think this is right. Please find ways to break it :)
cc @Kreijstal
=> fix: Prioritize $HOME over %userprofile% on Windows for Cygwin/msys2 compatibility

assets/chezmoi.io/docs/user-guide/tools/editor.md
=> docs: Update docs on auto applying changes on edit in VIM

assets/scripts/install-local-bin.sh, assets/scripts/install.sh, internal/cmds/generate-install.sh/install.sh.tmpl
=> fix: Use uname -o to detect Android in install script

internal/chezmoi/sourcestate.go, internal/chezmoi/sourcestatetreenode.go, internal/chezmoi/sourcestatetreenode_test.go, internal/cmd/testdata/scripts/issue3525.txtar
=> fix: Don't attempt to add entries in external_ directories

internal/cmd/catcmd.go, internal/cmd/chattrcmd.go, internal/cmd/config.go, internal/cmd/editcmd.go, internal/cmd/forgetcmd.go, internal/cmd/mergecmd.go, internal/cmd/readdcmd.go, internal/cmd/removecmd.go
=> fix: Fix panic when merging unmanaged file

internal/cmd/unmanagedcmd.go
=> fix: Fix --keep-going flag for unmanaged command

internal/chezmoi/abspath.go, internal/chezmoi/ageencryption_test.go, internal/cmd/autobool.go, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/datacmd_test.go, internal/cmd/severity.go, internal/cmd/testdata/scripts/issue3582.txtar, internal/cmd/textconv.go
=> fix: Fix config marshaling/unmarshaling

.github/workflows/main.yml
Refs https://github.com/twpayne/chezmoi/pull/3584#issuecomment-1963091632.
=> chore: Exclude install.sh.tmpl from code changes

assets/chezmoi.io/docs/user-guide/include-files-from-elsewhere.md
Description: Fix a small grammar mistake with repeated words in the docs.
=> docs: fix a grammar mistake

internal/cmd/cmd.go, internal/cmd/testdata/scripts/plugin.txtar
=> fix: Set CHEZMOI_ environment variables for plugins

internal/cmd/purgecmd.go, internal/cmd/unmanagedcmd.go
Refs https://github.com/twpayne/chezmoi/issues/3588#issuecomment-1975038722.
=> fix: Add missing newlines in error messages

internal/cmd/executetemplatecmd.go, internal/cmd/interactivetemplatefuncs.go, internal/cmd/templatefuncs.go
=> fix: Increase range of types accepted by promptChoice template function

internal/chezmoi/sourcestate.go, internal/cmd/addcmd_test.go, internal/cmd/testdata/scripts/issue3666.txtar
=> fix: Fix panic when adding children in exact_ dirs

internal/chezmoi/ageencryption.go, internal/chezmoi/sourcestate.go, internal/cmd/keepassxctemplatefuncs.go
=> chore: fix function names in comment

internal/chezmoi/sourcestate.go, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/testdata/scripts/issue3693.txtar, internal/cmd/util_unix.go, internal/cmd/util_windows.go
=> fix: Fix panic on empty external

internal/chezmoi/sourcestate.go, internal/cmd/cmd.go, internal/cmd/util.go
=> Fix function names

assets/chezmoi.io/docs/quick-start.md
=> docs: Fix origin URL in quick start guide

internal/cmd/config.go, internal/cmd/testdata/scripts/apply.txtar, internal/cmd/testdata/scripts/external.txtar, internal/cmd/testdata/scripts/keepgoing.txtar, internal/cmd/testdata/scripts/noencryption.txtar, internal/cmd/testdata/scripts/scriptsdir_unix.txtar
=> feat: Include name of target in error message

assets/chezmoi.io/docs/reference/command-line-flags/common.md, internal/chezmoitest/chezmoitest.go, internal/chezmoitest/chezmoitest_test.go, internal/cmd/config.go, internal/cmd/ignoredcmd.go, internal/cmd/managedcmd.go, internal/cmd/pathlist.go, internal/cmd/pathlist_test.go, internal/cmd/testdata/scripts/ignore.txtar, internal/cmd/testdata/scripts/managedtree.txtar, internal/cmd/testdata/scripts/unmanagedtree.txtar, internal/cmd/unmanagedcmd.go, internal/cmd/util.go
=> feat: Add --tree flag to commands that produce a list of files

internal/chezmoi/sourcestate.go, internal/cmd/applycmd_test.go, internal/cmd/testdata/scripts/issue3703.txtar
=> fix: Remove unmanaged files from exact_ directories containing external files

internal/chezmoi/sourcestate.go, internal/cmd/applycmd_test.go, internal/cmd/testdata/scripts/issue2597.txtar
=> fix: Apply .chezmoiignore to dirs in external archives

assets/chezmoi.io/docs/links/articles.md.yaml
=> Fix: Links section broken in docs at chezmoi.io

.goreleaser.yaml
Refs https://github.com/goreleaser/goreleaser/issues/4816. Probably a bug in snapcraft.
=> chore: Temporarily disable snapcraft builds

.github/workflows/main.yml, .golangci.yml, internal/chezmoibubbles/chezmoibubbles_test.go, internal/chezmoiset/chezmoiset.go, internal/cmd/prompt.go
Refs https://github.com/golangci/golangci-lint-action/issues/23.
=> chore: Fix file exists errors when running golangci-lint GitHub Action

internal/cmd/testdata/scripts/issue3744.txtar
=> chore: Add test for #3744

.github/workflows/main.yml, internal/chezmoi/realsystem_windows.go
Refs https://github.com/twpayne/chezmoi/pull/3762#issuecomment-2107031294.
=> chore: Run golangci-lint on all OSes

internal/cmd/editcmd.go, internal/cmd/editconfigtemplatecmd.go, internal/cmds/execute-template/main.go
=> fix: Respect umask when creating files

internal/cmd/readhttpresponse.go
Fixes #3662.
Fixes #3758.
Refs https://github.com/charmbracelet/bubbletea/issues/1016.
=> fix: Don't panic on unexpected bubbletea messages

internal/cmd/config.go
=> fix: Fix panic when parsing some commands

Makefile
Just a little meta thing to make it easier to have done as the html comment requests
=> chore: lint: don't assume origin (e.g. after $(gh repo fork))

internal/chezmoi/sourcestate_test.go, internal/chezmoi/template.go
=> fix: Accept line-endings template directive as well as line-ending

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md, internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/external.txtar
=> feat: Allow private_ and readonly_ attrs to be set for externals

internal/cmd/addcmd.go
=> fix: Prevent chezmoi add from adding chezmoi's own executable

assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiexternal-format.md, internal/chezmoi/compression.go, internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/externalcompression.txtar
=> feat: Add decompression of file externals

internal/chezmoi/sourcestate.go, internal/cmd/config.go, internal/cmd/testdata/scripts/scripttempdir.txtar
=> fix: Use scriptTempDir for modify_ scripts

internal/cmd/config.go, internal/cmd/config_test.go
When trying to exec 'chezmoi init' or 'chezmoi apply --init'  with .chezmoi.toml.tmpl including another file through 'includeTemplate', the initTemplateFuncs are only available in the first file, but not in the included template.
This is because the initial execution operates on a copy of c.templateFuncs, which wouldn't get passed on to includeTemplateTemplateFunc.
With this change, initFunctions will be added directly to c.templateFuncs and then removed after the config has been generated.
Note: Due to a separate implementation, 'chezmoi execute-template --init' is not affected by this bug.
=> fix: keep initFuncs when using 'includeTemplate' in config

assets/chezmoi.io/docs/user-guide/machines/containers-and-vms.md
=> docs: Clarify requirement to set sourceDir when used in Codespaces

internal/chezmoi/chezmoi.go, internal/chezmoi/chezmoi_unix.go, internal/chezmoi/chezmoi_windows.go, internal/cmd/readdcmd.go, internal/cmd/readdcmd_test.go, internal/cmd/testdata/scripts/issue3891.txtar
=> fix: Ignore permission changes in re-add command on Windows

internal/cmd/applycmd_test.go, internal/cmd/config.go
=> fix: Set User-Agent header to chezmoi.io/version on all HTTP requests

go.mod, go.sum, main.go
Thanks to @ghouscht for his talk at Bärner Go :)
=> feat: Set GOMAXPROCS based on available resources

assets/chezmoi.io/docs/index.md.tmpl, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/design.md
=> fix: Improve phonetic pronunciation of chezmoi

.github/workflows/installer.yml, .github/workflows/main.yml
Refs https://github.com/actions/runner-images/issues/10721.
=> chore: Move to macos-13 GitHub Action runners

internal/cmd/config.go, internal/cmd/config_test.go
* If `[age]` config is present but `encryption` is not set, respect `useBuiltinAge` config anyway. This behaviour is aligned with chezmoi docs. Remove confusing comment, encryption is used only when either `[age]` or `[gpg]` configs are provided.
* Because having age or gpg configs with `encryption` not set is unexpected, show warning about that.
* Add bunch of unit tests to check new behaviour.
This is the first time I'm writing in Go, I'd appreciate your feedback.
Fixes #3980
=> fix: Use builtin age when encryption is unset

assets/chezmoi.io/docs/reference/command-line-flags/common.md, internal/cmd/applycmd.go, internal/cmd/archivecmd.go, internal/cmd/config.go, internal/cmd/config_test.go, internal/cmd/diffcmd.go, internal/cmd/dumpcmd.go, internal/cmd/statuscmd.go, internal/cmd/testdata/scripts/issue3987.txtar, internal/cmd/updatecmd.go, internal/cmd/verifycmd.go
=> feat: Add common --parent-dirs/-P flag

internal/cmd/config.go, internal/cmd/interactivetemplatefuncs.go, internal/cmd/templatefuncs.go, internal/cmd/templatefuncs_test.go
=> feat: Extend quote and quoteList template funcs to handle more types

internal/cmd/catcmd.go, internal/cmd/chattrcmd.go, internal/cmd/config.go, internal/cmd/destroycmd.go, internal/cmd/editcmd.go, internal/cmd/forgetcmd.go, internal/cmd/mergecmd.go, internal/cmd/readdcmd.go, internal/cmd/testdata/scripts/issue4012.txtar
=> fix: Fix panic when running chattr on externals

internal/cmd/lazywriter.go, internal/cmd/testdata/scripts/issue4027.txtar
=> fix: Fix panic when --keep-going is set

internal/cmd/agecmd.go, internal/cmd/annotation.go, internal/cmd/catcmd.go, internal/cmd/catconfigcmd.go, internal/cmd/cdcmd.go, internal/cmd/chattrcmd.go, internal/cmd/completioncmd.go, internal/cmd/datacmd.go, internal/cmd/decryptcmd.go, internal/cmd/doctorcmd.go, internal/cmd/dumpconfigcmd.go, internal/cmd/editconfigcmd.go, internal/cmd/editconfigtemplatecmd.go, internal/cmd/encryptcmd.go, internal/cmd/generatecmd.go, internal/cmd/gitcmd.go, internal/cmd/helpcmd.go, internal/cmd/ignoredcmd.go, internal/cmd/licensecmd.go, internal/cmd/managedcmd.go, internal/cmd/mergeallcmd.go, internal/cmd/mergecmd.go, internal/cmd/purgecmd.go, internal/cmd/sourcepathcmd.go, internal/cmd/statecmd.go, internal/cmd/targetpathcmd.go, internal/cmd/testdata/scripts/issue4024.txtar, internal/cmd/unmanagedcmd.go, internal/cmd/upgradecmd.go
=> fix: Fix incorrect config template change warnings

internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/issue4002.txtar
=> fix: Fix includeTemplate template func search path in init

internal/cmd/catcmd.go, internal/cmd/managedcmd.go, internal/cmd/mergecmd.go, internal/cmd/unmanagedcmd.go
=> fix: Persist results of calls to GitHub API

assets/chezmoi.io/docs/reference/special-files/chezmoiexternal-format.md
Follow up to https://github.com/twpayne/chezmoi/issues/4014.
I verified that this indeed works.
=> docs: Add note that .chezmoiexternal files can be ignored

internal/cmd/config.go
Make sure all handles are awaited and closed even if chezmoi command returns error.
* Cobra doesn't run `PersistentPostRunE` in case of error (https://github.com/spf13/cobra/issues/1893), move such logic to `OnFinalize` as suggested workaround.
* Keep config verification, auto git commands and run hooks only for successful commands.
* Make best effort to close all handles, print message and continue on error.
Fixes #3995
=> fix: Perform post-run actions on error

.github/workflows/govulncheck.yml, .github/workflows/installer.yml, .github/workflows/lock-threads.yml, .github/workflows/main.yml
See https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions.
=> chore: Cancel in-progress GitHub Actions

assets/chezmoi.io/docs/links/articles.md.yaml
=> docs: Add link to article

assets/chezmoi.io/docs/reference/commands/managed.md, assets/chezmoi.io/snippets/common-flags/path-style.md, internal/chezmoi/relpath.go, internal/chezmoi/sourcerelpath.go, internal/cmd/config.go, internal/cmd/managedcmd.go, internal/cmd/pathstyle.go, internal/cmd/testdata/scripts/completion.txtar, internal/cmd/testdata/scripts/managed.txtar
=> feat: Add --path-style=all option to managed command

.github/workflows/clear-pr-caches.yml, .github/workflows/main.yml
This is the slowest job now, get final signal 6 minutes earlier.
=> chore: Split test-ubuntu job by umask

.github/workflows/main.yml
It prints compiled modules to have some insights what this step is doing.
=> chore: Add -v flag to go build

assets/chezmoi.io/docs/links/articles.md.yaml, assets/chezmoi.io/docs/links/videos.md.yaml
This is such a great tool! 
I was looking for a simple guide to understand the workflow of Chezmoi, but I found that the tutorial and official documentation were a bit unclear in some parts. As a result, I had to rely on trial and error :) to figure out how things work.
Unfortunately, I couldn't find a guide in Arabic in the official documentation, so I decided to create one after learning the key concepts, such as:
- Basic Workflow
- Templating
- Encryption
I hope this guide is helpful and contributes to making the official documentation even more comprehensive!
=> Add Arabic resources to the docs

internal/chezmoi/sourcestate.go
=> chore: fix some function names in comment

internal/cmd/addcmd_test.go, internal/cmd/choiceflag.go, internal/cmd/testdata/scripts/issue4104.txtar
=> fix: Fix error when choice variables are set in flags and config file

assets/chezmoi.io/docs/reference/templates/variables.md, internal/cmd/config.go
=> feat: Add .chezmoi.destDir template variable

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/usage.md
=> docs: Describe how to use tools installed with Flatpak

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, internal/cmd/config.go, internal/cmd/readdcmd.go
=> feat: Add interactive config variable

internal/cmd/testdata/scripts/edgecasesumask.txtar
=> chore: Fix hang in tests when umask is 027

go.mod, internal/cmd/nozerolog.go, internal/cmd/testdata/scripts/gitleaks.txtar
Refs https://github.com/gitleaks/gitleaks/issues/1684.
=> fix: Suppress gitleaks logspam

assets/chezmoi.io/docs/reference/commands/init.md, assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, internal/cmd/gitcmd.go, internal/cmd/initcmd.go, internal/cmd/testdata/scripts/initgitlfs.txtar
=> feat: Add --git-lfs option to init command

assets/chezmoi.io/docs/reference/templates/functions/warnf.md, assets/chezmoi.io/mkdocs.yml, assets/templates/COMMIT_MESSAGE.tmpl, internal/chezmoigit/status_test.go, internal/cmd/config.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/autocommit.txtar, internal/cmd/testdata/scripts/issue3344.txtar
=> fix: Warn, don't error, when generating git commit messages for unknown states

internal/chezmoi/boltpersistentstate.go, internal/chezmoi/boltpersistentstate_test.go, internal/chezmoi/debugpersistentstate.go, internal/chezmoi/mockpersistentstate.go, internal/chezmoi/nullpersistentstate.go, internal/chezmoi/persistentstate.go, internal/cmd/ignoredcmd.go, internal/cmd/sourcepathcmd.go, internal/cmd/targetpathcmd.go, internal/cmd/testdata/scripts/state.txtar
=> fix: Fix persistent state mode for commands that execute templates

internal/cmd/chattrcmd.go
=> fix: Fix persistent state mode in chattr command

assets/chezmoi.io/docs/reference/special-directories/chezmoidata.md, assets/chezmoi.io/docs/reference/special-files/chezmoidata-format.md
Refs https://github.com/twpayne/chezmoi/discussions/4220#discussioncomment-11950046
=> docs: Update wording in .chezmoidata pages

internal/cmd/cdcmd.go
Fixes #4279.
@halostatue would you be able to test this?
=> fix: Fix persistent state mode when using cd command with an argument

assets/chezmoi.io/docs/user-guide/encryption/age.md
=> docs: Add example of multiple age recipients

.github/workflows/main.yml, assets/scripts/install-local-bin.sh, assets/scripts/install.sh, internal/cmds/generate-install.sh/install.sh.tmpl
=> fix: Fallback to statically-linked binary on old Linuxes

internal/chezmoi/sourcestate.go, internal/cmd/testdata/scripts/issue4315.txtar
Refs #4315.
This PR does two things:
* Adds a test for what #4315 fixed.
* Tidies up a few comments and variable names that were also fixed in #4315.
Thank you to @qianlongzt for the original debugging and fix!
=> chore: Add a test for repeated template evaluation

completions/chezmoi.ps1, internal/cmd/completioncmd.go
=> feat: Include description in PowerShell completions

internal/cmd/config.go
=> feat: Set LESS and LV env vars the same way that git does

assets/chezmoi.io/docs/user-guide/tools/diff.md
This is @KapJI's work from #4207.
Closes #4205.
Closes #4207.
=> docs: Update docs for using delta

assets/chezmoi.io/docs/reference/commands/edit.md, internal/cmd/helps.gen.go
=> docs: Add note on templates in edit command

internal/cmd/catconfigcmd.go, internal/cmd/config.go, internal/cmd/datacmd.go, internal/cmd/doctorcmd.go, internal/cmd/dumpconfigcmd.go, internal/cmd/editconfigcmd.go, internal/cmd/editconfigtemplatecmd.go, internal/cmd/helpcmd.go, internal/cmd/ignoredcmd.go, internal/cmd/licensecmd.go, internal/cmd/purgecmd.go, internal/cmd/updatecmd.go, internal/cmd/upgradecmd.go
=> feat: completion improvements

assets/chezmoi.io/docs/reference/templates/directives.md, internal/chezmoi/template.go, internal/cmd/main_test.go, internal/cmd/testdata/scripts/templatedirectives.txtar
=> feat: Add encoding template directive for Windows

assets/chezmoi.io/docs/reference/commands/execute-template.md, internal/cmd/executetemplatecmd.go, internal/cmd/helps.gen.go, internal/cmd/testdata/scripts/executetemplate.txtar
As suggested by @bradenhilton in https://github.com/twpayne/chezmoi/discussions/4389#discussioncomment-12685877.
=> feat: Add --file flag to execute-template command

go.mod, go.sum
=> fix: Fix truncated placeholder in choice input

internal/cmd/executetemplatecmd.go, internal/cmd/testdata/scripts/executetemplate.txtar, internal/cmd/upgradecmd.go, internal/cmd/upgradecmd_windows.go
=> chore: Normalize path in .chezmoi.sourceFile in execute-template

internal/chezmoi/abspath.go, internal/chezmoi/gitdiffsystem.go, internal/chezmoi/sourcestate.go, internal/cmd/diffcmd_test.go
=> fix: Improve diff command output when removing files

assets/chezmoi.io/docs/reference/special-files/chezmoiexternal-format.md
=> docs: Add a note about private externals

assets/chezmoi.io/docs/reference/special-directories/chezmoidata.md, assets/chezmoi.io/docs/reference/special-files/chezmoidata-format.md
=> docs: Document that only dictionaries are merged

assets/chezmoi.io/docs/reference/special-directories/chezmoidata.md, assets/chezmoi.io/docs/reference/special-files/chezmoidata-format.md
=> docs: fix link

internal/cmd/config.go
=> fix: Exit with failure when apply is cancelled

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/usage.md, assets/chezmoi.io/docs/user-guide/use-scripts-to-perform-actions.md
=> docs: Emphasize that scriptEnv also applies to hooks and commands

assets/chezmoi.io/docs/reference/special-files/chezmoiroot.md, assets/chezmoi.io/docs/user-guide/advanced/customize-your-source-directory.md
Per https://github.com/twpayne/chezmoi/issues/4494
=> docs: add warnings to .chezmoiroot

assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml, internal/cmd/config.go, internal/cmd/diffcmd.go, internal/cmd/testdata/scripts/pager.txtar
Fixes #4480.
@halostatue does this make sense to you?
=> feat: Add pagerArgs and diff.pagerArgs configuration variables

assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md, assets/chezmoi.io/docs/user-guide/frequently-asked-questions/usage.md, assets/chezmoi.io/docs/user-guide/include-files-from-elsewhere.md, assets/chezmoi.io/docs/user-guide/machines/containers-and-vms.md, assets/chezmoi.io/docs/user-guide/machines/macos.md
=> docs: Recommend run_onchange_ scripts over run_once_ scripts

assets/chezmoi.io/docs/reference/templates/functions/comment.md, assets/chezmoi.io/docs/reference/templates/functions/ensureLinePrefix.md, assets/chezmoi.io/mkdocs.yml, internal/cmd/config.go, internal/cmd/templatefuncs.go, internal/cmd/testdata/scripts/templatefuncs.txtar
Fixes #4518.
Draft for now, as the documentation could be much better.
cc @felipecrs for feedback.
=> feat: Add ensureLinePrefix template function

internal/cmd/readdcmd.go, internal/cmd/testdata/scripts/addsecrets.txtar
=> feat: Check for secrets in re-add command

assets/chezmoi.io/docs/reference/templates/functions/returnEmpty.md, assets/chezmoi.io/mkdocs.yml, internal/chezmoi/sourcestate.go, internal/chezmoi/templatefuncs.go, internal/cmd/config.go, internal/cmd/testdata/scripts/templatefuncs.txtar
=> feat: Add returnEmpty template function

internal/chezmoi/externaldiffsystem.go, internal/cmd/config.go, internal/cmd/readdcmd.go
=> fix: Use external diff tool for apply and re-add previews

internal/chezmoi/externaldiffsystem.go, internal/cmd/config.go, internal/cmd/testdata/scripts/issue4500.txtar
=> fix: Always use diff.pager if configured

assets/chezmoi.io/docs/reference/source-state-attributes.md, assets/chezmoi.io/docs/reference/target-types.md, assets/chezmoi.io/docs/user-guide/use-scripts-to-perform-actions.md
=> docs: Clarify scripts have to succeed to count as being run

go.mod, go.sum, internal/chezmoi/diff.go
znkr.io/diff is new, but seems well-tested.
The changes to the tests in this PR are surprising. I would like to understand them before marking this PR ready for review.
=> feat: Switch to znkr.io/diff for builtin diff

internal/cmd/initcmd.go, internal/cmd/testdata/scripts/issue4662.txtar
=> fix: Make init --apply run apply pre and post hooks

Makefile, assets/chezmoi.io/docs/reference/commands/destroy.md, assets/chezmoi.io/docs/reference/commands/ssh.md, internal/cmd/cmd.go, internal/cmd/helps.gen.go, internal/cmds/generate-helps/main.go
=> fix: Add destroy and ssh command descriptions to help

internal/cmd/addcmd.go, internal/cmd/testdata/scripts/issue3772.txtar
=> fix: Report an error when --follow and --recursive are combined for directories
